package neo4jutil

const (
	NodeLabelTenant                    = "Tenant"
	NodeLabelTenantSettings            = "TenantSettings"
	NodeLabelTenantBillingProfile      = "TenantBillingProfile"
	NodeLabelBankAccount               = "BankAccount"
	NodeLabelTimelineEvent             = "TimelineEvent"
	NodeLabelContact                   = "Contact"
	NodeLabelCustomField               = "CustomField"
	NodeLabelJobRole                   = "JobRole"
	NodeLabelEmail                     = "Email"
	NodeLabelLocation                  = "Location"
	NodeLabelInteractionEvent          = "InteractionEvent"
	NodeLabelInteractionSession        = "InteractionSession"
	NodeLabelNote                      = "Note"
	NodeLabelLogEntry                  = "LogEntry"
	NodeLabelOrganization              = "Organization"
	NodeLabelBillingProfile            = "BillingProfile"
	NodeLabelMasterPlan                = "MasterPlan"
	NodeLabelMasterPlanMilestone       = "MasterPlanMilestone"
	NodeLabelAction                    = "Action"
	NodeLabelPageView                  = "PageView"
	NodeLabelPhoneNumber               = "PhoneNumber"
	NodeLabelTag                       = "Tag"
	NodeLabelIssue                     = "Issue"
	NodeLabelUser                      = "User"
	NodeLabelAnalysis                  = "Analysis"
	NodeLabelAttachment                = "Attachment"
	NodeLabelMeeting                   = "Meeting"
	NodeLabelSocial                    = "Social"
	NodeLabelPlayer                    = "Player"
	NodeLabelCountry                   = "Country"
	NodeLabelActionItem                = "ActionItem"
	NodeLabelComment                   = "Comment"
	NodeLabelContract                  = "Contract"
	NodeLabelDeletedContract           = "DeletedContract"
	NodeLabelServiceLineItem           = "ServiceLineItem"
	NodeLabelOpportunity               = "Opportunity"
	NodeLabelInvoicingCycle            = "InvoicingCycle"
	NodeLabelExternalSystem            = "ExternalSystem"
	NodeLabelInvoice                   = "Invoice"
	NodeLabelInvoiceLine               = "InvoiceLine"
	NodeLabelOrganizationPlan          = "OrganizationPlan"
	NodeLabelOrganizationPlanMilestone = "OrganizationPlanMilestone"
	NodeLabelReminder                  = "Reminder"
)
