apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: customer-os-api           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: customer-os-api        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: customer-os-api
    spec:                        # Spec for the container which will run in the Pod
      containers:
        - image: ghcr.io/openline-ai/openline-customer-os/customer-os-api:otter
          name: customer-os-api
          imagePullPolicy: Never
          ports:
            - containerPort: 1010  # Should match the port number that the Go application listens on
          livenessProbe:           # To check the health of the Pod
            httpGet:
              path: /health
              port: 1010
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:          # To check if the Pod is ready to serve traffic or not
            httpGet:
              path: /readiness
              port: 1010
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
          env:
            - name: NEO4J_TARGET
              value: "neo4j://neo4j-customer-os.openline.svc.cluster.local:7687"
            - name: NEO4J_AUTH_USER
              value: "neo4j"
            - name: NEO4J_AUTH_PWD
              value: "StrongLocalPa$$$"
            - name: NEO4J_AUTH_REALM
              value: ""
            - name: NEO4J_MAX_CONN_POOL_SIZE 
              value: "100"
            - name: GRAPHQL_PLAYGROUND_ENABLED
              value: "true"
            - name: NEO4J_LOG_LEVEL
              value: "INFO"
            - name: PORT
              value: "1010"
