export {
  useGetContactCommunicationChannelsQuery,
  useGetContactPersonalDetailsQuery,
  useCreateContactMutation,
  useUpdateContactEmailMutation,
  useAddEmailToContactMutation,
  useRemoveEmailFromContactMutation,
  useUpdateContactPhoneNumberMutation,
  useRemovePhoneNumberFromContactMutation,
  useAddPhoneToContactMutation,
  useCreateOrganizationNoteMutation,
  useCreateContactNoteMutation,
  useRemoveNoteMutation,
  useUpdateNoteMutation,
  useNoteLinkAttachmentMutation,
  useNoteUnlinkAttachmentMutation,
  DataSource,
  useGetContactNotesQuery,
  GetOrganizationTimelineDocument,
  GetContactTimelineDocument,
} from '../../graphQL/__generated__/generated';
export const NOW_DATE = new Date().toISOString();

export type {
  Contact,
  GetContactCommunicationChannelsQuery,
  GetContactPersonalDetailsQuery,
  ContactInput,
  CreateContactMutation,
  Email,
  UpdateContactEmailMutation,
  NoteInput,
  CreateOrganizationNoteMutation,
  CreateContactNoteMutation,
  GetContactNotesQuery,
  RemoveNoteMutation,
  NoteUpdateInput,
  UpdateNoteMutation,
  GetOrganizationTimelineQuery,
  Note,
  GetContactTimelineQuery,
  NoteLinkAttachmentMutation,
  NoteUnlinkAttachmentMutation,
} from '../../graphQL/__generated__/generated';
