# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/packages/server/customer-os-analytics-api"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "gomod"
      - "dependencies"
      - "app/customer-os-analytics-api"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/customer-os-api"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "gomod"
      - "dependencies"
      - "app/customer-os-api"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/customer-os-common-module"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "gomod"
      - "dependencies"
      - "module/customer-os-common-module"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/events-processing-common"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "gomod"
      - "dependencies"
      - "module/events-processing-common"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/events-processing-platform"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "gomod"
      - "dependencies"
      - "app/events-processing-platform"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/runner/sync-tracked-data"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "gomod"
      - "dependencies"
      - "app/sync-tracked-data"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/runner/sync-customer-os-data"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "gomod"
      - "dependencies"
      - "app/sync-customer-os-data"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/comms-api"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "gomod"
      - "dependencies"
      - "app/comms-api"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "gomod"
    directory: "/packages/server/file-store-api"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "gomod"
      - "dependencies"
      - "app/file-store-api"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "gomod"
    directory: "/packages/server/settings-api"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "gomod"
      - "dependencies"
      - "app/settings-api"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "gomod"
    directory: "/packages/server/validation-api"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "gomod"
      - "dependencies"
      - "app/validation-api"
    pull-request-branch-name:
      separator: "-"