# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/packages/server/customer-os-analytics-api"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 3
    labels:
      - "gomod"
      - "dependencies"
      - "analytics-api"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/customer-os-api"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 3
    labels:
      - "gomod"
      - "dependencies"
      - "customer-os-api"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/message-store"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 3
    labels:
      - "gomod"
      - "dependencies"
      - "message-store"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/runner/sync-tracked-data"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 3
    labels:
      - "gomod"
      - "dependencies"
      - "sync-tracked-data"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/runner/sync-customer-os-data"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 3
    labels:
      - "gomod"
      - "dependencies"
      - "sync-customer-os-data"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"