# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/packages/server/customer-os-api"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "go"
      - "dependencies"
      - "app/customer-os-api"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/customer-os-webhooks"
    schedule:
      interval: "daily"
      time: "04:30"
    open-pull-requests-limit: 5
    labels:
      - "go"
      - "dependencies"
      - "app/customer-os-webhooks"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/customer-os-common-module"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "go"
      - "dependencies"
      - "module/customer-os-common-module"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/customer-os-neo4j-repository"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "go"
      - "dependencies"
      - "module/customer-os-neo4j-repository"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/customer-os-postgres-repository"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "go"
      - "dependencies"
      - "module/customer-os-postgres-repository"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/events-processing-proto"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "go"
      - "dependencies"
      - "module/events-processing-proto"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/events-processing-platform"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "go"
      - "dependencies"
      - "app/events-processing-platform"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/events-subscribers"
    schedule:
      interval: "daily"
      time: "04:15"
    open-pull-requests-limit: 3
    labels:
      - "go"
      - "dependencies"
      - "app/events-subscribers"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/events-processing-platform-subscribers"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "go"
      - "dependencies"
      - "app/events-processing-platform-subscribers"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/runner/sync-customer-os-data"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "go"
      - "dependencies"
      - "app/sync-customer-os-data"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/runner/customer-os-dedup"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "go"
      - "dependencies"
      - "app/customer-os-dedup"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/runner/sync-gmail"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "go"
      - "dependencies"
      - "app/sync-gmail"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/runner/sync-slack"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "go"
      - "dependencies"
      - "app/sync-slack"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/runner/integrity-checker"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "go"
      - "dependencies"
      - "app/integrity-checker"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/mailsherpa-api"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "go"
      - "dependencies"
      - "app/mailsherpa-api"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/packages/server/customer-os-platform-admin-api"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "go"
      - "dependencies"
      - "app/customer-os-platform-admin-api"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"