export const mockData = [
  {
    month: 1,
    cancellations: 5,
    churned: 15,
    downgrades: 8,
    newlyContracted: 12,
    renewals: 18,
    upsells: 7,
  },
  {
    month: 2,
    cancellations: 8,
    churned: 10,
    downgrades: 5,
    newlyContracted: 14,
    renewals: 20,
    upsells: 3,
  },
  {
    month: 3,
    cancellations: 12,
    churned: 7,
    downgrades: 10,
    newlyContracted: 8,
    renewals: 15,
    upsells: 5,
  },
  {
    month: 4,
    cancellations: 6,
    churned: 12,
    downgrades: 7,
    newlyContracted: 10,
    renewals: 22,
    upsells: 9,
  },
  {
    month: 5,
    cancellations: 10,
    churned: 8,
    downgrades: 15,
    newlyContracted: 13,
    renewals: 16,
    upsells: 4,
  },
  {
    month: 6,
    cancellations: 14,
    churned: 5,
    downgrades: 9,
    newlyContracted: 11,
    renewals: 14,
    upsells: 6,
  },
  {
    month: 7,
    cancellations: 9,
    churned: 11,
    downgrades: 12,
    newlyContracted: 9,
    renewals: 17,
    upsells: 8,
  },
  {
    month: 8,
    cancellations: 11,
    churned: 14,
    downgrades: 6,
    newlyContracted: 15,
    renewals: 19,
    upsells: 2,
  },
  {
    month: 9,
    cancellations: 7,
    churned: 9,
    downgrades: 11,
    newlyContracted: 12,
    renewals: 21,
    upsells: 10,
  },
  {
    month: 10,
    cancellations: 13,
    churned: 13,
    downgrades: 8,
    newlyContracted: 7,
    renewals: 13,
    upsells: 5,
  },
  {
    month: 11,
    cancellations: 8,
    churned: 6,
    downgrades: 14,
    newlyContracted: 10,
    renewals: 18,
    upsells: 7,
  },
  {
    month: 12,
    cancellations: 10,
    churned: 10,
    downgrades: 10,
    newlyContracted: 10,
    renewals: 10,
    upsells: 10,
  },
];
