apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: comms-api-loadbalancer   # Name of the resource
spec:
  type: LoadBalancer
  ports:                         # Take incoming HTTP requests on port 8103 and forward them to the targetPort of 8013 
    - name: http
      port: 8013
      targetPort: 8013
  selector:
    app: comms-api         # Map any pod with label `app=comms-api` to this service
