apiVersion: v1
kind: Service
metadata:
  name: customer-os-api-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 10000
      targetPort: 10000
  selector:
    app: customer-os-api
