apiVersion: v1
kind: Service
metadata:
  name: events-processing-platform-loadbalancer
spec:
  type: LoadBalancer
  ports:                         # Take incoming HTTP requests on port 9009 and forward them to the targetPort of 9009
    - name: grpc
      port: 5001
      targetPort: 5001
  selector:
    app: events-processing-platform
