apiVersion: v1
kind: Service
metadata:
  name: events-processing-platform-service
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 5001
      targetPort: 5001
  selector:
    app: events-processing-platform
