apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: event-store-service   # Name of the resource
  annotations:
    'consul.hashicorp.com/service-sync': 'true'
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         
    - name: http
      port: 2113
      targetPort: 2113

  selector:
    app: event-store         # Map any pod with label `app=event-store` to this service
