apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-store-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-store-api
  template:
    metadata:
      labels:
        app: file-store-api
    spec:
      containers:
        - image: ghcr.io/openline-ai/openline-customer-os/file-store-api:latest
          name: file-store-api
          imagePullPolicy: Never
          ports:
            - containerPort: 10001
          livenessProbe:
            httpGet:
              path: /health
              port: 10001
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe: # To check if the Pod is ready to serve traffic or not
            httpGet:
              path: /readiness
              port: 10001
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "openline"
            - name: POSTGRES_HOST
              value: "customer-db-postgresql.openline.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_MAX_CONN
              value: "25"
            - name: POSTGRES_MAX_IDLE_CONN
              value: "10"
            - name: POSTGRES_CONN_MAX_LIFETIME
              value: "0"

            - name: NEO4J_TARGET
              value: "neo4j://customer-db-neo4j.openline.svc.cluster.local:7687"
            - name: NEO4J_AUTH_USER
              value: "neo4j"
            - name: NEO4J_AUTH_PWD
              value: "StrongLocalPa$$$"
            - name: NEO4J_AUTH_REALM
              value: ""
            - name: NEO4J_MAX_CONN_POOL_SIZE
              value: "100"
            - name: NEO4J_LOG_LEVEL
              value: "INFO"

            - name: PORT
              value: "10001"
            - name: BASE_URL
              value: "http://localhost:10001"

            - name: CUSTOMER_OS_API
              value: "http://customer-os-api-service.openline.svc.cluster.local:10000/query"
            - name: CUSTOMER_OS_API_KEY
              value: "dd9d2474-b4a9-4799-b96f-73cd0a2917e4"
            - name: FILE_STORE_API_JWT_SECRET
              value: "224ca5f5-7737-4fd6-a892-ddd40d7a7b0d"
