apiVersion: v1
kind: Service
metadata:
  name: file-storage-api-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 10001
      targetPort: 10001
  selector:
    app: file-storage-api
