apiVersion: v1
kind: Service
metadata:
  name: file-storage-api-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 10001
      targetPort: 10001
  selector:
    app: file-storage-api
