apiVersion: v1
kind: Service
metadata:
  name: auth-fusionauth-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: auth-fusionauth
    app.kubernetes.io/name: fusionauth
  ports:
    - name: http
      port: 9011
      targetPort: 9011
