apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: jaeger-loadbalancer   # Name of the resource
spec:
  type: LoadBalancer                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         
    - name: http
      port: 16686
      targetPort: 16686

  selector:
    app: jaeger         # Map any pod with label `app=event-store` to this service
