apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: udp-jaeger-thrift-compact-deprecated
      protocol: UDP
      port: 5775
      targetPort: 5775
    - name: udp-jaeger-thrift-compact
      protocol: UDP
      port: 6831
      targetPort: 6831
    - name: udp-jaeger-thrift-binary
      protocol: UDP
      port: 6832
      targetPort: 6832
    - name: http-sampling
      port: 5778
      targetPort: 5778
    - name: http-api
      port: 16676
      targetPort: 16686
    - name: http-spans
      port: 14268
      targetPort: 14268
    - name: http-zipkin
      port: 9411
      targetPort: 9411