apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: ory-tunnel-service   # Name of the resource
  annotations:
    'consul.hashicorp.com/service-sync': 'true'
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         
    - name: http
      port: 4000
      targetPort: 4000

  selector:
    app: ory-tunnel         # Map any pod with label `app=ory` to this service
