apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: efs-postgresql-claim # Sets name of PV
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 10Gi # Sets volume size