apiVersion: v1
kind: Service
metadata:
  name: settings-api-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 10002
      targetPort: 10002
  selector:
    app: settings-api
