apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaces-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spaces-gui
  template:
    metadata:
      labels:
        app: spaces-gui
    spec:
      containers:
        - image: ghcr.io/openline-ai/openline-customer-os:latest
          name: spaces-gui
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
              name: http-port
