apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: transcription-api-service   # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 8014 and forward them to the targetPort of 8014
    - name: http
      port: 8014
      targetPort: 8014

  selector:
    app: transcription-api         # Map any pod with label `app=transcription-api` to this service
