apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: transcription-api           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: transcription-api     # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: transcription-api
    spec:                        # Spec for the container which will run in the Pod
      containers:
        - image: ghcr.io/openline-ai/openline-customer-os/transcription-api:latest
          name: transcription-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8014  # Should match the port number that the Go application listens on
              name: http-port
          env:
            - name: CUSTOMER_OS_API_URL
              value: "http://customer-os-api-service.openline.svc.cluster.local:10000"
            - name: CUSTOMER_OS_API_KEY
              value: "dd9d2474-b4a9-4799-b96f-73cd0a2917e4"
            - name: TRANSCRIPTION_KEY
              value: "b1ced267-43b9-4be1-a5ef-8d054e6f84c1"
            - name: VCON_API_URL
              value: "http://comms-api-service.openline.svc.cluster.local:8013"
            - name: VCON_API_KEY
              value: "92c04073-17c3-4e91-8326-516bbd0750a4"
            - name: FILE_STORE_API_URL
              value: "http://file-store-api-service.openline.svc.cluster.local:10001"
            - name: FILE_STORE_API_KEY
              value: "9eb87aa2-75e7-45b2-a1e6-53ed297d0ba8"
            - name: REPLICATE_API_TOKEN
              value: ""
