apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: transcription-api-loadbalancer   # Name of the resource
spec:
  type: LoadBalancer
  ports:                         # Take incoming HTTP requests on port 8104 and forward them to the targetPort of 8014 
    - name: http
      port: 8014
      targetPort: 8014
  selector:
    app: transcription-api         # Map any pod with label `app=transcription-api` to this service
