apiVersion: v1
kind: Service
metadata:
  name: user-admin-api-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 14001
      targetPort: 14001
  selector:
    app: user-admin-api
