export const organizationKeywords = {
  add_contact: [
    'add',
    'contact',
    'new',
    'create',
    'person',
    'individual',
    'entry',
  ],
  change_or_add_tags: ['change', 'add', 'tags', 'update', 'edit'],
  rename_org: [
    'rename',
    'org',
    'organization',
    'company',
    'update',
    'edit',
    'change',
  ],
  edit_website: [
    'edit',
    'website',
    'change',
    'domain',
    'link',
    'url',
    'web address',
  ],
  change_relationship: [
    'change',
    'relationship',
    'status',
    'update',
    'edit',
    'customer',
    'former customer',
    'unqualified',
  ],
  change_relationship_to_prospect: ['prospect', 'relationship', 'change'],
  change_relationship_to_customer: ['customer', 'relationship', 'change'],
  change_relationship_to_former_customer: [
    'former',
    'customer',
    'relationship',
    'change',
  ],
  change_relationship_to_unqualified: ['unqualified', 'relationship', 'change'],
  change_org_stage: [
    'change',
    'org',
    'stage',
    'edit',
    'update',
    'organization',
    'status',
  ],
  change_org_stage_to_lead: ['lead', 'stage'],
  change_org_stage_to_target: ['target', 'stage'],
  change_org_stage_to_trial: ['trial', 'stage'],
  change_org_stage_to_engaged: ['engaged', 'stage'],
  change_org_stage_to_not_a_fit: ['not a fit', 'stage'],
  archive_org: ['archive', 'org', 'delete', 'remove', 'hide', 'organization'],
  change_health_status: ['change', 'health', 'status', 'score', 'update'],
  assign_owner: ['assign', 'change', 'update', 'edit', 'owner'],
  create_new_opportunity: ['create', 'new', 'opportunity', 'add', 'deal'],
  change_onboarding_stage: [
    'change',
    'onboarding',
    'stage',
    'update',
    'status',
  ],
};
