import { QueryClient } from '@tanstack/react-query';
import { useOrganizationPeoplePanelQuery } from '@organization/graphql/organizationPeoplePanel.generated';

export function invalidateQuery(queryClient: QueryClient, id: string) {
  queryClient.invalidateQueries(useOrganizationPeoplePanelQuery.getKey({ id }));
}

export const timezoneOptions = [
  { label: 'Africa/Abidjan (UTC)', value: 'Africa/Abidjan (UTC)' },
  { label: 'Africa/Accra (UTC)', value: 'Africa/Accra (UTC)' },
  {
    label: 'Africa/Addis_Ababa (UTC +3)',
    value: 'Africa/Addis_Ababa (UTC +3)',
  },
  { label: 'Africa/Algiers (UTC +1)', value: 'Africa/Algiers (UTC +1)' },
  { label: 'Africa/Asmara (UTC +3)', value: 'Africa/Asmara (UTC +3)' },
  { label: 'Africa/Bamako (UTC)', value: 'Africa/Bamako (UTC)' },
  { label: 'Africa/Bangui (UTC +1)', value: 'Africa/Bangui (UTC +1)' },
  { label: 'Africa/Banjul (UTC)', value: 'Africa/Banjul (UTC)' },
  { label: 'Africa/Bissau (UTC)', value: 'Africa/Bissau (UTC)' },
  { label: 'Africa/Blantyre (UTC +2)', value: 'Africa/Blantyre (UTC +2)' },
  {
    label: 'Africa/Brazzaville (UTC +1)',
    value: 'Africa/Brazzaville (UTC +1)',
  },
  { label: 'Africa/Bujumbura (UTC +2)', value: 'Africa/Bujumbura (UTC +2)' },
  { label: 'Africa/Cairo (UTC +3)', value: 'Africa/Cairo (UTC +3)' },
  { label: 'Africa/Casablanca (UTC +1)', value: 'Africa/Casablanca (UTC +1)' },
  { label: 'Africa/Ceuta (UTC +2)', value: 'Africa/Ceuta (UTC +2)' },
  { label: 'Africa/Conakry (UTC)', value: 'Africa/Conakry (UTC)' },
  { label: 'Africa/Dakar (UTC)', value: 'Africa/Dakar (UTC)' },
  {
    label: 'Africa/Dar_es_Salaam (UTC +3)',
    value: 'Africa/Dar_es_Salaam (UTC +3)',
  },
  { label: 'Africa/Djibouti (UTC +3)', value: 'Africa/Djibouti (UTC +3)' },
  { label: 'Africa/Douala (UTC +1)', value: 'Africa/Douala (UTC +1)' },
  { label: 'Africa/El_Aaiun (UTC +1)', value: 'Africa/El_Aaiun (UTC +1)' },
  { label: 'Africa/Freetown (UTC)', value: 'Africa/Freetown (UTC)' },
  { label: 'Africa/Gaborone (UTC +2)', value: 'Africa/Gaborone (UTC +2)' },
  { label: 'Africa/Harare (UTC +2)', value: 'Africa/Harare (UTC +2)' },
  {
    label: 'Africa/Johannesburg (UTC +2)',
    value: 'Africa/Johannesburg (UTC +2)',
  },
  { label: 'Africa/Juba (UTC +2)', value: 'Africa/Juba (UTC +2)' },
  { label: 'Africa/Kampala (UTC +3)', value: 'Africa/Kampala (UTC +3)' },
  { label: 'Africa/Khartoum (UTC +2)', value: 'Africa/Khartoum (UTC +2)' },
  { label: 'Africa/Kigali (UTC +2)', value: 'Africa/Kigali (UTC +2)' },
  { label: 'Africa/Kinshasa (UTC +1)', value: 'Africa/Kinshasa (UTC +1)' },
  { label: 'Africa/Lagos (UTC +1)', value: 'Africa/Lagos (UTC +1)' },
  { label: 'Africa/Libreville (UTC +1)', value: 'Africa/Libreville (UTC +1)' },
  { label: 'Africa/Lome (UTC)', value: 'Africa/Lome (UTC)' },
  { label: 'Africa/Luanda (UTC +1)', value: 'Africa/Luanda (UTC +1)' },
  { label: 'Africa/Lubumbashi (UTC +2)', value: 'Africa/Lubumbashi (UTC +2)' },
  { label: 'Africa/Lusaka (UTC +2)', value: 'Africa/Lusaka (UTC +2)' },
  { label: 'Africa/Malabo (UTC +1)', value: 'Africa/Malabo (UTC +1)' },
  { label: 'Africa/Maputo (UTC +2)', value: 'Africa/Maputo (UTC +2)' },
  { label: 'Africa/Maseru (UTC +2)', value: 'Africa/Maseru (UTC +2)' },
  { label: 'Africa/Mbabane (UTC +2)', value: 'Africa/Mbabane (UTC +2)' },
  { label: 'Africa/Mogadishu (UTC +3)', value: 'Africa/Mogadishu (UTC +3)' },
  { label: 'Africa/Monrovia (UTC)', value: 'Africa/Monrovia (UTC)' },
  { label: 'Africa/Nairobi (UTC +3)', value: 'Africa/Nairobi (UTC +3)' },
  { label: 'Africa/Ndjamena (UTC +1)', value: 'Africa/Ndjamena (UTC +1)' },
  { label: 'Africa/Niamey (UTC +1)', value: 'Africa/Niamey (UTC +1)' },
  { label: 'Africa/Nouakchott (UTC)', value: 'Africa/Nouakchott (UTC)' },
  { label: 'Africa/Ouagadougou (UTC)', value: 'Africa/Ouagadougou (UTC)' },
  { label: 'Africa/Porto-Novo (UTC +1)', value: 'Africa/Porto-Novo (UTC +1)' },
  { label: 'Africa/Sao_Tome (UTC)', value: 'Africa/Sao_Tome (UTC)' },
  { label: 'Africa/Tripoli (UTC +2)', value: 'Africa/Tripoli (UTC +2)' },
  { label: 'Africa/Tunis (UTC +1)', value: 'Africa/Tunis (UTC +1)' },
  { label: 'Africa/Windhoek (UTC +2)', value: 'Africa/Windhoek (UTC +2)' },
  { label: 'America/Adak (UTC -09)', value: 'America/Adak (UTC -09)' },
  {
    label: 'America/Anchorage (UTC -08)',
    value: 'America/Anchorage (UTC -08)',
  },
  { label: 'America/Anguilla (UTC -04)', value: 'America/Anguilla (UTC -04)' },
  { label: 'America/Antigua (UTC -04)', value: 'America/Antigua (UTC -04)' },
  {
    label: 'America/Araguaina (UTC -03)',
    value: 'America/Araguaina (UTC -03)',
  },
  {
    label: 'America/Argentina/Buenos_Aires (UTC -03)',
    value: 'America/Argentina/Buenos_Aires (UTC -03)',
  },
  {
    label: 'America/Argentina/Catamarca (UTC -03)',
    value: 'America/Argentina/Catamarca (UTC -03)',
  },
  {
    label: 'America/Argentina/Cordoba (UTC -03)',
    value: 'America/Argentina/Cordoba (UTC -03)',
  },
  {
    label: 'America/Argentina/Jujuy (UTC -03)',
    value: 'America/Argentina/Jujuy (UTC -03)',
  },
  {
    label: 'America/Argentina/La_Rioja (UTC -03)',
    value: 'America/Argentina/La_Rioja (UTC -03)',
  },
  {
    label: 'America/Argentina/Mendoza (UTC -03)',
    value: 'America/Argentina/Mendoza (UTC -03)',
  },
  {
    label: 'America/Argentina/Rio_Gallegos (UTC -03)',
    value: 'America/Argentina/Rio_Gallegos (UTC -03)',
  },
  {
    label: 'America/Argentina/Salta (UTC -03)',
    value: 'America/Argentina/Salta (UTC -03)',
  },
  {
    label: 'America/Argentina/San_Juan (UTC -03)',
    value: 'America/Argentina/San_Juan (UTC -03)',
  },
  {
    label: 'America/Argentina/San_Luis (UTC -03)',
    value: 'America/Argentina/San_Luis (UTC -03)',
  },
  {
    label: 'America/Argentina/Tucuman (UTC -03)',
    value: 'America/Argentina/Tucuman (UTC -03)',
  },
  {
    label: 'America/Argentina/Ushuaia (UTC -03)',
    value: 'America/Argentina/Ushuaia (UTC -03)',
  },
  { label: 'America/Aruba (UTC -04)', value: 'America/Aruba (UTC -04)' },
  { label: 'America/Asuncion (UTC -04)', value: 'America/Asuncion (UTC -04)' },
  { label: 'America/Atikokan (UTC -05)', value: 'America/Atikokan (UTC -05)' },
  { label: 'America/Bahia (UTC -03)', value: 'America/Bahia (UTC -03)' },
  {
    label: 'America/Bahia_Banderas (UTC -06)',
    value: 'America/Bahia_Banderas (UTC -06)',
  },
  { label: 'America/Barbados (UTC -04)', value: 'America/Barbados (UTC -04)' },
  { label: 'America/Belem (UTC -03)', value: 'America/Belem (UTC -03)' },
  { label: 'America/Belize (UTC -06)', value: 'America/Belize (UTC -06)' },
  {
    label: 'America/Blanc-Sablon (UTC -04)',
    value: 'America/Blanc-Sablon (UTC -04)',
  },
  {
    label: 'America/Boa_Vista (UTC -04)',
    value: 'America/Boa_Vista (UTC -04)',
  },
  { label: 'America/Bogota (UTC -05)', value: 'America/Bogota (UTC -05)' },
  { label: 'America/Boise (UTC -06)', value: 'America/Boise (UTC -06)' },
  {
    label: 'America/Cambridge_Bay (UTC -06)',
    value: 'America/Cambridge_Bay (UTC -06)',
  },
  {
    label: 'America/Campo_Grande (UTC -04)',
    value: 'America/Campo_Grande (UTC -04)',
  },
  { label: 'America/Cancun (UTC -05)', value: 'America/Cancun (UTC -05)' },
  { label: 'America/Caracas (UTC -04)', value: 'America/Caracas (UTC -04)' },
  { label: 'America/Cayenne (UTC -03)', value: 'America/Cayenne (UTC -03)' },
  { label: 'America/Cayman (UTC -05)', value: 'America/Cayman (UTC -05)' },
  { label: 'America/Chicago (UTC -05)', value: 'America/Chicago (UTC -05)' },
  {
    label: 'America/Chihuahua (UTC -06)',
    value: 'America/Chihuahua (UTC -06)',
  },
  {
    label: 'America/Ciudad_Juarez (UTC -06)',
    value: 'America/Ciudad_Juarez (UTC -06)',
  },
  {
    label: 'America/Costa_Rica (UTC -06)',
    value: 'America/Costa_Rica (UTC -06)',
  },
  { label: 'America/Creston (UTC -07)', value: 'America/Creston (UTC -07)' },
  { label: 'America/Cuiaba (UTC -04)', value: 'America/Cuiaba (UTC -04)' },
  { label: 'America/Curacao (UTC -04)', value: 'America/Curacao (UTC -04)' },
  { label: 'America/Danmarkshavn (UTC)', value: 'America/Danmarkshavn (UTC)' },
  { label: 'America/Dawson (UTC -07)', value: 'America/Dawson (UTC -07)' },
  {
    label: 'America/Dawson_Creek (UTC -07)',
    value: 'America/Dawson_Creek (UTC -07)',
  },
  { label: 'America/Denver (UTC -06)', value: 'America/Denver (UTC -06)' },
  { label: 'America/Detroit (UTC -04)', value: 'America/Detroit (UTC -04)' },
  { label: 'America/Dominica (UTC -04)', value: 'America/Dominica (UTC -04)' },
  { label: 'America/Edmonton (UTC -06)', value: 'America/Edmonton (UTC -06)' },
  { label: 'America/Eirunepe (UTC -05)', value: 'America/Eirunepe (UTC -05)' },
  {
    label: 'America/El_Salvador (UTC -06)',
    value: 'America/El_Salvador (UTC -06)',
  },
  {
    label: 'America/Fort_Nelson (UTC -07)',
    value: 'America/Fort_Nelson (UTC -07)',
  },
  {
    label: 'America/Fortaleza (UTC -03)',
    value: 'America/Fortaleza (UTC -03)',
  },
  {
    label: 'America/Glace_Bay (UTC -03)',
    value: 'America/Glace_Bay (UTC -03)',
  },
  {
    label: 'America/Goose_Bay (UTC -03)',
    value: 'America/Goose_Bay (UTC -03)',
  },
  {
    label: 'America/Grand_Turk (UTC -04)',
    value: 'America/Grand_Turk (UTC -04)',
  },
  { label: 'America/Grenada (UTC -04)', value: 'America/Grenada (UTC -04)' },
  {
    label: 'America/Guadeloupe (UTC -04)',
    value: 'America/Guadeloupe (UTC -04)',
  },
  {
    label: 'America/Guatemala (UTC -06)',
    value: 'America/Guatemala (UTC -06)',
  },
  {
    label: 'America/Guayaquil (UTC -05)',
    value: 'America/Guayaquil (UTC -05)',
  },
  { label: 'America/Guyana (UTC -04)', value: 'America/Guyana (UTC -04)' },
  { label: 'America/Halifax (UTC -03)', value: 'America/Halifax (UTC -03)' },
  { label: 'America/Havana (UTC -04)', value: 'America/Havana (UTC -04)' },
  {
    label: 'America/Hermosillo (UTC -07)',
    value: 'America/Hermosillo (UTC -07)',
  },
  {
    label: 'America/Indiana/Indianapolis (UTC -04)',
    value: 'America/Indiana/Indianapolis (UTC -04)',
  },
  {
    label: 'America/Indiana/Knox (UTC -05)',
    value: 'America/Indiana/Knox (UTC -05)',
  },
  {
    label: 'America/Indiana/Marengo (UTC -04)',
    value: 'America/Indiana/Marengo (UTC -04)',
  },
  {
    label: 'America/Indiana/Petersburg (UTC -04)',
    value: 'America/Indiana/Petersburg (UTC -04)',
  },
  {
    label: 'America/Indiana/Tell_City (UTC -05)',
    value: 'America/Indiana/Tell_City (UTC -05)',
  },
  {
    label: 'America/Indiana/Vevay (UTC -04)',
    value: 'America/Indiana/Vevay (UTC -04)',
  },
  {
    label: 'America/Indiana/Vincennes (UTC -04)',
    value: 'America/Indiana/Vincennes (UTC -04)',
  },
  {
    label: 'America/Indiana/Winamac (UTC -04)',
    value: 'America/Indiana/Winamac (UTC -04)',
  },
  { label: 'America/Inuvik (UTC -06)', value: 'America/Inuvik (UTC -06)' },
  { label: 'America/Iqaluit (UTC -04)', value: 'America/Iqaluit (UTC -04)' },
  { label: 'America/Jamaica (UTC -05)', value: 'America/Jamaica (UTC -05)' },
  { label: 'America/Juneau (UTC -08)', value: 'America/Juneau (UTC -08)' },
  {
    label: 'America/Kentucky/Louisville (UTC -04)',
    value: 'America/Kentucky/Louisville (UTC -04)',
  },
  {
    label: 'America/Kentucky/Monticello (UTC -04)',
    value: 'America/Kentucky/Monticello (UTC -04)',
  },
  {
    label: 'America/Kralendijk (UTC -04)',
    value: 'America/Kralendijk (UTC -04)',
  },
  { label: 'America/La_Paz (UTC -04)', value: 'America/La_Paz (UTC -04)' },
  { label: 'America/Lima (UTC -05)', value: 'America/Lima (UTC -05)' },
  {
    label: 'America/Los_Angeles (UTC -07)',
    value: 'America/Los_Angeles (UTC -07)',
  },
  {
    label: 'America/Lower_Princes (UTC -04)',
    value: 'America/Lower_Princes (UTC -04)',
  },
  { label: 'America/Maceio (UTC -03)', value: 'America/Maceio (UTC -03)' },
  { label: 'America/Managua (UTC -06)', value: 'America/Managua (UTC -06)' },
  { label: 'America/Manaus (UTC -04)', value: 'America/Manaus (UTC -04)' },
  { label: 'America/Marigot (UTC -04)', value: 'America/Marigot (UTC -04)' },
  {
    label: 'America/Martinique (UTC -04)',
    value: 'America/Martinique (UTC -04)',
  },
  {
    label: 'America/Matamoros (UTC -05)',
    value: 'America/Matamoros (UTC -05)',
  },
  { label: 'America/Mazatlan (UTC -07)', value: 'America/Mazatlan (UTC -07)' },
  {
    label: 'America/Menominee (UTC -05)',
    value: 'America/Menominee (UTC -05)',
  },
  { label: 'America/Merida (UTC -06)', value: 'America/Merida (UTC -06)' },
  {
    label: 'America/Metlakatla (UTC -08)',
    value: 'America/Metlakatla (UTC -08)',
  },
  {
    label: 'America/Mexico_City (UTC -06)',
    value: 'America/Mexico_City (UTC -06)',
  },
  { label: 'America/Miquelon (UTC -02)', value: 'America/Miquelon (UTC -02)' },
  { label: 'America/Moncton (UTC -03)', value: 'America/Moncton (UTC -03)' },
  {
    label: 'America/Monterrey (UTC -06)',
    value: 'America/Monterrey (UTC -06)',
  },
  {
    label: 'America/Montevideo (UTC -03)',
    value: 'America/Montevideo (UTC -03)',
  },
  {
    label: 'America/Montserrat (UTC -04)',
    value: 'America/Montserrat (UTC -04)',
  },
  { label: 'America/Nassau (UTC -04)', value: 'America/Nassau (UTC -04)' },
  { label: 'America/New_York (UTC -04)', value: 'America/New_York (UTC -04)' },
  { label: 'America/Nome (UTC -08)', value: 'America/Nome (UTC -08)' },
  { label: 'America/Noronha (UTC -02)', value: 'America/Noronha (UTC -02)' },
  {
    label: 'America/North_Dakota/Beulah (UTC -05)',
    value: 'America/North_Dakota/Beulah (UTC -05)',
  },
  {
    label: 'America/North_Dakota/Center (UTC -05)',
    value: 'America/North_Dakota/Center (UTC -05)',
  },
  {
    label: 'America/North_Dakota/New_Salem (UTC -05)',
    value: 'America/North_Dakota/New_Salem (UTC -05)',
  },
  { label: 'America/Nuuk (UTC -02)', value: 'America/Nuuk (UTC -02)' },
  { label: 'America/Ojinaga (UTC -05)', value: 'America/Ojinaga (UTC -05)' },
  { label: 'America/Panama (UTC -05)', value: 'America/Panama (UTC -05)' },
  {
    label: 'America/Paramaribo (UTC -03)',
    value: 'America/Paramaribo (UTC -03)',
  },
  { label: 'America/Phoenix (UTC -07)', value: 'America/Phoenix (UTC -07)' },
  {
    label: 'America/Port_of_Spain (UTC -04)',
    value: 'America/Port_of_Spain (UTC -04)',
  },
  {
    label: 'America/Port-au-Prince (UTC -04)',
    value: 'America/Port-au-Prince (UTC -04)',
  },
  {
    label: 'America/Porto_Velho (UTC -04)',
    value: 'America/Porto_Velho (UTC -04)',
  },
  {
    label: 'America/Puerto_Rico (UTC -04)',
    value: 'America/Puerto_Rico (UTC -04)',
  },
  {
    label: 'America/Punta_Arenas (UTC -03)',
    value: 'America/Punta_Arenas (UTC -03)',
  },
  {
    label: 'America/Rankin_Inlet (UTC -05)',
    value: 'America/Rankin_Inlet (UTC -05)',
  },
  { label: 'America/Recife (UTC -03)', value: 'America/Recife (UTC -03)' },
  { label: 'America/Regina (UTC -06)', value: 'America/Regina (UTC -06)' },
  { label: 'America/Resolute (UTC -05)', value: 'America/Resolute (UTC -05)' },
  {
    label: 'America/Rio_Branco (UTC -05)',
    value: 'America/Rio_Branco (UTC -05)',
  },
  { label: 'America/Santarem (UTC -03)', value: 'America/Santarem (UTC -03)' },
  { label: 'America/Santiago (UTC -04)', value: 'America/Santiago (UTC -04)' },
  {
    label: 'America/Santo_Domingo (UTC -04)',
    value: 'America/Santo_Domingo (UTC -04)',
  },
  {
    label: 'America/Sao_Paulo (UTC -03)',
    value: 'America/Sao_Paulo (UTC -03)',
  },
  { label: 'America/Scoresbysund (UTC)', value: 'America/Scoresbysund (UTC)' },
  { label: 'America/Sitka (UTC -08)', value: 'America/Sitka (UTC -08)' },
  {
    label: 'America/St_Barthelemy (UTC -04)',
    value: 'America/St_Barthelemy (UTC -04)',
  },
  {
    label: 'America/St_Johns (UTC -02:30)',
    value: 'America/St_Johns (UTC -02:30)',
  },
  { label: 'America/St_Kitts (UTC -04)', value: 'America/St_Kitts (UTC -04)' },
  { label: 'America/St_Lucia (UTC -04)', value: 'America/St_Lucia (UTC -04)' },
  {
    label: 'America/St_Thomas (UTC -04)',
    value: 'America/St_Thomas (UTC -04)',
  },
  {
    label: 'America/St_Vincent (UTC -04)',
    value: 'America/St_Vincent (UTC -04)',
  },
  {
    label: 'America/Swift_Current (UTC -06)',
    value: 'America/Swift_Current (UTC -06)',
  },
  {
    label: 'America/Tegucigalpa (UTC -06)',
    value: 'America/Tegucigalpa (UTC -06)',
  },
  { label: 'America/Thule (UTC -03)', value: 'America/Thule (UTC -03)' },
  { label: 'America/Tijuana (UTC -07)', value: 'America/Tijuana (UTC -07)' },
  { label: 'America/Toronto (UTC -04)', value: 'America/Toronto (UTC -04)' },
  { label: 'America/Tortola (UTC -04)', value: 'America/Tortola (UTC -04)' },
  {
    label: 'America/Vancouver (UTC -07)',
    value: 'America/Vancouver (UTC -07)',
  },
  {
    label: 'America/Whitehorse (UTC -07)',
    value: 'America/Whitehorse (UTC -07)',
  },
  { label: 'America/Winnipeg (UTC -05)', value: 'America/Winnipeg (UTC -05)' },
  { label: 'America/Yakutat (UTC -08)', value: 'America/Yakutat (UTC -08)' },
  { label: 'Antarctica/Casey (UTC +11)', value: 'Antarctica/Casey (UTC +11)' },
  { label: 'Antarctica/Davis (UTC +7)', value: 'Antarctica/Davis (UTC +7)' },
  {
    label: 'Antarctica/DumontDUrville (UTC +10)',
    value: 'Antarctica/DumontDUrville (UTC +10)',
  },
  {
    label: 'Antarctica/Macquarie (UTC +10)',
    value: 'Antarctica/Macquarie (UTC +10)',
  },
  { label: 'Antarctica/Mawson (UTC +5)', value: 'Antarctica/Mawson (UTC +5)' },
  {
    label: 'Antarctica/McMurdo (UTC +12)',
    value: 'Antarctica/McMurdo (UTC +12)',
  },
  {
    label: 'Antarctica/Palmer (UTC -03)',
    value: 'Antarctica/Palmer (UTC -03)',
  },
  {
    label: 'Antarctica/Rothera (UTC -03)',
    value: 'Antarctica/Rothera (UTC -03)',
  },
  { label: 'Antarctica/Syowa (UTC +3)', value: 'Antarctica/Syowa (UTC +3)' },
  { label: 'Antarctica/Troll (UTC +2)', value: 'Antarctica/Troll (UTC +2)' },
  { label: 'Antarctica/Vostok (UTC +6)', value: 'Antarctica/Vostok (UTC +6)' },
  {
    label: 'Arctic/Longyearbyen (UTC +2)',
    value: 'Arctic/Longyearbyen (UTC +2)',
  },
  { label: 'Asia/Aden (UTC +3)', value: 'Asia/Aden (UTC +3)' },
  { label: 'Asia/Almaty (UTC +6)', value: 'Asia/Almaty (UTC +6)' },
  { label: 'Asia/Amman (UTC +3)', value: 'Asia/Amman (UTC +3)' },
  { label: 'Asia/Anadyr (UTC +12)', value: 'Asia/Anadyr (UTC +12)' },
  { label: 'Asia/Aqtau (UTC +5)', value: 'Asia/Aqtau (UTC +5)' },
  { label: 'Asia/Aqtobe (UTC +5)', value: 'Asia/Aqtobe (UTC +5)' },
  { label: 'Asia/Ashgabat (UTC +5)', value: 'Asia/Ashgabat (UTC +5)' },
  { label: 'Asia/Atyrau (UTC +5)', value: 'Asia/Atyrau (UTC +5)' },
  { label: 'Asia/Baghdad (UTC +3)', value: 'Asia/Baghdad (UTC +3)' },
  { label: 'Asia/Bahrain (UTC +3)', value: 'Asia/Bahrain (UTC +3)' },
  { label: 'Asia/Baku (UTC +4)', value: 'Asia/Baku (UTC +4)' },
  { label: 'Asia/Bangkok (UTC +7)', value: 'Asia/Bangkok (UTC +7)' },
  { label: 'Asia/Barnaul (UTC +7)', value: 'Asia/Barnaul (UTC +7)' },
  { label: 'Asia/Beirut (UTC +3)', value: 'Asia/Beirut (UTC +3)' },
  { label: 'Asia/Bishkek (UTC +6)', value: 'Asia/Bishkek (UTC +6)' },
  { label: 'Asia/Brunei (UTC +8)', value: 'Asia/Brunei (UTC +8)' },
  { label: 'Asia/Chita (UTC +9)', value: 'Asia/Chita (UTC +9)' },
  { label: 'Asia/Choibalsan (UTC +8)', value: 'Asia/Choibalsan (UTC +8)' },
  { label: 'Asia/Colombo (UTC +5:30)', value: 'Asia/Colombo (UTC +5:30)' },
  { label: 'Asia/Damascus (UTC +3)', value: 'Asia/Damascus (UTC +3)' },
  { label: 'Asia/Dhaka (UTC +6)', value: 'Asia/Dhaka (UTC +6)' },
  { label: 'Asia/Dili (UTC +9)', value: 'Asia/Dili (UTC +9)' },
  { label: 'Asia/Dubai (UTC +4)', value: 'Asia/Dubai (UTC +4)' },
  { label: 'Asia/Dushanbe (UTC +5)', value: 'Asia/Dushanbe (UTC +5)' },
  { label: 'Asia/Famagusta (UTC +3)', value: 'Asia/Famagusta (UTC +3)' },
  { label: 'Asia/Gaza (UTC +3)', value: 'Asia/Gaza (UTC +3)' },
  { label: 'Asia/Hebron (UTC +3)', value: 'Asia/Hebron (UTC +3)' },
  { label: 'Asia/Ho_Chi_Minh (UTC +7)', value: 'Asia/Ho_Chi_Minh (UTC +7)' },
  { label: 'Asia/Hong_Kong (UTC +8)', value: 'Asia/Hong_Kong (UTC +8)' },
  { label: 'Asia/Hovd (UTC +7)', value: 'Asia/Hovd (UTC +7)' },
  { label: 'Asia/Irkutsk (UTC +8)', value: 'Asia/Irkutsk (UTC +8)' },
  { label: 'Asia/Jakarta (UTC +7)', value: 'Asia/Jakarta (UTC +7)' },
  { label: 'Asia/Jayapura (UTC +9)', value: 'Asia/Jayapura (UTC +9)' },
  { label: 'Asia/Jerusalem (UTC +3)', value: 'Asia/Jerusalem (UTC +3)' },
  { label: 'Asia/Kabul (UTC +4:30)', value: 'Asia/Kabul (UTC +4:30)' },
  { label: 'Asia/Kamchatka (UTC +12)', value: 'Asia/Kamchatka (UTC +12)' },
  { label: 'Asia/Karachi (UTC +5)', value: 'Asia/Karachi (UTC +5)' },
  { label: 'Asia/Kathmandu (UTC +5:45)', value: 'Asia/Kathmandu (UTC +5:45)' },
  { label: 'Asia/Khandyga (UTC +9)', value: 'Asia/Khandyga (UTC +9)' },
  { label: 'Asia/Kolkata (UTC +5:30)', value: 'Asia/Kolkata (UTC +5:30)' },
  { label: 'Asia/Krasnoyarsk (UTC +7)', value: 'Asia/Krasnoyarsk (UTC +7)' },
  { label: 'Asia/Kuala_Lumpur (UTC +8)', value: 'Asia/Kuala_Lumpur (UTC +8)' },
  { label: 'Asia/Kuching (UTC +8)', value: 'Asia/Kuching (UTC +8)' },
  { label: 'Asia/Kuwait (UTC +3)', value: 'Asia/Kuwait (UTC +3)' },
  { label: 'Asia/Macau (UTC +8)', value: 'Asia/Macau (UTC +8)' },
  { label: 'Asia/Magadan (UTC +11)', value: 'Asia/Magadan (UTC +11)' },
  { label: 'Asia/Makassar (UTC +8)', value: 'Asia/Makassar (UTC +8)' },
  { label: 'Asia/Manila (UTC +8)', value: 'Asia/Manila (UTC +8)' },
  { label: 'Asia/Muscat (UTC +4)', value: 'Asia/Muscat (UTC +4)' },
  { label: 'Asia/Nicosia (UTC +3)', value: 'Asia/Nicosia (UTC +3)' },
  { label: 'Asia/Novokuznetsk (UTC +7)', value: 'Asia/Novokuznetsk (UTC +7)' },
  { label: 'Asia/Novosibirsk (UTC +7)', value: 'Asia/Novosibirsk (UTC +7)' },
  { label: 'Asia/Omsk (UTC +6)', value: 'Asia/Omsk (UTC +6)' },
  { label: 'Asia/Oral (UTC +5)', value: 'Asia/Oral (UTC +5)' },
  { label: 'Asia/Phnom_Penh (UTC +7)', value: 'Asia/Phnom_Penh (UTC +7)' },
  { label: 'Asia/Pontianak (UTC +7)', value: 'Asia/Pontianak (UTC +7)' },
  { label: 'Asia/Pyongyang (UTC +9)', value: 'Asia/Pyongyang (UTC +9)' },
  { label: 'Asia/Qatar (UTC +3)', value: 'Asia/Qatar (UTC +3)' },
  { label: 'Asia/Qostanay (UTC +6)', value: 'Asia/Qostanay (UTC +6)' },
  { label: 'Asia/Qyzylorda (UTC +5)', value: 'Asia/Qyzylorda (UTC +5)' },
  { label: 'Asia/Riyadh (UTC +3)', value: 'Asia/Riyadh (UTC +3)' },
  { label: 'Asia/Sakhalin (UTC +11)', value: 'Asia/Sakhalin (UTC +11)' },
  { label: 'Asia/Samarkand (UTC +5)', value: 'Asia/Samarkand (UTC +5)' },
  { label: 'Asia/Seoul (UTC +9)', value: 'Asia/Seoul (UTC +9)' },
  { label: 'Asia/Shanghai (UTC +8)', value: 'Asia/Shanghai (UTC +8)' },
  { label: 'Asia/Singapore (UTC +8)', value: 'Asia/Singapore (UTC +8)' },
  {
    label: 'Asia/Srednekolymsk (UTC +11)',
    value: 'Asia/Srednekolymsk (UTC +11)',
  },
  { label: 'Asia/Taipei (UTC +8)', value: 'Asia/Taipei (UTC +8)' },
  { label: 'Asia/Tashkent (UTC +5)', value: 'Asia/Tashkent (UTC +5)' },
  { label: 'Asia/Tbilisi (UTC +4)', value: 'Asia/Tbilisi (UTC +4)' },
  { label: 'Asia/Tehran (UTC +3:30)', value: 'Asia/Tehran (UTC +3:30)' },
  { label: 'Asia/Thimphu (UTC +6)', value: 'Asia/Thimphu (UTC +6)' },
  { label: 'Asia/Tokyo (UTC +9)', value: 'Asia/Tokyo (UTC +9)' },
  { label: 'Asia/Tomsk (UTC +7)', value: 'Asia/Tomsk (UTC +7)' },
  { label: 'Asia/Ulaanbaatar (UTC +8)', value: 'Asia/Ulaanbaatar (UTC +8)' },
  { label: 'Asia/Urumqi (UTC +6)', value: 'Asia/Urumqi (UTC +6)' },
  { label: 'Asia/Ust-Nera (UTC +10)', value: 'Asia/Ust-Nera (UTC +10)' },
  { label: 'Asia/Vientiane (UTC +7)', value: 'Asia/Vientiane (UTC +7)' },
  { label: 'Asia/Vladivostok (UTC +10)', value: 'Asia/Vladivostok (UTC +10)' },
  { label: 'Asia/Yakutsk (UTC +9)', value: 'Asia/Yakutsk (UTC +9)' },
  { label: 'Asia/Yangon (UTC +6:30)', value: 'Asia/Yangon (UTC +6:30)' },
  {
    label: 'Asia/Yekaterinburg (UTC +5)',
    value: 'Asia/Yekaterinburg (UTC +5)',
  },
  { label: 'Asia/Yerevan (UTC +4)', value: 'Asia/Yerevan (UTC +4)' },
  { label: 'Atlantic/Azores (UTC)', value: 'Atlantic/Azores (UTC)' },
  { label: 'Atlantic/Bermuda (UTC -03)', value: 'Atlantic/Bermuda (UTC -03)' },
  { label: 'Atlantic/Canary (UTC +1)', value: 'Atlantic/Canary (UTC +1)' },
  {
    label: 'Atlantic/Cape_Verde (UTC -01)',
    value: 'Atlantic/Cape_Verde (UTC -01)',
  },
  { label: 'Atlantic/Faroe (UTC +1)', value: 'Atlantic/Faroe (UTC +1)' },
  { label: 'Atlantic/Madeira (UTC +1)', value: 'Atlantic/Madeira (UTC +1)' },
  { label: 'Atlantic/Reykjavik (UTC)', value: 'Atlantic/Reykjavik (UTC)' },
  {
    label: 'Atlantic/South_Georgia (UTC -02)',
    value: 'Atlantic/South_Georgia (UTC -02)',
  },
  { label: 'Atlantic/St_Helena (UTC)', value: 'Atlantic/St_Helena (UTC)' },
  { label: 'Atlantic/Stanley (UTC -03)', value: 'Atlantic/Stanley (UTC -03)' },
  {
    label: 'Australia/Adelaide (UTC +9:30)',
    value: 'Australia/Adelaide (UTC +9:30)',
  },
  {
    label: 'Australia/Brisbane (UTC +10)',
    value: 'Australia/Brisbane (UTC +10)',
  },
  {
    label: 'Australia/Broken_Hill (UTC +9:30)',
    value: 'Australia/Broken_Hill (UTC +9:30)',
  },
  {
    label: 'Australia/Darwin (UTC +9:30)',
    value: 'Australia/Darwin (UTC +9:30)',
  },
  {
    label: 'Australia/Eucla (UTC +8:45)',
    value: 'Australia/Eucla (UTC +8:45)',
  },
  { label: 'Australia/Hobart (UTC +10)', value: 'Australia/Hobart (UTC +10)' },
  {
    label: 'Australia/Lindeman (UTC +10)',
    value: 'Australia/Lindeman (UTC +10)',
  },
  {
    label: 'Australia/Lord_Howe (UTC +10:30)',
    value: 'Australia/Lord_Howe (UTC +10:30)',
  },
  {
    label: 'Australia/Melbourne (UTC +10)',
    value: 'Australia/Melbourne (UTC +10)',
  },
  { label: 'Australia/Perth (UTC +8)', value: 'Australia/Perth (UTC +8)' },
  { label: 'Australia/Sydney (UTC +10)', value: 'Australia/Sydney (UTC +10)' },
  { label: 'Europe/Amsterdam (UTC +2)', value: 'Europe/Amsterdam (UTC +2)' },
  { label: 'Europe/Andorra (UTC +2)', value: 'Europe/Andorra (UTC +2)' },
  { label: 'Europe/Astrakhan (UTC +4)', value: 'Europe/Astrakhan (UTC +4)' },
  { label: 'Europe/Athens (UTC +3)', value: 'Europe/Athens (UTC +3)' },
  { label: 'Europe/Belgrade (UTC +2)', value: 'Europe/Belgrade (UTC +2)' },
  { label: 'Europe/Berlin (UTC +2)', value: 'Europe/Berlin (UTC +2)' },
  { label: 'Europe/Bratislava (UTC +2)', value: 'Europe/Bratislava (UTC +2)' },
  { label: 'Europe/Brussels (UTC +2)', value: 'Europe/Brussels (UTC +2)' },
  { label: 'Europe/Bucharest (UTC +3)', value: 'Europe/Bucharest (UTC +3)' },
  { label: 'Europe/Budapest (UTC +2)', value: 'Europe/Budapest (UTC +2)' },
  { label: 'Europe/Busingen (UTC +2)', value: 'Europe/Busingen (UTC +2)' },
  { label: 'Europe/Chisinau (UTC +3)', value: 'Europe/Chisinau (UTC +3)' },
  { label: 'Europe/Copenhagen (UTC +2)', value: 'Europe/Copenhagen (UTC +2)' },
  { label: 'Europe/Dublin (UTC +1)', value: 'Europe/Dublin (UTC +1)' },
  { label: 'Europe/Gibraltar (UTC +2)', value: 'Europe/Gibraltar (UTC +2)' },
  { label: 'Europe/Guernsey (UTC +1)', value: 'Europe/Guernsey (UTC +1)' },
  { label: 'Europe/Helsinki (UTC +3)', value: 'Europe/Helsinki (UTC +3)' },
  {
    label: 'Europe/Isle_of_Man (UTC +1)',
    value: 'Europe/Isle_of_Man (UTC +1)',
  },
  { label: 'Europe/Istanbul (UTC +3)', value: 'Europe/Istanbul (UTC +3)' },
  { label: 'Europe/Jersey (UTC +1)', value: 'Europe/Jersey (UTC +1)' },
  {
    label: 'Europe/Kaliningrad (UTC +2)',
    value: 'Europe/Kaliningrad (UTC +2)',
  },
  { label: 'Europe/Kirov (UTC +3)', value: 'Europe/Kirov (UTC +3)' },
  { label: 'Europe/Kyiv (UTC +3)', value: 'Europe/Kyiv (UTC +3)' },
  { label: 'Europe/Lisbon (UTC +1)', value: 'Europe/Lisbon (UTC +1)' },
  { label: 'Europe/Ljubljana (UTC +2)', value: 'Europe/Ljubljana (UTC +2)' },
  { label: 'Europe/London (UTC +1)', value: 'Europe/London (UTC +1)' },
  { label: 'Europe/Luxembourg (UTC +2)', value: 'Europe/Luxembourg (UTC +2)' },
  { label: 'Europe/Madrid (UTC +2)', value: 'Europe/Madrid (UTC +2)' },
  { label: 'Europe/Malta (UTC +2)', value: 'Europe/Malta (UTC +2)' },
  { label: 'Europe/Mariehamn (UTC +3)', value: 'Europe/Mariehamn (UTC +3)' },
  { label: 'Europe/Minsk (UTC +3)', value: 'Europe/Minsk (UTC +3)' },
  { label: 'Europe/Monaco (UTC +2)', value: 'Europe/Monaco (UTC +2)' },
  { label: 'Europe/Moscow (UTC +3)', value: 'Europe/Moscow (UTC +3)' },
  { label: 'Europe/Oslo (UTC +2)', value: 'Europe/Oslo (UTC +2)' },
  { label: 'Europe/Paris (UTC +2)', value: 'Europe/Paris (UTC +2)' },
  { label: 'Europe/Podgorica (UTC +2)', value: 'Europe/Podgorica (UTC +2)' },
  { label: 'Europe/Prague (UTC +2)', value: 'Europe/Prague (UTC +2)' },
  { label: 'Europe/Riga (UTC +3)', value: 'Europe/Riga (UTC +3)' },
  { label: 'Europe/Rome (UTC +2)', value: 'Europe/Rome (UTC +2)' },
  { label: 'Europe/Samara (UTC +4)', value: 'Europe/Samara (UTC +4)' },
  { label: 'Europe/San_Marino (UTC +2)', value: 'Europe/San_Marino (UTC +2)' },
  { label: 'Europe/Sarajevo (UTC +2)', value: 'Europe/Sarajevo (UTC +2)' },
  { label: 'Europe/Saratov (UTC +4)', value: 'Europe/Saratov (UTC +4)' },
  { label: 'Europe/Simferopol (UTC +3)', value: 'Europe/Simferopol (UTC +3)' },
  { label: 'Europe/Skopje (UTC +2)', value: 'Europe/Skopje (UTC +2)' },
  { label: 'Europe/Sofia (UTC +3)', value: 'Europe/Sofia (UTC +3)' },
  { label: 'Europe/Stockholm (UTC +2)', value: 'Europe/Stockholm (UTC +2)' },
  { label: 'Europe/Tallinn (UTC +3)', value: 'Europe/Tallinn (UTC +3)' },
  { label: 'Europe/Tirane (UTC +2)', value: 'Europe/Tirane (UTC +2)' },
  { label: 'Europe/Ulyanovsk (UTC +4)', value: 'Europe/Ulyanovsk (UTC +4)' },
  { label: 'Europe/Vaduz (UTC +2)', value: 'Europe/Vaduz (UTC +2)' },
  { label: 'Europe/Vatican (UTC +2)', value: 'Europe/Vatican (UTC +2)' },
  { label: 'Europe/Vienna (UTC +2)', value: 'Europe/Vienna (UTC +2)' },
  { label: 'Europe/Vilnius (UTC +3)', value: 'Europe/Vilnius (UTC +3)' },
  { label: 'Europe/Volgograd (UTC +3)', value: 'Europe/Volgograd (UTC +3)' },
  { label: 'Europe/Warsaw (UTC +2)', value: 'Europe/Warsaw (UTC +2)' },
  { label: 'Europe/Zagreb (UTC +2)', value: 'Europe/Zagreb (UTC +2)' },
  { label: 'Europe/Zurich (UTC +2)', value: 'Europe/Zurich (UTC +2)' },
  {
    label: 'Indian/Antananarivo (UTC +3)',
    value: 'Indian/Antananarivo (UTC +3)',
  },
  { label: 'Indian/Chagos (UTC +6)', value: 'Indian/Chagos (UTC +6)' },
  { label: 'Indian/Christmas (UTC +7)', value: 'Indian/Christmas (UTC +7)' },
  { label: 'Indian/Cocos (UTC +6:30)', value: 'Indian/Cocos (UTC +6:30)' },
  { label: 'Indian/Comoro (UTC +3)', value: 'Indian/Comoro (UTC +3)' },
  { label: 'Indian/Kerguelen (UTC +5)', value: 'Indian/Kerguelen (UTC +5)' },
  { label: 'Indian/Mahe (UTC +4)', value: 'Indian/Mahe (UTC +4)' },
  { label: 'Indian/Maldives (UTC +5)', value: 'Indian/Maldives (UTC +5)' },
  { label: 'Indian/Mauritius (UTC +4)', value: 'Indian/Mauritius (UTC +4)' },
  { label: 'Indian/Mayotte (UTC +3)', value: 'Indian/Mayotte (UTC +3)' },
  { label: 'Indian/Reunion (UTC +4)', value: 'Indian/Reunion (UTC +4)' },
  { label: 'Pacific/Apia (UTC +13)', value: 'Pacific/Apia (UTC +13)' },
  { label: 'Pacific/Auckland (UTC +12)', value: 'Pacific/Auckland (UTC +12)' },
  {
    label: 'Pacific/Bougainville (UTC +11)',
    value: 'Pacific/Bougainville (UTC +11)',
  },
  {
    label: 'Pacific/Chatham (UTC +12:45)',
    value: 'Pacific/Chatham (UTC +12:45)',
  },
  { label: 'Pacific/Chuuk (UTC +10)', value: 'Pacific/Chuuk (UTC +10)' },
  { label: 'Pacific/Easter (UTC -06)', value: 'Pacific/Easter (UTC -06)' },
  { label: 'Pacific/Efate (UTC +11)', value: 'Pacific/Efate (UTC +11)' },
  { label: 'Pacific/Fakaofo (UTC +13)', value: 'Pacific/Fakaofo (UTC +13)' },
  { label: 'Pacific/Fiji (UTC +12)', value: 'Pacific/Fiji (UTC +12)' },
  { label: 'Pacific/Funafuti (UTC +12)', value: 'Pacific/Funafuti (UTC +12)' },
  {
    label: 'Pacific/Galapagos (UTC -06)',
    value: 'Pacific/Galapagos (UTC -06)',
  },
  { label: 'Pacific/Gambier (UTC -09)', value: 'Pacific/Gambier (UTC -09)' },
  {
    label: 'Pacific/Guadalcanal (UTC +11)',
    value: 'Pacific/Guadalcanal (UTC +11)',
  },
  { label: 'Pacific/Guam (UTC +10)', value: 'Pacific/Guam (UTC +10)' },
  { label: 'Pacific/Honolulu (UTC -10)', value: 'Pacific/Honolulu (UTC -10)' },
  { label: 'Pacific/Kanton (UTC +13)', value: 'Pacific/Kanton (UTC +13)' },
  {
    label: 'Pacific/Kiritimati (UTC +14)',
    value: 'Pacific/Kiritimati (UTC +14)',
  },
  { label: 'Pacific/Kosrae (UTC +11)', value: 'Pacific/Kosrae (UTC +11)' },
  {
    label: 'Pacific/Kwajalein (UTC +12)',
    value: 'Pacific/Kwajalein (UTC +12)',
  },
  { label: 'Pacific/Majuro (UTC +12)', value: 'Pacific/Majuro (UTC +12)' },
  {
    label: 'Pacific/Marquesas (UTC -09:30)',
    value: 'Pacific/Marquesas (UTC -09:30)',
  },
  { label: 'Pacific/Midway (UTC -11)', value: 'Pacific/Midway (UTC -11)' },
  { label: 'Pacific/Nauru (UTC +12)', value: 'Pacific/Nauru (UTC +12)' },
  { label: 'Pacific/Niue (UTC -11)', value: 'Pacific/Niue (UTC -11)' },
  { label: 'Pacific/Norfolk (UTC +11)', value: 'Pacific/Norfolk (UTC +11)' },
  { label: 'Pacific/Noumea (UTC +11)', value: 'Pacific/Noumea (UTC +11)' },
  {
    label: 'Pacific/Pago_Pago (UTC -11)',
    value: 'Pacific/Pago_Pago (UTC -11)',
  },
  { label: 'Pacific/Palau (UTC +9)', value: 'Pacific/Palau (UTC +9)' },
  { label: 'Pacific/Pitcairn (UTC -08)', value: 'Pacific/Pitcairn (UTC -08)' },
  { label: 'Pacific/Pohnpei (UTC +11)', value: 'Pacific/Pohnpei (UTC +11)' },
  {
    label: 'Pacific/Port_Moresby (UTC +10)',
    value: 'Pacific/Port_Moresby (UTC +10)',
  },
  {
    label: 'Pacific/Rarotonga (UTC -10)',
    value: 'Pacific/Rarotonga (UTC -10)',
  },
  { label: 'Pacific/Saipan (UTC +10)', value: 'Pacific/Saipan (UTC +10)' },
  { label: 'Pacific/Tahiti (UTC -10)', value: 'Pacific/Tahiti (UTC -10)' },
  { label: 'Pacific/Tarawa (UTC +12)', value: 'Pacific/Tarawa (UTC +12)' },
  {
    label: 'Pacific/Tongatapu (UTC +13)',
    value: 'Pacific/Tongatapu (UTC +13)',
  },
  { label: 'Pacific/Wake (UTC +12)', value: 'Pacific/Wake (UTC +12)' },
  { label: 'Pacific/Wallis (UTC +12)', value: 'Pacific/Wallis (UTC +12)' },
];
