// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_model

import (
	"time"
)

type Connection interface {
	IsConnection()
	GetPageInfo() *PageInfo
	GetTotalCount() int
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PaginationInput struct {
	Offset *int `json:"offset,omitempty"`
	Limit  *int `json:"limit,omitempty"`
}

type Query struct {
}

type Webtracker struct {
	ID                string     `json:"id"`
	Domain            string     `json:"domain"`
	CnameHost         string     `json:"cnameHost"`
	CnameTarget       string     `json:"cnameTarget"`
	IsCnameConfigured bool       `json:"isCnameConfigured"`
	IsProxyActive     bool       `json:"isProxyActive"`
	IsArchived        bool       `json:"isArchived"`
	LastEventAt       time.Time  `json:"lastEventAt"`
	CreatedAt         time.Time  `json:"createdAt"`
	UpdatedAt         *time.Time `json:"updatedAt,omitempty"`
}

type WebtrackerSaveInput struct {
	ID        *string `json:"id,omitempty"`
	Domain    string  `json:"domain"`
	CnameHost *string `json:"cnameHost,omitempty"`
}
