package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/customeros/customeros/packages/server/customer-os-api/graphql/generated"
	"github.com/customeros/customeros/packages/server/customer-os-api/graphql/model"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/common"
	commonModel "github.com/customeros/customeros/packages/server/customer-os-common-module/model"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/telemetry"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/utils"
	neo4j_entity "github.com/customeros/customeros/packages/server/customer-os-neo4j-repository/entity"
)

// AddTag is the resolver for the addTag field.
func (r *mutationResolver) AddTag(ctx context.Context, input model.AddTagInput) (string, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "CommonResolver.AddTag", graphql.GetOperationContext(ctx))
	defer spans.Finish()

	spans.LogObjectAsJson("request", input)

	tenant := common.GetTenantFromContext(ctx)

	tagId, err := r.Services.CommonServices.TagService.AddTagToEntity(ctx, nil, tenant, input.EntityID, commonModel.DecodeEntityType(input.EntityType.String()), utils.StringOrEmpty(input.Tag.ID), utils.StringOrEmpty(input.Tag.Name))
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Error adding tag to entity")
		return "", err
	}

	return tagId, nil
}

// RemoveTag is the resolver for the removeTag field.
func (r *mutationResolver) RemoveTag(ctx context.Context, input model.RemoveTagInput) (*model.Result, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "CommonResolver.RemoveTag", graphql.GetOperationContext(ctx))
	defer spans.Finish()
	spans.LogObjectAsJson("request", input)

	tenant := common.GetTenantFromContext(ctx)

	err := r.Services.CommonServices.TagService.RemoveTagFromEntity(ctx, nil, tenant, input.EntityID, commonModel.DecodeEntityType(input.EntityType.String()), input.TagID, "")
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Error removing tag from entity")
		return nil, err
	}

	return &model.Result{Result: true}, nil
}

// RemoveTags is the resolver for the removeTags field.
func (r *mutationResolver) RemoveTags(ctx context.Context, input model.RemoveTagsInput) (*model.Result, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "CommonResolver.RemoveTags", graphql.GetOperationContext(ctx))
	defer spans.Finish()
	spans.TagEntity(input.EntityID)
	spans.LogObjectAsJson("request", input)

	tenant := common.GetTenantFromContext(ctx)

	// get all tags for the entity
	tagEntities, err := r.Services.CommonServices.TagService.GetTagsForEntity(ctx, input.EntityID, commonModel.DecodeEntityType(input.EntityType.String()))
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Error getting tags for entity")
		return nil, err
	}

	if tagEntities == nil {
		return &model.Result{Result: true}, nil
	}

	// for each tag, remove it from the entity
	for _, tagEntity := range *tagEntities {
		err := r.Services.CommonServices.TagService.RemoveTagFromEntity(ctx, nil, tenant, input.EntityID, commonModel.DecodeEntityType(input.EntityType.String()), tagEntity.Id, "")
		if err != nil {
			spans.TraceError(err)
			graphql.AddErrorf(ctx, "Error removing tag from entity")
			return nil, err
		}
	}

	return &model.Result{Result: true}, nil
}

// FlagWrongField is the resolver for the flagWrongField field.
func (r *mutationResolver) FlagWrongField(ctx context.Context, input model.FlagWrongFieldInput) (*model.Result, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "CommonResolver.FlagWrongField", graphql.GetOperationContext(ctx))
	defer spans.Finish()
	spans.LogObjectAsJson("request", input)

	tenant := common.GetTenantFromContext(ctx)

	switch input.Field {
	case model.FlagWrongFieldsOrganizationIndustry:
		err := r.Services.CommonServices.Neo4jRepositories.CommonWriteRepository.UpdateProperties(ctx, nil, tenant, commonModel.NodeLabelOrganization, input.EntityID,
			map[string]interface{}{
				string(neo4j_entity.OrganizationPropertyWrongIndustry):   true,
				string(neo4j_entity.OrganizationPropertyWrongIndustryAt): utils.TimePtrAsAny(utils.TimePtr(utils.Now())),
			})

		if err != nil {
			spans.TraceError(err)
			graphql.AddErrorf(ctx, "Error flagging wrong industry")
			return nil, err
		}

	default:
		return &model.Result{Result: false}, nil
	}

	return &model.Result{Result: true}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
