package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/customeros/customeros/packages/server/customer-os-api/graphql/model"
	"github.com/customeros/customeros/packages/server/customer-os-api/mapper"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/common"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/telemetry"
)

// ExternalSystemCreate is the resolver for the externalSystem_Create field.
func (r *mutationResolver) ExternalSystemCreate(ctx context.Context, input model.ExternalSystemInput) (string, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "MutationResolver.ExternalSystemCreate", graphql.GetOperationContext(ctx))
	defer spans.Finish()

	spans.LogObjectAsJson("request.input", input)

	err := r.Services.CommonServices.ExternalSystemService.MergeExternalSystem(ctx, common.GetTenantFromContext(ctx), input.Name)
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Failed to merge external system")
		return "", err
	}
	return input.Name, nil
}

// ExternalSystemInstances is the resolver for the externalSystemInstances field.
func (r *queryResolver) ExternalSystemInstances(ctx context.Context) ([]*model.ExternalSystemInstance, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "QueryResolver.ExternalSystemInstances", graphql.GetOperationContext(ctx))
	defer spans.Finish()

	externalSystemEntities, err := r.Services.ExternalSystemService.GetAllExternalSystemInstances(ctx)
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Failed to get external system instances")
		return nil, err
	}
	return mapper.MapExternalSystemEntitiesToExternalSystemInstances(externalSystemEntities), nil
}
