package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/customeros/customeros/packages/server/customer-os-api/graphql/model"
	"github.com/customeros/customeros/packages/server/customer-os-api/mapper"
	"github.com/customeros/customeros/packages/server/customer-os-api/tracing"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/common"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/utils"
	postgres_entity "github.com/customeros/customeros/packages/server/customer-os-postgres-repository/entity"
)

// SkuSave is the resolver for the sku_Save field.
func (r *mutationResolver) SkuSave(ctx context.Context, input model.SkuInput) (*model.Sku, error) {
	ctx, span := tracing.StartGraphQLTracerSpan(ctx, "SkuResolver.SkuSave", graphql.GetOperationContext(ctx))
	defer span.Finish()
	tracing.SetDefaultResolverSpanTags(ctx, span)

	tenant := common.GetTenantFromContext(ctx)

	var err error
	var toStore *postgres_entity.SkuEntity

	if input.ID != nil && *input.ID != "" {
		toStore, err = r.Services.CommonServices.PostgresRepositories.SkuRepository.Get(ctx, tenant, *input.ID)
		if err != nil {
			tracing.TraceErr(span, err)
			graphql.AddErrorf(ctx, "Failed to get skus")
			return nil, err
		}

		if toStore == nil {
			err := fmt.Errorf("sku with id %s not found", *input.ID)
			tracing.TraceErr(span, err)
			graphql.AddErrorf(ctx, "Failed to save sku")
			return nil, err
		}
	} else {
		toStore = &postgres_entity.SkuEntity{}
		toStore.Tenant = tenant
		toStore.CreatedAt = utils.Now()
	}

	toStore.Name = input.Name
	toStore.Price = input.Price

	sku, err := r.Services.CommonServices.PostgresRepositories.SkuRepository.Save(ctx, toStore)
	if err != nil {
		tracing.TraceErr(span, err)
		graphql.AddErrorf(ctx, "Failed to get skus")
		return nil, err
	}

	return mapper.MapEntityToSku(sku), nil
}

// SkuDelete is the resolver for the sku_Delete field.
func (r *mutationResolver) SkuDelete(ctx context.Context, id string) (*model.Result, error) {
	ctx, span := tracing.StartGraphQLTracerSpan(ctx, "SkuResolver.SkuDelete", graphql.GetOperationContext(ctx))
	defer span.Finish()
	tracing.SetDefaultResolverSpanTags(ctx, span)

	tenant := common.GetTenantFromContext(ctx)

	sku, err := r.Services.CommonServices.PostgresRepositories.SkuRepository.Get(ctx, tenant, id)
	if err != nil {
		tracing.TraceErr(span, err)
		graphql.AddErrorf(ctx, "Failed to get skus")
		return nil, err
	}

	if sku == nil {
		err := fmt.Errorf("sku with id %s not found", id)
		tracing.TraceErr(span, err)
		graphql.AddErrorf(ctx, "Failed to delete sku")
		return nil, err
	}

	err = r.Services.CommonServices.PostgresRepositories.SkuRepository.Delete(ctx, tenant, id)
	if err != nil {
		tracing.TraceErr(span, err)
		graphql.AddErrorf(ctx, "Failed to delete sku")
		return nil, err
	}

	return &model.Result{Result: true}, nil
}

// Skus is the resolver for the skus field.
func (r *queryResolver) Skus(ctx context.Context) ([]*model.Sku, error) {
	ctx, span := tracing.StartGraphQLTracerSpan(ctx, "SkuResolver.Skus", graphql.GetOperationContext(ctx))
	defer span.Finish()
	tracing.SetDefaultResolverSpanTags(ctx, span)

	tenant := common.GetTenantFromContext(ctx)

	skuEntities, err := r.Services.CommonServices.PostgresRepositories.SkuRepository.GetAll(ctx, tenant)
	if err != nil {
		tracing.TraceErr(span, err)
		graphql.AddErrorf(ctx, "Failed to get skus")
		return nil, err
	}

	return mapper.MapEntitiesToSkus(skuEntities), nil
}
