package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"sync"

	"github.com/99designs/gqlgen/graphql"
	"github.com/customeros/customeros/packages/server/customer-os-api/dataloader"
	"github.com/customeros/customeros/packages/server/customer-os-api/graphql/generated"
	"github.com/customeros/customeros/packages/server/customer-os-api/graphql/model"
	"github.com/customeros/customeros/packages/server/customer-os-api/mapper"
	enummapper "github.com/customeros/customeros/packages/server/customer-os-api/mapper/enum"
	"github.com/customeros/customeros/packages/server/customer-os-api/tracing"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/common"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/data_fields"
	commonmodel "github.com/customeros/customeros/packages/server/customer-os-common-module/model"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/utils"
	"github.com/opentracing/opentracing-go"
)

// TaskSave is the resolver for the task_Save field.
func (r *mutationResolver) TaskSave(ctx context.Context, input model.TaskInput) (*model.Task, error) {
	ctx, span := tracing.StartGraphQLTracerSpan(ctx, "MutationResolver.TaskSave", graphql.GetOperationContext(ctx))
	defer span.Finish()
	tracing.SetDefaultResolverSpanTags(ctx, span)

	dataFields := data_fields.TaskFields{
		Subject:         input.Subject,
		Description:     input.Description,
		DueAt:           input.DueAt,
		OpportunityIds:  &input.OpportunityIds,
		AssigneeUserIds: &input.Assignees,
	}
	if input.Status != nil {
		dataFields.Status = utils.ToPtr(enummapper.MapTaskStatusFromModel(*input.Status))
	}
	taskId, err := r.Services.CommonServices.TaskService.Save(ctx, nil, input.ID, dataFields)
	if err != nil {
		tracing.TraceErr(span, err)
		graphql.AddErrorf(ctx, "Failed to save task")
		return nil, err
	}

	taskEntity, err := r.Services.CommonServices.TaskService.GetById(ctx, taskId)
	if err != nil {
		tracing.TraceErr(span, err)
		graphql.AddErrorf(ctx, "Failed to get task")
		return nil, err
	}

	return mapper.MapEntityToTask(taskEntity), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, ids []string) ([]*model.Task, error) {
	ctx, span := tracing.StartGraphQLTracerSpan(ctx, "QueryResolver.Tasks", graphql.GetOperationContext(ctx))
	defer span.Finish()
	tracing.SetDefaultResolverSpanTags(ctx, span)

	taskEntities, err := r.Services.CommonServices.TaskService.GetAllByIds(ctx, ids)
	if err != nil {
		tracing.TraceErr(span, err)
		graphql.AddErrorf(ctx, "Failed to get tasks")
		return nil, err
	}

	return mapper.MapEntitiesToTasks(taskEntities), nil
}

// TasksSearch is the resolver for the tasks_search field.
func (r *queryResolver) TasksSearch(ctx context.Context, limit *int, where *model.Filter, sort *commonmodel.SortBy) (*model.TaskSearchResult, error) {
	ctx, span := tracing.StartGraphQLTracerSpan(ctx, "QueryResolver.TasksSearch", graphql.GetOperationContext(ctx))
	defer span.Finish()
	tracing.SetDefaultResolverSpanTags(ctx, span)

	tenant := common.GetTenantFromContext(ctx)

	if limit == nil {
		i := 1000
		limit = &i
	}

	var wg sync.WaitGroup
	var firstErr error
	var mu sync.Mutex

	setError := func(err error) {
		mu.Lock()
		defer mu.Unlock()
		if firstErr == nil {
			firstErr = err
		}
	}

	response := &model.TaskSearchResult{}

	// Convert GraphQL Filter to commonmodel Filter
	commonWhere := mapper.MapFilterToCommonModel(where)

	wg.Add(1)
	go func(resp *model.TaskSearchResult) {
		innerSpan, innerCtx := opentracing.StartSpanFromContext(ctx, "QueryResolver.TasksSearch.SearchTasks")
		defer innerSpan.Finish()
		defer wg.Done()
		tracing.SetDefaultResolverSpanTags(innerCtx, span)

		taskSearchResponse, err := r.Services.Repositories.Neo4jRepositories.TaskReadRepository.SearchTasks(innerCtx, tenant, *limit, commonWhere, sort)
		if err != nil {
			tracing.TraceErr(innerSpan, err)
			setError(err)
			return
		}

		resp.TotalElements = taskSearchResponse.Count
		resp.Tasks = taskSearchResponse.Strings
	}(response)

	wg.Add(1)
	go func(resp *model.TaskSearchResult) {
		innerSpan, innerCtx := opentracing.StartSpanFromContext(ctx, "QueryResolver.TasksSearch.TotalAvailable")
		defer innerSpan.Finish()
		defer wg.Done()
		tracing.SetDefaultResolverSpanTags(innerCtx, innerSpan)

		totalAvailable, err := r.Services.Repositories.Neo4jRepositories.TaskReadRepository.CountByTenant(innerCtx, tenant)
		if err != nil {
			tracing.TraceErr(innerSpan, err)
			setError(err)
			return
		}

		resp.TotalAvailable = totalAvailable
	}(response)

	wg.Wait()

	if firstErr != nil {
		tracing.TraceErr(opentracing.SpanFromContext(ctx), firstErr)
		r.log.Errorf("Failed to get tasks: %v", firstErr)
		graphql.AddErrorf(ctx, "Failed to get tasks: %v", firstErr)
		return nil, nil
	}

	return response, nil
}

// Assignees is the resolver for the assignees field.
func (r *taskResolver) Assignees(ctx context.Context, obj *model.Task) ([]string, error) {
	ctx = tracing.EnrichCtxWithSpanCtxForGraphQL(ctx, graphql.GetOperationContext(ctx))

	userEntities, err := dataloader.For(ctx).GetUsersAssigneesForTask(ctx, obj.ID)
	if err != nil {
		tracing.TraceErr(opentracing.SpanFromContext(ctx), err)
		r.log.Errorf("Failed to get users for task %s: %s", obj.ID, err.Error())
		graphql.AddErrorf(ctx, "Failed to get users for task %s", obj.ID)
		return nil, nil
	}
	var output []string
	if userEntities != nil {
		for _, userEntity := range *userEntities {
			output = append(output, userEntity.Id)
		}
	}
	return output, nil
}

// AuthorID is the resolver for the authorId field.
func (r *taskResolver) AuthorID(ctx context.Context, obj *model.Task) (*string, error) {
	ctx = tracing.EnrichCtxWithSpanCtxForGraphQL(ctx, graphql.GetOperationContext(ctx))

	userEntity, err := dataloader.For(ctx).GetUserCreatorForTask(ctx, obj.ID)
	if err != nil {
		tracing.TraceErr(opentracing.SpanFromContext(ctx), err)
		graphql.AddErrorf(ctx, "Failed to get author")
		return nil, nil
	}
	if userEntity == nil {
		return nil, nil
	}
	return utils.StringPtr(userEntity.Id), nil
}

// OpportunityIds is the resolver for the opportunityIds field.
func (r *taskResolver) OpportunityIds(ctx context.Context, obj *model.Task) ([]string, error) {
	ctx = tracing.EnrichCtxWithSpanCtxForGraphQL(ctx, graphql.GetOperationContext(ctx))

	opportunityEntities, err := dataloader.For(ctx).GetOpportunitiesForTask(ctx, obj.ID)
	if err != nil {
		tracing.TraceErr(opentracing.SpanFromContext(ctx), err)
		r.log.Errorf("Failed to get users for task %s: %s", obj.ID, err.Error())
		graphql.AddErrorf(ctx, "Failed to get users for task %s", obj.ID)
		return nil, nil
	}
	var output []string
	if opportunityEntities != nil {
		for _, opportunityEntity := range *opportunityEntities {
			output = append(output, opportunityEntity.Id)
		}
	}
	return output, nil
}

// Task returns generated.TaskResolver implementation.
func (r *Resolver) Task() generated.TaskResolver { return &taskResolver{r} }

type taskResolver struct{ *Resolver }
