package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.71

import (
	"context"
	"errors"

	"github.com/99designs/gqlgen/graphql"
	"github.com/customeros/customeros/packages/server/customer-os-api/constants"
	"github.com/customeros/customeros/packages/server/customer-os-api/graphql/model"
	"github.com/customeros/customeros/packages/server/customer-os-api/mapper"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/common"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/data_fields"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/telemetry"
	"github.com/customeros/customeros/packages/server/customer-os-common-module/utils"
	neo4jentity "github.com/customeros/customeros/packages/server/customer-os-neo4j-repository/entity"
)

// TenantAddBillingProfile is the resolver for the tenant_AddBillingProfile field.
func (r *mutationResolver) TenantAddBillingProfile(ctx context.Context, input model.TenantBillingProfileInput) (*model.TenantBillingProfile, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "MutationResolver.TenantAddBillingProfile", graphql.GetOperationContext(ctx))
	defer spans.Finish()

	spans.LogObjectAsJson("request.input", input)

	dataFields := data_fields.TenantBillingProfileFields{
		Source:                 utils.StringPtr(neo4jentity.DataSourceOpenline.String()),
		AppSource:              utils.StringPtr(constants.AppSourceCustomerOsApi),
		Phone:                  input.Phone,
		LegalName:              input.LegalName,
		AddressLine1:           input.AddressLine1,
		AddressLine2:           input.AddressLine2,
		AddressLine3:           input.AddressLine3,
		Locality:               input.Locality,
		Country:                input.Country,
		Region:                 input.Region,
		Zip:                    input.Zip,
		VatNumber:              utils.StringPtr(input.VatNumber),
		SendInvoicesFrom:       utils.StringPtr(input.SendInvoicesFrom),
		SendInvoicesBcc:        input.SendInvoicesBcc,
		CanPayWithPigeon:       utils.BoolPtr(input.CanPayWithPigeon),
		CanPayWithBankTransfer: utils.BoolPtr(input.CanPayWithBankTransfer),
		Check:                  utils.BoolPtr(input.Check),
	}

	profileId, err := r.Services.CommonServices.TenantSettingsService.CreateTenantBillingProfile(ctx, dataFields)
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Failed to create tenant billing profile")
		return &model.TenantBillingProfile{ID: profileId}, err
	}

	createdTenantBillingProfileEntity, err := r.Services.CommonServices.TenantSettingsService.GetTenantBillingProfile(ctx, profileId)
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Tenant billing profile not yet available.")
		return &model.TenantBillingProfile{ID: profileId}, nil
	}
	spans.LogKV("response.tenantBillingProfileId", profileId)
	return mapper.MapEntityToTenantBillingProfile(createdTenantBillingProfileEntity), nil
}

// TenantUpdateBillingProfile is the resolver for the tenant_UpdateBillingProfile field.
func (r *mutationResolver) TenantUpdateBillingProfile(ctx context.Context, input model.TenantBillingProfileUpdateInput) (*model.TenantBillingProfile, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "MutationResolver.TenantUpdateBillingProfile", graphql.GetOperationContext(ctx))
	defer spans.Finish()

	spans.LogObjectAsJson("request.input", input)

	if input.ID == "" {
		err := errors.New("missing tenant billing profile id")
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Missing tenant billing profile id")
		return nil, nil
	}

	dataFields := data_fields.TenantBillingProfileFields{
		Phone:                  input.Phone,
		LegalName:              input.LegalName,
		AddressLine1:           input.AddressLine1,
		AddressLine2:           input.AddressLine2,
		AddressLine3:           input.AddressLine3,
		Locality:               input.Locality,
		Country:                input.Country,
		Region:                 input.Region,
		Zip:                    input.Zip,
		VatNumber:              input.VatNumber,
		SendInvoicesFrom:       input.SendInvoicesFrom,
		SendInvoicesBcc:        input.SendInvoicesBcc,
		CanPayWithPigeon:       input.CanPayWithPigeon,
		CanPayWithBankTransfer: input.CanPayWithBankTransfer,
		Check:                  input.Check,
	}

	err := r.Services.CommonServices.TenantSettingsService.UpdateTenantBillingProfile(ctx, input.ID, dataFields)
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Failed to update billing profile")
		return nil, err
	}

	updatedTenantBillingProfileEntity, err := r.Services.CommonServices.TenantSettingsService.GetTenantBillingProfile(ctx, input.ID)
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Failed to fetch tenant billing profile details")
		return nil, nil
	}
	return mapper.MapEntityToTenantBillingProfile(updatedTenantBillingProfileEntity), nil
}

// TenantUpdateSettings is the resolver for the tenant_UpdateSettings field.
func (r *mutationResolver) TenantUpdateSettings(ctx context.Context, input *model.TenantSettingsInput) (*model.TenantSettings, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "MutationResolver.TenantUpdateSettings", graphql.GetOperationContext(ctx))
	defer spans.Finish()

	spans.LogObjectAsJson("request.input", input)

	//LogoRepositoryFileId: utils.IfNotNilString(input.LogoRepositoryFileID),
	//		BaseCurrency:         baseCurrency,
	dataFields := data_fields.TenantSettingsFields{
		WorkspaceName:        input.WorkspaceName,
		WorkspaceLogo:        input.WorkspaceLogo,
		LogoRepositoryFileId: input.LogoRepositoryFileID,
	}
	if input.BaseCurrency != nil {
		dataFields.BaseCurrency = utils.StringPtr(input.BaseCurrency.String())
	}

	err := r.Services.CommonServices.TenantSettingsService.UpdateTenantSettings(ctx, dataFields)
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Failed to update tenant settings")
		return nil, err
	}

	updatedTenantSettingsEntity, err := r.Services.CommonServices.TenantSettingsService.GetTenantSettings(ctx)
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Failed to fetch tenant settings")
		return nil, nil
	}
	return mapper.MapEntityToTenantSettings(updatedTenantSettingsEntity), nil
}

// TenantUpdateSettingsOpportunityStage is the resolver for the tenant_UpdateSettingsOpportunityStage field.
func (r *mutationResolver) TenantUpdateSettingsOpportunityStage(ctx context.Context, input model.TenantSettingsOpportunityStageConfigurationInput) (*model.ActionResponse, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "MutationResolver.TenantUpdateSettingsOpportunityStage", graphql.GetOperationContext(ctx))
	defer spans.Finish()

	spans.LogObjectAsJson("request.input", input)

	tenant := common.GetTenantFromContext(ctx)

	updatedEntity, err := r.Services.Repositories.PostgresRepositories.TenantSettingsOpportunityStageRepository.Update(ctx, tenant, input.ID, input.Label, input.LikelihoodRate, input.Visible)
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Failed to update tenant settings opportunity stage")
		return &model.ActionResponse{Accepted: false}, err
	}
	if updatedEntity == nil {
		return &model.ActionResponse{Accepted: false}, nil
	}

	return &model.ActionResponse{Accepted: true}, nil
}

// Tenant is the resolver for the tenant field.
func (r *queryResolver) Tenant(ctx context.Context) (string, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "QueryResolver.Tenant", graphql.GetOperationContext(ctx))
	defer spans.Finish()

	return common.GetTenantFromContext(ctx), nil
}

// TenantBillingProfiles is the resolver for the tenantBillingProfiles field.
func (r *queryResolver) TenantBillingProfiles(ctx context.Context) ([]*model.TenantBillingProfile, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "QueryResolver.TenantBillingProfiles", graphql.GetOperationContext(ctx))
	defer spans.Finish()

	tenantBillingProfileEntities, err := r.Services.CommonServices.TenantSettingsService.GetTenantBillingProfiles(ctx)
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Failed to fetch billing profiles")
		return nil, nil
	}
	return mapper.MapEntitiesToTenantBillingProfiles(tenantBillingProfileEntities), nil
}

// TenantBillingProfile is the resolver for the tenantBillingProfile field.
func (r *queryResolver) TenantBillingProfile(ctx context.Context, id string) (*model.TenantBillingProfile, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "QueryResolver.TenantBillingProfile", graphql.GetOperationContext(ctx))
	defer spans.Finish()

	spans.LogKV("request.tenantBillingProfileId", id)

	tenantBillingProfileEntity, err := r.Services.CommonServices.TenantSettingsService.GetTenantBillingProfile(ctx, id)
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Failed to fetch tenant billing profile details")
		return nil, nil
	}
	return mapper.MapEntityToTenantBillingProfile(tenantBillingProfileEntity), nil
}

// TenantSettings is the resolver for the tenantSettings field.
func (r *queryResolver) TenantSettings(ctx context.Context) (*model.TenantSettings, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "QueryResolver.TenantSettings", graphql.GetOperationContext(ctx))
	defer spans.Finish()

	tenantSettingsEntity, err := r.Services.CommonServices.TenantSettingsService.GetTenantSettings(ctx)
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Failed to fetch tenant settings")
		return nil, nil
	}
	tenantSettings := mapper.MapEntityToTenantSettings(tenantSettingsEntity)

	opportunityStages, err := r.Services.Repositories.PostgresRepositories.TenantSettingsOpportunityStageRepository.GetOrInitialize(ctx, common.GetTenantFromContext(ctx))
	if err != nil {
		spans.TraceError(err)
		graphql.AddErrorf(ctx, "Failed to fetch tenant settings opportunity stages")
		return nil, nil
	}

	tenantSettings.OpportunityStages = mapper.MapEntitiesToTenantSettingsOpportunityStages(opportunityStages)

	return tenantSettings, nil
}
