package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/customeros/customeros/packages/server/customer-os-api/graphql/model"
)

// TestMutation is the resolver for the testMutation field.
func (r *mutationResolver) TestMutation(ctx context.Context, input model.TestInput) (bool, error) {
	panic(fmt.Errorf("not implemented: TestMutation - testMutation"))
}
