package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"github.com/openline-ai/openline-customer-os/packages/server/file-store-api/test/graph/model"
)

// SocialUpdate is the resolver for the social_Update field.
func (r *mutationResolver) SocialUpdate(ctx context.Context, input model.SocialUpdateInput) (*model.Social, error) {
	panic(fmt.Errorf("not implemented: SocialUpdate - social_Update"))
}

// SocialRemove is the resolver for the social_Remove field.
func (r *mutationResolver) SocialRemove(ctx context.Context, socialID string) (*model.Result, error) {
	panic(fmt.Errorf("not implemented: SocialRemove - social_Remove"))
}
