server {
  listen 80;
  server_name localhost;

  proxy_buffers 64 512k;
  proxy_buffer_size 128k;
  large_client_header_buffers 16 32k;

  add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'self';" always;
  add_header X-Frame-Options "DENY" always;
  add_header X-Content-Type-Options "nosniff";

  location ~ /\. {
      deny all;
      return 404;
  }

  location = /BitKeeper {
      deny all;
      return 404;
  }

  location / {
    limit_except GET POST HEAD PUT PATCH DELETE OPTIONS {
      deny all;
    }

    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri /index.html;
  }
}