import { cva } from 'class-variance-authority';
export const iconVariant = cva('', {
  variants: {
    size: {
      xxs: [],
      xs: [],
      sm: [],
      md: [],
      lg: [],
    },
    variant: {
      solid: [],
      outline: [],
      ghost: [],
    },
    colorScheme: {
      primary: [],
      gray: [],
      grayBlue: [],
      grayModern: [],
      grayWarm: [],
      error: [],
      rose: [],
      warning: [],
      yellow: [],
      blueDark: [],
      teal: [],
      success: [],
      blue: [],
      moss: [],
      greenLight: [],
      violet: [],
      fuchsia: [],
      orangeDark: [],
      purple: [],
      cyan: [],
    },
  },
  compoundVariants: [
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'grayBlue',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'grayModern',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'grayWarm',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'yellow',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'blue',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'orangeDark',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'purple',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'cyan',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-3 h-3', 'text-primary-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-3 h-3', 'text-gray-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'grayBlue',
      className: ['w-3 h-3', 'text-grayBlue-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'grayModern',
      className: ['w-3 h-3', 'text-grayModern-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'grayWarm',
      className: ['w-3 h-3', 'text-grayWarm-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-3 h-3', 'text-error-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-3 h-3', 'text-rose-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-3 h-3', 'text-warning-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'yellow',
      className: ['w-3 h-3', 'text-yellow-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-3 h-3', 'text-blueDark-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-3 h-3', 'text-teal-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-3 h-3', 'text-success-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'blue',
      className: ['w-3 h-3', 'text-blue-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-3 h-3', 'text-moss-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-3 h-3', 'text-greenLight-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-3 h-3', 'text-violet-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-3 h-3', 'text-fuchsia-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'orangeDark',
      className: ['w-3 h-3', 'text-orangeDark-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'purple',
      className: ['w-3 h-3', 'text-purple-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'cyan',
      className: ['w-3 h-3', 'text-cyan-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-3 h-3', 'text-primary-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-3 h-3', 'text-gray-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'grayBlue',
      className: ['w-3 h-3', 'text-grayBlue-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'grayModern',
      className: ['w-3 h-3', 'text-grayModern-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'grayWarm',
      className: ['w-3 h-3', 'text-grayWarm-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-3 h-3', 'text-error-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-3 h-3', 'text-rose-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-3 h-3', 'text-warning-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'yellow',
      className: ['w-3 h-3', 'text-yellow-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-3 h-3', 'text-blueDark-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-3 h-3', 'text-teal-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-3 h-3', 'text-success-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'blue',
      className: ['w-3 h-3', 'text-blue-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-3 h-3', 'text-moss-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-3 h-3', 'text-greenLight-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-3 h-3', 'text-violet-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-3 h-3', 'text-fuchsia-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'orangeDark',
      className: ['w-3 h-3', 'text-orangeDark-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'purple',
      className: ['w-3 h-3', 'text-purple-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'cyan',
      className: ['w-3 h-3', 'text-cyan-600'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'grayBlue',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'grayModern',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'grayWarm',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'yellow',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'blue',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'orangeDark',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'purple',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'cyan',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'grayBlue',
      className: ['w-4 h-4', 'text-grayBlue-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'grayModern',
      className: ['w-4 h-4', 'text-grayModern-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'grayWarm',
      className: ['w-4 h-4', 'text-grayWarm-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'yellow',
      className: ['w-4 h-4', 'text-yellow-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'blue',
      className: ['w-4 h-4', 'text-blue-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'orangeDark',
      className: ['w-4 h-4', 'text-orangeDark-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'purple',
      className: ['w-4 h-4', 'text-purple-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'cyan',
      className: ['w-4 h-4', 'text-cyan-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'grayBlue',
      className: ['w-4 h-4', 'text-grayBlue-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'grayModern',
      className: ['w-4 h-4', 'text-grayModern-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'grayWarm',
      className: ['w-4 h-4', 'text-grayWarm-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'yellow',
      className: ['w-4 h-4', 'text-yellow-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'blue',
      className: ['w-4 h-4', 'text-blue-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'orangeDark',
      className: ['w-4 h-4', 'text-orangeDark-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'purple',
      className: ['w-4 h-4', 'text-purple-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'cyan',
      className: ['w-4 h-4', 'text-cyan-600'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-grayBlue-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-grayModern-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-grayWarm-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-rose-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-warning-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-yellow-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-blueDark-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-teal-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-blue-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-moss-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-greenLight-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-violet-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-fuchsia-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-orangeDark-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-purple-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-cyan-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-grayBlue-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-grayModern-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-grayWarm-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-rose-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-warning-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-yellow-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-blueDark-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-teal-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-blue-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-moss-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-greenLight-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-violet-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-fuchsia-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-orangeDark-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-purple-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-cyan-600'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-grayBlue-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-grayModern-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-grayWarm-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-rose-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-warning-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-yellow-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-blueDark-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-teal-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-blue-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-moss-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-greenLight-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-violet-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-fuchsia-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-orangeDark-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-purple-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-cyan-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-grayBlue-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-grayModern-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-grayWarm-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-rose-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-warning-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-yellow-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-blueDark-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-teal-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-blue-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-moss-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-greenLight-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-violet-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-fuchsia-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-orangeDark-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-purple-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-cyan-600'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'grayBlue',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'grayModern',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'grayWarm',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'yellow',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'blue',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'orangeDark',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'purple',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'cyan',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-primary-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-gray-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'grayBlue',
      className: ['w-6 h-6', 'text-grayBlue-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'grayModern',
      className: ['w-6 h-6', 'text-grayModern-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'grayWarm',
      className: ['w-6 h-6', 'text-grayWarm-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-error-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-6 h-6', 'text-rose-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-6 h-6', 'text-warning-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'yellow',
      className: ['w-6 h-6', 'text-yellow-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-6 h-6', 'text-blueDark-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-6 h-6', 'text-teal-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-success-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'blue',
      className: ['w-6 h-6', 'text-blue-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-6 h-6', 'text-moss-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-6 h-6', 'text-greenLight-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-6 h-6', 'text-violet-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-6 h-6', 'text-fuchsia-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'orangeDark',
      className: ['w-6 h-6', 'text-orangeDark-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'purple',
      className: ['w-6 h-6', 'text-purple-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'cyan',
      className: ['w-6 h-6', 'text-cyan-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-primary-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-gray-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'grayBlue',
      className: ['w-6 h-6', 'text-grayBlue-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'grayModern',
      className: ['w-6 h-6', 'text-grayModern-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'grayWarm',
      className: ['w-6 h-6', 'text-grayWarm-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-error-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-6 h-6', 'text-rose-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-6 h-6', 'text-warning-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'yellow',
      className: ['w-6 h-6', 'text-yellow-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-6 h-6', 'text-blueDark-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-6 h-6', 'text-teal-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-success-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'blue',
      className: ['w-6 h-6', 'text-blue-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-6 h-6', 'text-moss-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-6 h-6', 'text-greenLight-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-6 h-6', 'text-violet-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-6 h-6', 'text-fuchsia-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'orangeDark',
      className: ['w-6 h-6', 'text-orangeDark-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'purple',
      className: ['w-6 h-6', 'text-purple-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'cyan',
      className: ['w-6 h-6', 'text-cyan-600'],
    },
  ],
});
