export const industries = [
  'Aerospace & Defense',
  'Air Freight & Logistics',
  'Automobile Components',
  'Automobiles',
  'Banks',
  'Beverages',
  'Biotechnology',
  'Broadline Retail',
  'Building Products',
  'Capital Markets',
  'Chemicals',
  'Commercial Services & Supplies',
  'Communications Equipment',
  'Construction & Engineering',
  'Construction Materials',
  'Consumer Finance',
  'Consumer Staples Distribution & Retail',
  'Containers & Packaging',
  'Diversified Consumer Services',
  'Diversified REITs',
  'Diversified Telecommunication Services',
  'Distributors',
  'Electric Utilities',
  'Electrical Equipment',
  'Electronic Equipment, Instruments & Components',
  'Energy Equipment & Services',
  'Entertainment',
  'Financial Services',
  'Food Products',
  'Gas Utilities',
  'Ground Transportation',
  'Health Care Equipment & Supplies',
  'Health Care Providers & Services',
  'Health Care REITs',
  'Health Care Technology',
  'Hotel & Resort REITs',
  'Hotels, Restaurants & Leisure',
  'Household Durables',
  'Household Products',
  'Independent Power and Renewable Electricity Producers',
  'Industrial Conglomerates',
  'Industrial REITs',
  'Insurance',
  'Interactive Media & Services',
  'Internet Software & Services',
  'IT Services',
  'Leisure Products',
  'Life Sciences Tools & Services',
  'Machinery',
  'Marine Transportation',
  'Media',
  'Metals & Mining',
  'Mortgage Real Estate Investment Trusts (REITs)',
  'Multi-Utilities',
  'Office REITs',
  'Oil, Gas & Consumable Fuels',
  'Paper & Forest Products',
  'Passenger Airlines',
  'Personal Products',
  'Pharmaceuticals',
  'Professional Services',
  'Real Estate Management & Development',
  'Residential REITs',
  'Retail REITs',
  'Semiconductors & Semiconductor Equipment',
  'Software',
  'Specialized REITs',
  'Specialty Retail',
  'Technology Hardware, Storage & Peripherals',
  'Textiles, Apparel & Luxury Goods',
  'Tobacco',
  'Trading Companies & Distributors',
  'Transportation Infrastructure',
  'Water Utilities',
  'Wireless Telecommunication Services',
];

export const countries = [
  { countryCodeA2: 'AW', country: 'Aruba' },
  { countryCodeA2: 'AF', country: 'Afghanistan' },
  { countryCodeA2: 'AO', country: 'Angola' },
  { countryCodeA2: 'AI', country: 'Anguilla' },
  { countryCodeA2: 'AL', country: 'Albania' },
  { countryCodeA2: 'AD', country: 'Andorra' },
  { countryCodeA2: 'AE', country: 'United Arab Emirates' },
  { countryCodeA2: 'AR', country: 'Argentina' },
  { countryCodeA2: 'AM', country: 'Armenia' },
  { countryCodeA2: 'AS', country: 'American Samoa' },
  { countryCodeA2: 'AQ', country: 'Antarctica' },
  { countryCodeA2: 'AG', country: 'Antigua and Barbuda' },
  { countryCodeA2: 'AU', country: 'Australia' },
  { countryCodeA2: 'AT', country: 'Austria' },
  { countryCodeA2: 'AZ', country: 'Azerbaijan' },
  { countryCodeA2: 'BI', country: 'Burundi' },
  { countryCodeA2: 'BE', country: 'Belgium' },
  { countryCodeA2: 'BJ', country: 'Benin' },
  { countryCodeA2: 'BF', country: 'Burkina Faso' },
  { countryCodeA2: 'BD', country: 'Bangladesh' },
  { countryCodeA2: 'BG', country: 'Bulgaria' },
  { countryCodeA2: 'BH', country: 'Bahrain' },
  { countryCodeA2: 'BS', country: 'Bahamas' },
  { countryCodeA2: 'BA', country: 'Bosnia and Herzegovina' },
  { countryCodeA2: 'BY', country: 'Belarus' },
  { countryCodeA2: 'BZ', country: 'Belize' },
  { countryCodeA2: 'BM', country: 'Bermuda' },
  { countryCodeA2: 'BO', country: 'Bolivia, Plurinational State of' },
  { countryCodeA2: 'BR', country: 'Brazil' },
  { countryCodeA2: 'BB', country: 'Barbados' },
  { countryCodeA2: 'BT', country: 'Bhutan' },
  { countryCodeA2: 'BV', country: 'Bouvet Island' },
  { countryCodeA2: 'BW', country: 'Botswana' },
  { countryCodeA2: 'CF', country: 'Central African Republic' },
  { countryCodeA2: 'CA', country: 'Canada' },
  { countryCodeA2: 'CH', country: 'Switzerland' },
  { countryCodeA2: 'CL', country: 'Chile' },
  { countryCodeA2: 'CN', country: 'China' },
  { countryCodeA2: 'CI', country: "Côte d'Ivoire" },
  { countryCodeA2: 'CM', country: 'Cameroon' },
  { countryCodeA2: 'CD', country: 'Congo, The Democratic Republic of the' },
  { countryCodeA2: 'CG', country: 'Congo' },
  { countryCodeA2: 'CO', country: 'Colombia' },
  { countryCodeA2: 'KM', country: 'Comoros' },
  { countryCodeA2: 'CV', country: 'Cabo Verde' },
  { countryCodeA2: 'CR', country: 'Costa Rica' },
  { countryCodeA2: 'CU', country: 'Cuba' },
  { countryCodeA2: 'KY', country: 'Cayman Islands' },
  { countryCodeA2: 'CY', country: 'Cyprus' },
  { countryCodeA2: 'CZ', country: 'Czechia' },
  { countryCodeA2: 'DE', country: 'Germany' },
  { countryCodeA2: 'DJ', country: 'Djibouti' },
  { countryCodeA2: 'DM', country: 'Dominica' },
  { countryCodeA2: 'DK', country: 'Denmark' },
  { countryCodeA2: 'DO', country: 'Dominican Republic' },
  { countryCodeA2: 'DZ', country: 'Algeria' },
  { countryCodeA2: 'EC', country: 'Ecuador' },
  { countryCodeA2: 'EG', country: 'Egypt' },
  { countryCodeA2: 'ER', country: 'Eritrea' },
  { countryCodeA2: 'EH', country: 'Western Sahara' },
  { countryCodeA2: 'ES', country: 'Spain' },
  { countryCodeA2: 'EE', country: 'Estonia' },
  { countryCodeA2: 'ET', country: 'Ethiopia' },
  { countryCodeA2: 'FI', country: 'Finland' },
  { countryCodeA2: 'FJ', country: 'Fiji' },
  { countryCodeA2: 'FK', country: 'Falkland Islands (Malvinas)' },
  { countryCodeA2: 'FR', country: 'France' },
  { countryCodeA2: 'FO', country: 'Faroe Islands' },
  { countryCodeA2: 'FM', country: 'Micronesia, Federated States of' },
  { countryCodeA2: 'GA', country: 'Gabon' },
  { countryCodeA2: 'GB', country: 'United Kingdom' },
  { countryCodeA2: 'GE', country: 'Georgia' },
  { countryCodeA2: 'GG', country: 'Guernsey' },
  { countryCodeA2: 'GH', country: 'Ghana' },
  { countryCodeA2: 'GI', country: 'Gibraltar' },
  { countryCodeA2: 'GN', country: 'Guinea' },
  { countryCodeA2: 'GM', country: 'Gambia' },
  { countryCodeA2: 'GW', country: 'Guinea-Bissau' },
  { countryCodeA2: 'GQ', country: 'Equatorial Guinea' },
  { countryCodeA2: 'GR', country: 'Greece' },
  { countryCodeA2: 'GD', country: 'Grenada' },
  { countryCodeA2: 'GL', country: 'Greenland' },
  { countryCodeA2: 'GT', country: 'Guatemala' },
  { countryCodeA2: 'GU', country: 'Guam' },
  { countryCodeA2: 'GY', country: 'Guyana' },
  { countryCodeA2: 'HK', country: 'Hong Kong' },
  { countryCodeA2: 'HN', country: 'Honduras' },
  { countryCodeA2: 'HR', country: 'Croatia' },
  { countryCodeA2: 'HT', country: 'Haiti' },
  { countryCodeA2: 'HU', country: 'Hungary' },
  { countryCodeA2: 'ID', country: 'Indonesia' },
  { countryCodeA2: 'IM', country: 'Isle of Man' },
  { countryCodeA2: 'IN', country: 'India' },
  { countryCodeA2: 'IO', country: 'British Indian Ocean Territory' },
  { countryCodeA2: 'IE', country: 'Ireland' },
  { countryCodeA2: 'IR', country: 'Iran, Islamic Republic of' },
  { countryCodeA2: 'IQ', country: 'Iraq' },
  { countryCodeA2: 'IS', country: 'Iceland' },
  { countryCodeA2: 'IL', country: 'Israel' },
  { countryCodeA2: 'IT', country: 'Italy' },
  { countryCodeA2: 'JM', country: 'Jamaica' },
  { countryCodeA2: 'JE', country: 'Jersey' },
  { countryCodeA2: 'JO', country: 'Jordan' },
  { countryCodeA2: 'JP', country: 'Japan' },
  { countryCodeA2: 'KZ', country: 'Kazakhstan' },
  { countryCodeA2: 'KE', country: 'Kenya' },
  { countryCodeA2: 'KG', country: 'Kyrgyzstan' },
  { countryCodeA2: 'KH', country: 'Cambodia' },
  { countryCodeA2: 'KI', country: 'Kiribati' },
  { countryCodeA2: 'KN', country: 'Saint Kitts and Nevis' },
  { countryCodeA2: 'KR', country: 'Korea, Republic of' },
  { countryCodeA2: 'KW', country: 'Kuwait' },
  { countryCodeA2: 'LA', country: "Lao People's Democratic Republic" },
  { countryCodeA2: 'LB', country: 'Lebanon' },
  { countryCodeA2: 'LR', country: 'Liberia' },
  { countryCodeA2: 'LY', country: 'Libya' },
  { countryCodeA2: 'LC', country: 'Saint Lucia' },
  { countryCodeA2: 'LI', country: 'Liechtenstein' },
  { countryCodeA2: 'LK', country: 'Sri Lanka' },
  { countryCodeA2: 'LS', country: 'Lesotho' },
  { countryCodeA2: 'LT', country: 'Lithuania' },
  { countryCodeA2: 'LU', country: 'Luxembourg' },
  { countryCodeA2: 'LV', country: 'Latvia' },
  { countryCodeA2: 'MO', country: 'Macao' },
  { countryCodeA2: 'MA', country: 'Morocco' },
  { countryCodeA2: 'MC', country: 'Monaco' },
  { countryCodeA2: 'MD', country: 'Moldova, Republic of' },
  { countryCodeA2: 'MG', country: 'Madagascar' },
  { countryCodeA2: 'MV', country: 'Maldives' },
  { countryCodeA2: 'MX', country: 'Mexico' },
  { countryCodeA2: 'MH', country: 'Marshall Islands' },
  { countryCodeA2: 'MK', country: 'North Macedonia' },
  { countryCodeA2: 'ML', country: 'Mali' },
  { countryCodeA2: 'MT', country: 'Malta' },
  { countryCodeA2: 'MM', country: 'Myanmar' },
  { countryCodeA2: 'ME', country: 'Montenegro' },
  { countryCodeA2: 'MN', country: 'Mongolia' },
  { countryCodeA2: 'MP', country: 'Northern Mariana Islands' },
  { countryCodeA2: 'MZ', country: 'Mozambique' },
  { countryCodeA2: 'MR', country: 'Mauritania' },
  { countryCodeA2: 'MS', country: 'Montserrat' },
  { countryCodeA2: 'MU', country: 'Mauritius' },
  { countryCodeA2: 'MW', country: 'Malawi' },
  { countryCodeA2: 'MY', country: 'Malaysia' },
  { countryCodeA2: 'NA', country: 'Namibia' },
  { countryCodeA2: 'NC', country: 'New Caledonia' },
  { countryCodeA2: 'NE', country: 'Niger' },
  { countryCodeA2: 'NF', country: 'Norfolk Island' },
  { countryCodeA2: 'NG', country: 'Nigeria' },
  { countryCodeA2: 'NI', country: 'Nicaragua' },
  { countryCodeA2: 'NU', country: 'Niue' },
  { countryCodeA2: 'NL', country: 'Netherlands' },
  { countryCodeA2: 'NO', country: 'Norway' },
  { countryCodeA2: 'NP', country: 'Nepal' },
  { countryCodeA2: 'NR', country: 'Nauru' },
  { countryCodeA2: 'NZ', country: 'New Zealand' },
  { countryCodeA2: 'OM', country: 'Oman' },
  { countryCodeA2: 'PK', country: 'Pakistan' },
  { countryCodeA2: 'PA', country: 'Panama' },
  { countryCodeA2: 'PE', country: 'Peru' },
  { countryCodeA2: 'PH', country: 'Philippines' },
  { countryCodeA2: 'PW', country: 'Palau' },
  { countryCodeA2: 'PG', country: 'Papua New Guinea' },
  { countryCodeA2: 'PL', country: 'Poland' },
  { countryCodeA2: 'PR', country: 'Puerto Rico' },
  { countryCodeA2: 'PT', country: 'Portugal' },
  { countryCodeA2: 'PY', country: 'Paraguay' },
  { countryCodeA2: 'PS', country: 'Palestine, State of' },
  { countryCodeA2: 'QA', country: 'Qatar' },
  { countryCodeA2: 'RE', country: 'Réunion' },
  { countryCodeA2: 'RO', country: 'Romania' },
  { countryCodeA2: 'RU', country: 'Russian Federation' },
  { countryCodeA2: 'RW', country: 'Rwanda' },
  { countryCodeA2: 'SA', country: 'Saudi Arabia' },
  { countryCodeA2: 'SD', country: 'Sudan' },
  { countryCodeA2: 'SN', country: 'Senegal' },
  { countryCodeA2: 'SG', country: 'Singapore' },
  {
    countryCodeA2: 'SH',
    country: 'Saint Helena, Ascension and Tristan da Cunha',
  },
  { countryCodeA2: 'SJ', country: 'Svalbard and Jan Mayen' },
  { countryCodeA2: 'SB', country: 'Solomon Islands' },
  { countryCodeA2: 'SL', country: 'Sierra Leone' },
  { countryCodeA2: 'SV', country: 'El Salvador' },
  { countryCodeA2: 'SM', country: 'San Marino' },
  { countryCodeA2: 'SO', country: 'Somalia' },
  { countryCodeA2: 'PM', country: 'Saint Pierre and Miquelon' },
  { countryCodeA2: 'RS', country: 'Serbia' },
  { countryCodeA2: 'SS', country: 'South Sudan' },
  { countryCodeA2: 'ST', country: 'Sao Tome and Principe' },
  { countryCodeA2: 'SR', country: 'Suriname' },
  { countryCodeA2: 'SK', country: 'Slovakia' },
  { countryCodeA2: 'SI', country: 'Slovenia' },
  { countryCodeA2: 'SE', country: 'Sweden' },
  { countryCodeA2: 'SZ', country: 'Eswatini' },
  { countryCodeA2: 'SX', country: 'Sint Maarten (Dutch part)' },
  { countryCodeA2: 'SC', country: 'Seychelles' },
  { countryCodeA2: 'SY', country: 'Syrian Arab Republic' },
  { countryCodeA2: 'TC', country: 'Turks and Caicos Islands' },
  { countryCodeA2: 'TD', country: 'Chad' },
  { countryCodeA2: 'TG', country: 'Togo' },
  { countryCodeA2: 'TH', country: 'Thailand' },
  { countryCodeA2: 'TJ', country: 'Tajikistan' },
  { countryCodeA2: 'TK', country: 'Tokelau' },
  { countryCodeA2: 'TM', country: 'Turkmenistan' },
  { countryCodeA2: 'TL', country: 'Timor-Leste' },
  { countryCodeA2: 'TO', country: 'Tonga' },
  { countryCodeA2: 'TT', country: 'Trinidad and Tobago' },
  { countryCodeA2: 'TN', country: 'Tunisia' },
  { countryCodeA2: 'TR', country: 'Turkey' },
  { countryCodeA2: 'TV', country: 'Tuvalu' },
  { countryCodeA2: 'TW', country: 'Taiwan, Province of China' },
  { countryCodeA2: 'TZ', country: 'Tanzania, United Republic of' },
  { countryCodeA2: 'UG', country: 'Uganda' },
  { countryCodeA2: 'UA', country: 'Ukraine' },
  { countryCodeA2: 'UY', country: 'Uruguay' },
  { countryCodeA2: 'US', country: 'United States' },
  { countryCodeA2: 'UZ', country: 'Uzbekistan' },
  { countryCodeA2: 'VC', country: 'Saint Vincent and the Grenadines' },
  { countryCodeA2: 'VE', country: 'Venezuela, Bolivarian Republic of' },
  { countryCodeA2: 'VN', country: 'Viet Nam' },
  { countryCodeA2: 'VU', country: 'Vanuatu' },
  { countryCodeA2: 'WS', country: 'Samoa' },
  { countryCodeA2: 'YE', country: 'Yemen' },
  { countryCodeA2: 'ZA', country: 'South Africa' },
  { countryCodeA2: 'ZM', country: 'Zambia' },
  { countryCodeA2: 'ZW', country: 'Zimbabwe' },
];
