export {
  useGetContactCommunicationChannelsQuery,
  useGetContactPersonalDetailsQuery,
  useCreateContactMutation,
  useUpdateContactEmailMutation,
  useAddEmailToContactMutation,
  useRemoveEmailFromContactMutation,
  useUpdateContactPhoneNumberMutation,
  useRemovePhoneNumberFromContactMutation,
  useAddPhoneToContactMutation,
  useAddPhoneToOrganizationMutation,
  useRemovePhoneNumberFromOrganizationMutation,
  useUpdateOrganizationPhoneNumberMutation,
  GetOrganizationCommunicationChannelsDocument,
} from '../../graphQL/__generated__/generated';
export type {
  Contact,
  GetContactCommunicationChannelsQuery,
  GetContactPersonalDetailsQuery,
  ContactInput,
  CreateContactMutation,
  Email,
  UpdateContactEmailMutation,
  AddPhoneToOrganizationMutation,
  RemovePhoneNumberFromOrganizationMutation,
  UpdateOrganizationPhoneNumberMutation,
  PhoneNumber,
  PhoneNumberUpdateInput,
  GetOrganizationCommunicationChannelsQuery,
} from '../../graphQL/__generated__/generated';
