jetstream: enabled

system_account: SYS

accounts: {
  SYS: {
    users: [
      {user: admin, password: password}
    ]
  }
  
  DEFAULT: {
    users: [
      {user: client, password: password}
    ]
  }
}

http_port: 8222
