serviceName: event-processing-platform
grpc:
  port: :5001
  development: true
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8001
  checkIntervalSeconds: 10
logger:
  level: debug
  devMode: false
  encoder: console
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbName: products
  sslMode: false
jaeger:
  enable: true
  serviceName: event-processing-platform
  hostPort: "localhost:6831"
  logSpans: false
eventStoreConfig:
  connectionString: "esdb://localhost:2113?tls=false"
subscriptions:
  poolSize: 60
  orderPrefix: "order-"
  mongoProjectionGroupName: "order1"
  elasticProjectionGroupName: "order-elastic"
