serviceName: es_service
grpc:
  port: :5001
  development: true
http:
  port: :5007
  development: true
  basePath: /api/v1
  ordersPath: /api/v1/orders
  debugErrorsResponse: true
  ignoreLogUrls: [ "metrics" ]
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8001
  checkIntervalSeconds: 10
logger:
  level: debug
  devMode: false
  encoder: console
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbName: products
  sslMode: false
mongo:
  uri: "mongodb://localhost:27017"
  user: admin
  password: admin
  db: orders
mongoCollections:
  orders: orders
jaeger:
  enable: true
  serviceName: es_service
  hostPort: "localhost:6831"
  logSpans: false
eventStoreConfig:
  connectionString: "esdb://localhost:2113?tls=false"
subscriptions:
  poolSize: 60
  orderPrefix: "order-"
  mongoProjectionGroupName: "order1"
  elasticProjectionGroupName: "order-elastic"
elastic:
  url: "http://localhost:9200"
  sniff: false
  gzip: true
  explain: true
  fetchSource: true
  version: true
  pretty: true
elasticIndexes:
  orders: "orders"
