package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"errors"

	"github.com/customeros/customeros/packages/server/leads/api/graphql/graphql_model"
	"github.com/customeros/customeros/packages/server/leads/api/graphql/mappers"
	"github.com/customeros/customeros/packages/server/leads/internal/models"
	"github.com/customeros/customeros/packages/server/leads/internal/telemetry"
	"github.com/customeros/customeros/packages/server/leads/internal/utils"
)

// CreateWebtracker is the resolver for the createWebtracker field.
func (r *mutationResolver) CreateWebtracker(ctx context.Context, tracker graphql_model.WebtrackerSaveInput) (*graphql_model.Webtracker, error) {
	span, ctx := telemetry.StartGraphQLSpan(ctx, "graphQLResolvers.CreateWebtracker")
	defer span.Finish()

	cnameHost := ""
	switch {
	case tracker.CnameHost == nil && *tracker.CnameHost == "":
		// do nothing
	case utils.IsLowerAlphanumeric(*tracker.CnameHost):
		cnameHost = *tracker.CnameHost
	default:
		err := errors.New("Invalid CNAME Host")
		span.TraceError(err)
		return nil, err
	}

	newTracker := &models.WebTracker{
		ID:        utils.GenerateNanoIDWithPrefix("trkr", 16),
		Domain:    tracker.Domain,
		CNAMEHost: cnameHost,
	}

	return mappers.ToWebtrackerGraphQL(newTracker), nil
}

// UpdateWebtracker is the resolver for the updateWebtracker field.
func (r *mutationResolver) UpdateWebtracker(ctx context.Context, tracker graphql_model.WebtrackerSaveInput) (*graphql_model.Webtracker, error) {
	span, ctx := telemetry.StartGraphQLSpan(ctx, "graphQLResolvers.UpdateWebtracker")
	defer span.Finish()

	cnameHost := ""
	switch {
	case tracker.CnameHost == nil && *tracker.CnameHost == "":
		err := errors.New("cnameHost is empty")
		span.TraceError(err)
		return nil, err
	case !utils.IsLowerAlphanumeric(*tracker.CnameHost):
		err := errors.New("Invalid cnameHost")
		span.TraceError(err)
		return nil, err
	default:
		cnameHost = *tracker.CnameHost
		updatedTracker, err := r.services.WebtrackerRegistrationService.UpdateCNAMEHost(ctx, cnameHost)
		if err != nil {
			span.TraceError(err)
			return nil, err
		}
		return mappers.ToWebtrackerGraphQL(updatedTracker), nil
	}
}

// VerifyWebtrackerCname is the resolver for the verifyWebtrackerCname field.
func (r *mutationResolver) VerifyWebtrackerCname(ctx context.Context, id string) (bool, error) {
	span, ctx := telemetry.StartGraphQLSpan(ctx, "graphQLResolvers.VerifyWebtrackerCname")
	defer span.Finish()

	if id == "" {
		err := errors.New("ID cannot be empty")
		span.TraceError(err)
		return false, err
	}

	return r.services.WebtrackerRegistrationService.IsCNAMEConfigured(ctx, id)
}

// ArchiveWebtracker is the resolver for the archiveWebtracker field.
func (r *mutationResolver) ArchiveWebtracker(ctx context.Context, id string) (bool, error) {
	span, ctx := telemetry.StartGraphQLSpan(ctx, "graphQLResolvers.VerifyWebtrackerCname")
	defer span.Finish()

	if id == "" {
		err := errors.New("ID cannot be empty")
		span.TraceError(err)
		return false, err
	}

	err := r.services.WebtrackerRegistrationService.ArchiveWebtracker(ctx, id)
	if err != nil {
		span.TraceError(err)
		return false, err
	}
	return true, nil
}

// Webtracker is the resolver for the webtracker field.
func (r *queryResolver) Webtracker(ctx context.Context, id string) (*graphql_model.Webtracker, error) {
	span, ctx := telemetry.StartGraphQLSpan(ctx, "graphQLResolvers.Webtracker")
	defer span.Finish()

	if id == "" {
		err := errors.New("ID cannot be empty")
		span.TraceError(err)
		return nil, err
	}

	tracker, err := r.services.WebtrackerRegistrationService.GetWebtracker(ctx, id)
	if err != nil {
		span.TraceError(err)
		return nil, err
	}

	return mappers.ToWebtrackerGraphQL(tracker), nil
}

// Webtrackers is the resolver for the webtrackers field.
func (r *queryResolver) Webtrackers(ctx context.Context) ([]*graphql_model.Webtracker, error) {
	span, ctx := telemetry.StartGraphQLSpan(ctx, "graphQLResolvers.Webtracker")
	defer span.Finish()

	webtrackers, err := r.services.WebtrackerRegistrationService.GetActiveWebtrackers(ctx)
	if err != nil {
		span.TraceError(err)
		return nil, err
	}

	return mappers.ToWebtrackerGraphQLSlice(webtrackers), nil
}
