import { SelectOption } from '@shared/types/SelectOptions';

export const industryOptions: SelectOption[] = [
  { value: 'Aerospace & Defense', label: 'Aerospace & Defense' },
  { value: 'Air Freight & Logistics', label: 'Air Freight & Logistics' },
  { value: 'Automobile Components', label: 'Automobile Components' },
  { value: 'Automobiles', label: 'Automobiles' },
  { value: 'Banks', label: 'Banks' },
  { value: 'Beverages', label: 'Beverages' },
  { value: 'Biotechnology', label: 'Biotechnology' },
  { value: 'Broadline Retail', label: 'Broadline Retail' },
  { value: 'Building Products', label: 'Building Products' },
  { value: 'Capital Markets', label: 'Capital Markets' },
  { value: 'Chemicals', label: 'Chemicals' },
  {
    value: 'Commercial Services & Supplies',
    label: 'Commercial Services & Supplies',
  },
  { value: 'Communications Equipment', label: 'Communications Equipment' },
  { value: 'Construction & Engineering', label: 'Construction & Engineering' },
  { value: 'Construction Materials', label: 'Construction Materials' },
  { value: 'Consumer Finance', label: 'Consumer Finance' },
  {
    value: 'Consumer Staples Distribution & Retail',
    label: 'Consumer Staples Distribution & Retail',
  },
  { value: 'Containers & Packaging', label: 'Containers & Packaging' },
  {
    value: 'Diversified Consumer Services',
    label: 'Diversified Consumer Services',
  },
  { value: 'Diversified REITs', label: 'Diversified REITs' },
  {
    value: 'Diversified Telecommunication Services',
    label: 'Diversified Telecommunication Services',
  },
  { value: 'Distributors', label: 'Distributors' },
  { value: 'Electric Utilities', label: 'Electric Utilities' },
  { value: 'Electrical Equipment', label: 'Electrical Equipment' },
  {
    value: 'Electronic Equipment, Instruments & Components',
    label: 'Electronic Equipment, Instruments & Components',
  },
  {
    value: 'Energy Equipment & Services',
    label: 'Energy Equipment & Services',
  },
  { value: 'Entertainment', label: 'Entertainment' },
  { value: 'Financial Services', label: 'Financial Services' },
  { value: 'Food Products', label: 'Food Products' },
  { value: 'Gas Utilities', label: 'Gas Utilities' },
  { value: 'Ground Transportation', label: 'Ground Transportation' },
  {
    value: 'Health Care Equipment & Supplies',
    label: 'Health Care Equipment & Supplies',
  },
  {
    value: 'Health Care Providers & Services',
    label: 'Health Care Providers & Services',
  },
  { value: 'Health Care REITs', label: 'Health Care REITs' },
  { value: 'Health Care Technology', label: 'Health Care Technology' },
  { value: 'Hotel & Resort REITs', label: 'Hotel & Resort REITs' },
  {
    value: 'Hotels, Restaurants & Leisure',
    label: 'Hotels, Restaurants & Leisure',
  },
  { value: 'Household Durables', label: 'Household Durables' },
  { value: 'Household Products', label: 'Household Products' },
  {
    value: 'Independent Power and Renewable Electricity Producers',
    label: 'Independent Power and Renewable Electricity Producers',
  },
  { value: 'Industrial Conglomerates', label: 'Industrial Conglomerates' },
  { value: 'Industrial REITs', label: 'Industrial REITs' },
  { value: 'Insurance', label: 'Insurance' },
  {
    value: 'Interactive Media & Services',
    label: 'Interactive Media & Services',
  },
  {
    value: 'Internet Software & Services',
    label: 'Internet Software & Services',
  },
  { value: 'IT Services', label: 'IT Services' },
  { value: 'Leisure Products', label: 'Leisure Products' },
  {
    value: 'Life Sciences Tools & Services',
    label: 'Life Sciences Tools & Services',
  },
  { value: 'Machinery', label: 'Machinery' },
  { value: 'Marine Transportation', label: 'Marine Transportation' },
  { value: 'Media', label: 'Media' },
  { value: 'Metals & Mining', label: 'Metals & Mining' },
  {
    value: 'Mortgage Real Estate Investment Trusts (REITs)',
    label: 'Mortgage Real Estate Investment Trusts (REITs)',
  },
  { value: 'Multi-Utilities', label: 'Multi-Utilities' },
  { value: 'Office REITs', label: 'Office REITs' },
  {
    value: 'Oil, Gas & Consumable Fuels',
    label: 'Oil, Gas & Consumable Fuels',
  },
  { value: 'Paper & Forest Products', label: 'Paper & Forest Products' },
  { value: 'Passenger Airlines', label: 'Passenger Airlines' },
  { value: 'Personal Products', label: 'Personal Products' },
  { value: 'Pharmaceuticals', label: 'Pharmaceuticals' },
  { value: 'Professional Services', label: 'Professional Services' },
  {
    value: 'Real Estate Management & Development',
    label: 'Real Estate Management & Development',
  },
  { value: 'Residential REITs', label: 'Residential REITs' },
  { value: 'Retail REITs', label: 'Retail REITs' },
  {
    value: 'Semiconductors & Semiconductor Equipment',
    label: 'Semiconductors & Semiconductor Equipment',
  },
  { value: 'Software', label: 'Software' },
  { value: 'Specialized REITs', label: 'Specialized REITs' },
  { value: 'Specialty Retail', label: 'Specialty Retail' },
  {
    value: 'Technology Hardware, Storage & Peripherals',
    label: 'Technology Hardware, Storage & Peripherals',
  },
  {
    value: 'Textiles, Apparel & Luxury Goods',
    label: 'Textiles, Apparel & Luxury Goods',
  },
  { value: 'Tobacco', label: 'Tobacco' },
  {
    value: 'Trading Companies & Distributors',
    label: 'Trading Companies & Distributors',
  },
  {
    value: 'Transportation Infrastructure',
    label: 'Transportation Infrastructure',
  },
  { value: 'Water Utilities', label: 'Water Utilities' },
  {
    value: 'Wireless Telecommunication Services',
    label: 'Wireless Telecommunication Services',
  },
];

export const locationsOptions: SelectOption[] = [
  { value: 'AF', label: 'AF • Afghanistan' },
  { value: 'AL', label: 'AL • Albania' },
  { value: 'DZ', label: 'DZ • Algeria' },
  { value: 'AS', label: 'AS • American Samoa' },
  { value: 'AD', label: 'AD • Andorra' },
  { value: 'AO', label: 'AO • Angola' },
  { value: 'AI', label: 'AI • Anguilla' },
  { value: 'AQ', label: 'AQ • Antarctica' },
  { value: 'AG', label: 'AG • Antigua and Barbuda' },
  { value: 'AR', label: 'AR • Argentina' },
  { value: 'AM', label: 'AM • Armenia' },
  { value: 'AW', label: 'AW • Aruba' },
  { value: 'AU', label: 'AU • Australia' },
  { value: 'AT', label: 'AT • Austria' },
  { value: 'AZ', label: 'AZ • Azerbaijan' },
  { value: 'BS', label: 'BS • Bahamas' },
  { value: 'BH', label: 'BH • Bahrain' },
  { value: 'BD', label: 'BD • Bangladesh' },
  { value: 'BB', label: 'BB • Barbados' },
  { value: 'BY', label: 'BY • Belarus' },
  { value: 'BE', label: 'BE • Belgium' },
  { value: 'BZ', label: 'BZ • Belize' },
  { value: 'BJ', label: 'BJ • Benin' },
  { value: 'BM', label: 'BM • Bermuda' },
  { value: 'BT', label: 'BT • Bhutan' },
  { value: 'BO', label: 'BO • Bolivia' },
  { value: 'BA', label: 'BA • Bosnia and Herzegovina' },
  { value: 'BW', label: 'BW • Botswana' },
  { value: 'BV', label: 'BV • Bouvet Island' },
  { value: 'BR', label: 'BR • Brazil' },
  { value: 'IO', label: 'IO • British Indian Ocean Territory' },
  { value: 'BN', label: 'BN • Brunei Darussalam' },
  { value: 'BG', label: 'BG • Bulgaria' },
  { value: 'BF', label: 'BF • Burkina Faso' },
  { value: 'BI', label: 'BI • Burundi' },
  { value: 'CV', label: 'CV • Cape Verde' },
  { value: 'KH', label: 'KH • Cambodia' },
  { value: 'CM', label: 'CM • Cameroon' },
  { value: 'CA', label: 'CA • Canada' },
  { value: 'KY', label: 'KY • Cayman Islands' },
  { value: 'CF', label: 'CF • Central African Republic' },
  { value: 'TD', label: 'TD • Chad' },
  { value: 'CL', label: 'CL • Chile' },
  { value: 'CN', label: 'CN • China' },
  { value: 'CX', label: 'CX • Christmas Island' },
  { value: 'CC', label: 'CC • Cocos (Keeling) Islands' },
  { value: 'CO', label: 'CO • Colombia' },
  { value: 'KM', label: 'KM • Comoros' },
  { value: 'CG', label: 'CG • Congo' },
  { value: 'CD', label: 'CD • Congo, The Democratic Republic of the' },
  { value: 'CK', label: 'CK • Cook Islands' },
  { value: 'CR', label: 'CR • Costa Rica' },
  { value: 'CI', label: "CI • Côte d'Ivoire" },
  { value: 'HR', label: 'HR • Croatia' },
  { value: 'CU', label: 'CU • Cuba' },
  { value: 'CY', label: 'CY • Cyprus' },
  { value: 'CZ', label: 'CZ • Czech Republic' },
  { value: 'DK', label: 'DK • Denmark' },
  { value: 'DJ', label: 'DJ • Djibouti' },
  { value: 'DM', label: 'DM • Dominica' },
  { value: 'DO', label: 'DO • Dominican Republic' },
  { value: 'EC', label: 'EC • Ecuador' },
  { value: 'EG', label: 'EG • Egypt' },
  { value: 'SV', label: 'SV • El Salvador' },
  { value: 'GQ', label: 'GQ • Equatorial Guinea' },
  { value: 'ER', label: 'ER • Eritrea' },
  { value: 'EE', label: 'EE • Estonia' },
  { value: 'ET', label: 'ET • Ethiopia' },
  { value: 'FK', label: 'FK • Falkland Islands (Malvinas)' },
  { value: 'FO', label: 'FO • Faroe Islands' },
  { value: 'FJ', label: 'FJ • Fiji' },
  { value: 'FI', label: 'FI • Finland' },
  { value: 'FR', label: 'FR • France' },
  { value: 'GF', label: 'GF • French Guiana' },
  { value: 'PF', label: 'PF • French Polynesia' },
  { value: 'TF', label: 'TF • French Southern Territories' },
  { value: 'GA', label: 'GA • Gabon' },
  { value: 'GM', label: 'GM • Gambia' },
  { value: 'GE', label: 'GE • Georgia' },
  { value: 'DE', label: 'DE • Germany' },
  { value: 'GH', label: 'GH • Ghana' },
  { value: 'GI', label: 'GI • Gibraltar' },
  { value: 'GR', label: 'GR • Greece' },
  { value: 'GL', label: 'GL • Greenland' },
  { value: 'GD', label: 'GD • Grenada' },
  { value: 'GP', label: 'GP • Guadeloupe' },
  { value: 'GU', label: 'GU • Guam' },
  { value: 'GT', label: 'GT • Guatemala' },
  { value: 'GG', label: 'GG • Guernsey' },
  { value: 'GN', label: 'GN • Guinea' },
  { value: 'GW', label: 'GW • Guinea-Bissau' },
  { value: 'GY', label: 'GY • Guyana' },
  { value: 'HT', label: 'HT • Haiti' },
  { value: 'HM', label: 'HM • Heard Island and McDonald Islands' },
  { value: 'VA', label: 'VA • Holy See (Vatican City State)' },
  { value: 'HN', label: 'HN • Honduras' },
  { value: 'HK', label: 'HK • Hong Kong' },
  { value: 'HU', label: 'HU • Hungary' },
  { value: 'IS', label: 'IS • Iceland' },
  { value: 'IN', label: 'IN • India' },
  { value: 'ID', label: 'ID • Indonesia' },
  { value: 'IR', label: 'IR • Iran, Islamic Republic of' },
  { value: 'IQ', label: 'IQ • Iraq' },
  { value: 'IE', label: 'IE • Ireland' },
  { value: 'IM', label: 'IM • Isle of Man' },
  { value: 'IL', label: 'IL • Israel' },
  { value: 'IT', label: 'IT • Italy' },
  { value: 'JM', label: 'JM • Jamaica' },
  { value: 'JP', label: 'JP • Japan' },
  { value: 'JE', label: 'JE • Jersey' },
  { value: 'JO', label: 'JO • Jordan' },
  { value: 'KZ', label: 'KZ • Kazakhstan' },
  { value: 'KE', label: 'KE • Kenya' },
  { value: 'KI', label: 'KI • Kiribati' },
  { value: 'KP', label: "KP • Korea, Democratic People's Republic of" },
  { value: 'KR', label: 'KR • Korea, Republic of' },
  { value: 'KW', label: 'KW • Kuwait' },
  { value: 'KG', label: 'KG • Kyrgyzstan' },
  { value: 'LA', label: "LA • Lao People's Democratic Republic" },
  { value: 'LV', label: 'LV • Latvia' },
  { value: 'LB', label: 'LB • Lebanon' },
  { value: 'LS', label: 'LS • Lesotho' },
  { value: 'LR', label: 'LR • Liberia' },
  { value: 'LY', label: 'LY • Libyan Arab Jamahiriya' },
  { value: 'LI', label: 'LI • Liechtenstein' },
  { value: 'LT', label: 'LT • Lithuania' },
  { value: 'LU', label: 'LU • Luxembourg' },
  { value: 'MO', label: 'MO • Macao' },
  { value: 'MK', label: 'MK • Macedonia, The Former Yugoslav Republic of' },
  { value: 'MG', label: 'MG • Madagascar' },
  { value: 'MW', label: 'MW • Malawi' },
  { value: 'MY', label: 'MY • Malaysia' },
  { value: 'MV', label: 'MV • Maldives' },
  { value: 'ML', label: 'ML • Mali' },
  { value: 'MT', label: 'MT • Malta' },
  { value: 'MH', label: 'MH • Marshall Islands' },
  { value: 'MQ', label: 'MQ • Martinique' },
  { value: 'MR', label: 'MR • Mauritania' },
  { value: 'MU', label: 'MU • Mauritius' },
  { value: 'YT', label: 'YT • Mayotte' },
  { value: 'MX', label: 'MX • Mexico' },
  { value: 'FM', label: 'FM • Micronesia, Federated States of' },
  { value: 'MD', label: 'MD • Moldova, Republic of' },
  { value: 'MC', label: 'MC • Monaco' },
  { value: 'MN', label: 'MN • Mongolia' },
  { value: 'ME', label: 'ME • Montenegro' },
  { value: 'MS', label: 'MS • Montserrat' },
  { value: 'MA', label: 'MA • Morocco' },
  { value: 'MZ', label: 'MZ • Mozambique' },
  { value: 'MM', label: 'MM • Myanmar' },
  { value: 'NA', label: 'NA • Namibia' },
  { value: 'NR', label: 'NR • Nauru' },
  { value: 'NP', label: 'NP • Nepal' },
  { value: 'NL', label: 'NL • Netherlands' },
  { value: 'NC', label: 'NC • New Caledonia' },
  { value: 'NZ', label: 'NZ • New Zealand' },
  { value: 'NI', label: 'NI • Nicaragua' },
  { value: 'NE', label: 'NE • Niger' },
  { value: 'NG', label: 'NG • Nigeria' },
  { value: 'NU', label: 'NU • Niue' },
  { value: 'NF', label: 'NF • Norfolk Island' },
  { value: 'MP', label: 'MP • Northern Mariana Islands' },
  { value: 'NO', label: 'NO • Norway' },
  { value: 'OM', label: 'OM • Oman' },
  { value: 'PK', label: 'PK • Pakistan' },
  { value: 'PW', label: 'PW • Palau' },
  { value: 'PS', label: 'PS • Palestinian Territory, Occupied' },
  { value: 'PA', label: 'PA • Panama' },
  { value: 'PG', label: 'PG • Papua New Guinea' },
  { value: 'PY', label: 'PY • Paraguay' },
  { value: 'PE', label: 'PE • Peru' },
  { value: 'PH', label: 'PH • Philippines' },
  { value: 'PN', label: 'PN • Pitcairn' },
  { value: 'PL', label: 'PL • Poland' },
  { value: 'PT', label: 'PT • Portugal' },
  { value: 'PR', label: 'PR • Puerto Rico' },
  { value: 'QA', label: 'QA • Qatar' },
  { value: 'RE', label: 'RE • Réunion' },
  { value: 'RO', label: 'RO • Romania' },
  { value: 'RU', label: 'RU • Russian Federation' },
  { value: 'RW', label: 'RW • Rwanda' },
  { value: 'BL', label: 'BL • Saint Barthélemy' },
  { value: 'SH', label: 'SH • Saint Helena' },
  { value: 'KN', label: 'KN • Saint Kitts and Nevis' },
  { value: 'LC', label: 'LC • Saint Lucia' },
  { value: 'MF', label: 'MF • Saint Martin (French part)' },
  { value: 'PM', label: 'PM • Saint Pierre and Miquelon' },
  { value: 'VC', label: 'VC • Saint Vincent and the Grenadines' },
  { value: 'WS', label: 'WS • Samoa' },
  { value: 'SM', label: 'SM • San Marino' },
  { value: 'ST', label: 'ST • Sao Tome and Principe' },
  { value: 'SA', label: 'SA • Saudi Arabia' },
  { value: 'SN', label: 'SN • Senegal' },
  { value: 'RS', label: 'RS • Serbia' },
  { value: 'SC', label: 'SC • Seychelles' },
  { value: 'SL', label: 'SL • Sierra Leone' },
  { value: 'SG', label: 'SG • Singapore' },
  { value: 'SX', label: 'SX • Sint Maarten (Dutch part)' },
  { value: 'SK', label: 'SK • Slovakia' },
  { value: 'SI', label: 'SI • Slovenia' },
  { value: 'SB', label: 'SB • Solomon Islands' },
  { value: 'SO', label: 'SO • Somalia' },
  { value: 'ZA', label: 'ZA • South Africa' },
  { value: 'GS', label: 'GS • South Georgia and the South Sandwich Islands' },
  { value: 'SS', label: 'SS • South Sudan' },
  { value: 'ES', label: 'ES • Spain' },
  { value: 'LK', label: 'LK • Sri Lanka' },
  { value: 'SD', label: 'SD • Sudan' },
  { value: 'SR', label: 'SR • Suriname' },
  { value: 'SJ', label: 'SJ • Svalbard and Jan Mayen' },
  { value: 'SZ', label: 'SZ • Swaziland' },
  { value: 'SE', label: 'SE • Sweden' },
  { value: 'CH', label: 'CH • Switzerland' },
  { value: 'SY', label: 'SY • Syrian Arab Republic' },
  { value: 'TW', label: 'TW • Taiwan, Province of China' },
  { value: 'TJ', label: 'TJ • Tajikistan' },
  { value: 'TZ', label: 'TZ • Tanzania, United Republic of' },
  { value: 'TH', label: 'TH • Thailand' },
  { value: 'TL', label: 'TL • Timor-Leste' },
  { value: 'TG', label: 'TG • Togo' },
  { value: 'TK', label: 'TK • Tokelau' },
  { value: 'TO', label: 'TO • Tonga' },
  { value: 'TT', label: 'TT • Trinidad and Tobago' },
  { value: 'TN', label: 'TN • Tunisia' },
  { value: 'TR', label: 'TR • Turkey' },
  { value: 'TM', label: 'TM • Turkmenistan' },
  { value: 'TC', label: 'TC • Turks and Caicos Islands' },
  { value: 'TV', label: 'TV • Tuvalu' },
  { value: 'UG', label: 'UG • Uganda' },
  { value: 'UA', label: 'UA • Ukraine' },
  { value: 'AE', label: 'AE • United Arab Emirates' },
  { value: 'GB', label: 'GB • United Kingdom' },
  { value: 'US', label: 'US • United States' },
  { value: 'UM', label: 'UM • United States Minor Outlying Islands' },
  { value: 'UY', label: 'UY • Uruguay' },
  { value: 'UZ', label: 'UZ • Uzbekistan' },
  { value: 'VU', label: 'VU • Vanuatu' },
  { value: 'VE', label: 'VE • Venezuela, Bolivarian Republic of' },
  { value: 'VN', label: 'VN • Viet Nam' },
  { value: 'VG', label: 'VG • Virgin Islands, British' },
  { value: 'VI', label: 'VI • Virgin Islands, U.S.' },
  { value: 'WF', label: 'WF • Wallis and Futuna' },
  { value: 'EH', label: 'EH • Western Sahara' },
  { value: 'YE', label: 'YE • Yemen' },
  { value: 'ZM', label: 'ZM • Zambia' },
  { value: 'ZW', label: 'ZW • Zimbabwe' },
];
