import { Currency } from '@graphql/types';

export const currencyOptions = [
  { label: 'Afghan afghani', value: 'AFN' },
  { label: 'Albanian lek', value: 'ALL' },
  { label: 'Armenian dram', value: 'AMD' },
  { label: 'Netherlands Antillean guilder', value: 'ANG' },
  { label: 'Angolan kwanza', value: 'AOA' },
  { label: 'Argentine peso', value: 'ARS' },
  { label: 'Australian dollar', value: 'AUD' },
  { label: 'Aruban florin', value: 'AWG' },
  { label: 'Azerbaijani manat', value: 'AZN' },
  { label: 'Bosnia and Herzegovina convertible mark', value: 'BAM' },
  { label: 'Barbados dollar', value: 'BBD' },
  { label: 'Bangladeshi taka', value: 'BDT' },
  { label: 'Bulgarian lev', value: 'BGN' },
  { label: 'Bahraini dinar', value: 'BHD' },
  { label: 'Burundian franc', value: 'BIF' },
  {
    label: 'Bermudian dollar (customarily known as Bermuda dollar)',
    value: 'BMD',
  },
  { label: 'Brunei dollar', value: 'BND' },
  { label: 'Boliviano', value: 'BOB' },
  { label: 'Bolivian Mvdol (funds code)', value: 'BOV' },
  { label: 'Brazilian real', value: 'BRL' },
  { label: 'Bahamian dollar', value: 'BSD' },
  { label: 'Bhutanese ngultrum', value: 'BTN' },
  { label: 'Botswana pula', value: 'BWP' },
  { label: 'Belarusian ruble', value: 'BYR' },
  { label: 'Belize dollar', value: 'BZD' },
  { label: 'Canadian dollar', value: 'CAD' },
  { label: 'Congolese franc', value: 'CDF' },
  { label: 'WIR Euro (complementary currency)', value: 'CHE' },
  { label: 'Swiss franc', value: 'CHF' },
  { label: 'WIR Franc (complementary currency)', value: 'CHW' },
  { label: 'Unidad de Fomento (funds code)', value: 'CLF' },
  { label: 'Chilean peso', value: 'CLP' },
  { label: 'Chinese yuan', value: 'CNY' },
  { label: 'Colombian peso', value: 'COP' },
  { label: 'Unidad de Valor Real', value: 'COU' },
  { label: 'Costa Rican colon', value: 'CRC' },
  { label: 'Cuban convertible peso', value: 'CUC' },
  { label: 'Cuban peso', value: 'CUP' },
  { label: 'Cape Verde escudo', value: 'CVE' },
  { label: 'Czech koruna', value: 'CZK' },
  { label: 'Djiboutian franc', value: 'DJF' },
  { label: 'Danish krone', value: 'DKK' },
  { label: 'Dominican peso', value: 'DOP' },
  { label: 'Algerian dinar', value: 'DZD' },
  { label: 'Egyptian pound', value: 'EGP' },
  { label: 'Eritrean nakfa', value: 'ERN' },
  { label: 'Ethiopian birr', value: 'ETB' },
  { label: 'Euro', value: 'EUR' },
  { label: 'Fiji dollar', value: 'FJD' },
  { label: 'Falkland Islands pound', value: 'FKP' },
  { label: 'Pound sterling', value: 'GBP' },
  { label: 'Georgian lari', value: 'GEL' },
  { label: 'Ghanaian cedi', value: 'GHS' },
  { label: 'Gibraltar pound', value: 'GIP' },
  { label: 'Gambian dalasi', value: 'GMD' },
  { label: 'Guinean franc', value: 'GNF' },
  { label: 'Guatemalan quetzal', value: 'GTQ' },
  { label: 'Guyanese dollar', value: 'GYD' },
  { label: 'Hong Kong dollar', value: 'HKD' },
  { label: 'Honduran lempira', value: 'HNL' },
  { label: 'Croatian kuna', value: 'HRK' },
  { label: 'Haitian gourde', value: 'HTG' },
  { label: 'Hungarian forint', value: 'HUF' },
  { label: 'Indonesian rupiah', value: 'IDR' },
  { label: 'Israeli new shekel', value: 'ILS' },
  { label: 'Indian rupee', value: 'INR' },
  { label: 'Iraqi dinar', value: 'IQD' },
  { label: 'Iranian rial', value: 'IRR' },
  { label: 'Icelandic króna', value: 'ISK' },
  { label: 'Jamaican dollar', value: 'JMD' },
  { label: 'Jordanian dinar', value: 'JOD' },
  { label: 'Japanese yen', value: 'JPY' },
  { label: 'Kenyan shilling', value: 'KES' },
  { label: 'Kyrgyzstani som', value: 'KGS' },
  { label: 'Cambodian riel', value: 'KHR' },
  { label: 'Comoro franc', value: 'KMF' },
  { label: 'North Korean won', value: 'KPW' },
  { label: 'South Korean won', value: 'KRW' },
  { label: 'Kuwaiti dinar', value: 'KWD' },
  { label: 'Cayman Islands dollar', value: 'KYD' },
  { label: 'Kazakhstani tenge', value: 'KZT' },
  { label: 'Lao kip', value: 'LAK' },
  { label: 'Lebanese pound', value: 'LBP' },
  { label: 'Sri Lankan rupee', value: 'LKR' },
  { label: 'Liberian dollar', value: 'LRD' },
  { label: 'Lesotho loti', value: 'LSL' },
  { label: 'Lithuanian litas', value: 'LTL' },
  { label: 'Latvian lats', value: 'LVL' },
  { label: 'Libyan dinar', value: 'LYD' },
  { label: 'Moroccan dirham', value: 'MAD' },
  { label: 'Moldovan leu', value: 'MDL' },
  { label: 'Malagasy ariary', value: 'MGA' },
  { label: 'Macedonian denar', value: 'MKD' },
  { label: 'Myanmar kyat', value: 'MMK' },
  { label: 'Mongolian tugrik', value: 'MNT' },
  { label: 'Macanese pataca', value: 'MOP' },
  { label: 'Mauritanian ouguiya', value: 'MRU' },
  { label: 'Mauritian rupee', value: 'MUR' },
  { label: 'Maldivian rufiyaa', value: 'MVR' },
  { label: 'Malawian kwacha', value: 'MWK' },
  { label: 'Mexican peso', value: 'MXN' },
  { label: 'Mexican Unidad de Inversion (UDI) (funds code)', value: 'MXV' },
  { label: 'Malaysian ringgit', value: 'MYR' },
  { label: 'Mozambican metical', value: 'MZN' },
  { label: 'Namibian dollar', value: 'NAD' },
  { label: 'Nigerian naira', value: 'NGN' },
  { label: 'Nicaraguan córdoba', value: 'NIO' },
  { label: 'Norwegian krone', value: 'NOK' },
  { label: 'Nepalese rupee', value: 'NPR' },
  { label: 'New Zealand dollar', value: 'NZD' },
  { label: 'Omani rial', value: 'OMR' },
  { label: 'Panamanian balboa', value: 'PAB' },
  { label: 'Peruvian nuevo sol', value: 'PEN' },
  { label: 'Papua New Guinean kina', value: 'PGK' },
  { label: 'Philippine peso', value: 'PHP' },
  { label: 'Pakistani rupee', value: 'PKR' },
  { label: 'Polish złoty', value: 'PLN' },
  { label: 'Paraguayan guaraní', value: 'PYG' },
  { label: 'Qatari riyal', value: 'QAR' },
  { label: 'Romanian leu', value: 'RON' },
  { label: 'Serbian dinar', value: 'RSD' },
  { label: 'Russian ruble', value: 'RUB' },
  { label: 'Rwandan franc', value: 'RWF' },
  { label: 'Saudi riyal', value: 'SAR' },
  { label: 'Solomon Islands dollar', value: 'SBD' },
  { label: 'Seychelles rupee', value: 'SCR' },
  { label: 'Sudanese pound', value: 'SDG' },
  { label: 'Swedish krona/kronor', value: 'SEK' },
  { label: 'Singapore dollar', value: 'SGD' },
  { label: 'Saint Helena pound', value: 'SHP' },
  { label: 'Sierra Leonean leone', value: 'SLL' },
  { label: 'Somali shilling', value: 'SOS' },
  { label: 'Surinamese dollar', value: 'SRD' },
  { label: 'South Sudanese pound', value: 'SSP' },
  { label: 'São Tomé and Príncipe dobra', value: 'STN' },
  { label: 'Salvadoran colón', value: 'SVC' },
  { label: 'Syrian pound', value: 'SYP' },
  { label: 'Swazi lilangeni', value: 'SZL' },
  { label: 'Thai baht', value: 'THB' },
  { label: 'Tajikistani somoni', value: 'TJS' },
  { label: 'Turkmenistan manat', value: 'TMT' },
  { label: 'Tunisian dinar', value: 'TND' },
  { label: 'Tongan paʻanga', value: 'TOP' },
  { label: 'Turkish lira', value: 'TRY' },
  { label: 'Trinidad and Tobago dollar', value: 'TTD' },
  { label: 'New Taiwan dollar', value: 'TWD' },
  { label: 'Tanzanian shilling', value: 'TZS' },
  { label: 'Ukrainian hryvnia', value: 'UAH' },
  { label: 'Ugandan shilling', value: 'UGX' },
  { label: 'United States dollar', value: 'USD' },
  { label: 'Uruguayan peso', value: 'UYU' },
  { label: 'Unidad Previsional', value: 'UYW' },
  { label: 'Uzbekistan som', value: 'UZS' },
  { label: 'Venezuelan bolívar soberano', value: 'VES' },
  { label: 'Vietnamese đồng', value: 'VND' },
  { label: 'Vanuatu vatu', value: 'VUV' },
  { label: 'Samoan tālā', value: 'WST' },
  { label: 'Central African CFA franc', value: 'XAF' },
  { label: 'East Caribbean dollar', value: 'XCD' },
  { label: 'West African CFA franc', value: 'XOF' },
  { label: 'Pacific franc (CFP franc)', value: 'XPF' },
  { label: 'Yemeni rial', value: 'YER' },
  { label: 'South African rand', value: 'ZAR' },
  { label: 'Zambian kwacha', value: 'ZMW' },
  { label: 'Zimbabwean dollar', value: 'ZWL' },
];

const currencyOptionsLabel = {
  AFN: 'Afghan afghani - AFN',
  ALL: 'Albanian lek - ALL',
  AMD: 'Armenian dram - AMD',
  ANG: 'Netherlands Antillean guilder - ANG',
  AOA: 'Angolan kwanza - AOA',
  ARS: 'Argentine peso - ARS',
  AUD: 'Australian dollar - AUD',
  AWG: 'Aruban florin - AWG',
  AZN: 'Azerbaijani manat - AZN',
  BAM: 'Bosnia and Herzegovina convertible mark - BAM',
  BBD: 'Barbados dollar - BBD',
  BDT: 'Bangladeshi taka - BDT',
  BGN: 'Bulgarian lev - BGN',
  BHD: 'Bahraini dinar - BHD',
  BIF: 'Burundian franc - BIF',
  BMD: 'Bermudian dollar (customarily known as Bermuda dollar) - BMD',
  BND: 'Brunei dollar - BND',
  BOB: 'Boliviano - BOB',
  BOV: 'Bolivian Mvdol (funds code) - BOV',
  BRL: 'Brazilian real - BRL',
  BSD: 'Bahamian dollar - BSD',
  BTN: 'Bhutanese ngultrum - BTN',
  BWP: 'Botswana pula - BWP',
  BYR: 'Belarusian ruble - BYR',
  BZD: 'Belize dollar - BZD',
  CAD: 'Canadian dollar - CAD',
  CDF: 'Congolese franc - CDF',
  CHE: 'WIR Euro (complementary currency) - CHE',
  CHF: 'Swiss franc - CHF',
  CHW: 'WIR Franc (complementary currency) - CHW',
  CLF: 'Unidad de Fomento (funds code) - CLF',
  CLP: 'Chilean peso - CLP',
  CNY: 'Chinese yuan - CNY',
  COP: 'Colombian peso - COP',
  COU: 'Unidad de Valor Real - COU',
  CRC: 'Costa Rican colon - CRC',
  CUC: 'Cuban convertible peso - CUC',
  CUP: 'Cuban peso - CUP',
  CVE: 'Cape Verde escudo - CVE',
  CZK: 'Czech koruna - CZK',
  DJF: 'Djiboutian franc - DJF',
  DKK: 'Danish krone - DKK',
  DOP: 'Dominican peso - DOP',
  DZD: 'Algerian dinar - DZD',
  EGP: 'Egyptian pound - EGP',
  ERN: 'Eritrean nakfa - ERN',
  ETB: 'Ethiopian birr - ETB',
  EUR: 'Euro - EUR',
  FJD: 'Fiji dollar - FJD',
  FKP: 'Falkland Islands pound - FKP',
  GBP: 'Pound sterling - GBP',
  GEL: 'Georgian lari - GEL',
  GHS: 'Ghanaian cedi - GHS',
  GIP: 'Gibraltar pound - GIP',
  GMD: 'Gambian dalasi - GMD',
  GNF: 'Guinean franc - GNF',
  GTQ: 'Guatemalan quetzal - GTQ',
  GYD: 'Guyanese dollar - GYD',
  HKD: 'Hong Kong dollar - HKD',
  HNL: 'Honduran lempira - HNL',
  HRK: 'Croatian kuna - HRK',
  HTG: 'Haitian gourde - HTG',
  HUF: 'Hungarian forint - HUF',
  IDR: 'Indonesian rupiah - IDR',
  ILS: 'Israeli new shekel - ILS',
  INR: 'Indian rupee - INR',
  IQD: 'Iraqi dinar - IQD',
  IRR: 'Iranian rial - IRR',
  ISK: 'Icelandic króna - ISK',
  JMD: 'Jamaican dollar - JMD',
  JOD: 'Jordanian dinar - JOD',
  JPY: 'Japanese yen - JPY',
  KES: 'Kenyan shilling - KES',
  KGS: 'Kyrgyzstani som - KGS',
  KHR: 'Cambodian riel - KHR',
  KMF: 'Comoro franc - KMF',
  KPW: 'North Korean won - KPW',
  KRW: 'South Korean won - KRW',
  KWD: 'Kuwaiti dinar - KWD',
  KYD: 'Cayman Islands dollar - KYD',
  KZT: 'Kazakhstani tenge - KZT',
  LAK: 'Lao kip - LAK',
  LBP: 'Lebanese pound - LBP',
  LKR: 'Sri Lankan rupee - LKR',
  LRD: 'Liberian dollar - LRD',
  LSL: 'Lesotho loti - LSL',
  LTL: 'Lithuanian litas - LTL',
  LVL: 'Latvian lats - LVL',
  LYD: 'Libyan dinar - LYD',
  MAD: 'Moroccan dirham - MAD',
  MDL: 'Moldovan leu - MDL',
  MGA: 'Malagasy ariary - MGA',
  MKD: 'Macedonian denar - MKD',
  MMK: 'Myanmar kyat - MMK',
  MNT: 'Mongolian tugrik - MNT',
  MOP: 'Macanese pataca - MOP',
  MRU: 'Mauritanian ouguiya - MRU',
  MUR: 'Mauritian rupee - MUR',
  MVR: 'Maldivian rufiyaa - MVR',
  MWK: 'Malawian kwacha - MWK',
  MXN: 'Mexican peso - MXN',
  MXV: 'Mexican Unidad de Inversion (UDI) (funds code) - MXV',
  MYR: 'Malaysian ringgit - MYR',
  MZN: 'Mozambican metical - MZN',
  NAD: 'Namibian dollar - NAD',
  NGN: 'Nigerian naira - NGN',
  NIO: 'Nicaraguan córdoba - NIO',
  NOK: 'Norwegian krone - NOK',
  NPR: 'Nepalese rupee - NPR',
  NZD: 'New Zealand dollar - NZD',
  OMR: 'Omani rial - OMR',
  PAB: 'Panamanian balboa - PAB',
  PEN: 'Peruvian nuevo sol - PEN',
  PGK: 'Papua New Guinean kina - PGK',
  PHP: 'Philippine peso - PHP',
  PKR: 'Pakistani rupee - PKR',
  PLN: 'Polish złoty - PLN',
  PYG: 'Paraguayan guaraní - PYG',
  QAR: 'Qatari riyal - QAR',
  RON: 'Romanian leu - RON',
  RSD: 'Serbian dinar - RSD',
  RUB: 'Russian ruble - RUB',
  RWF: 'Rwandan franc - RWF',
  SAR: 'Saudi riyal - SAR',
  SBD: 'Solomon Islands dollar - SBD',
  SCR: 'Seychelles rupee - SCR',
  SDG: 'Sudanese pound - SDG',
  SEK: 'Swedish krona/kronor - SEK',
  SGD: 'Singapore dollar - SGD',
  SHP: 'Saint Helena pound - SHP',
  SLL: 'Sierra Leonean leone - SLL',
  SOS: 'Somali shilling - SOS',
  SRD: 'Surinamese dollar - SRD',
  SSP: 'South Sudanese pound - SSP',
  STN: 'São Tomé and Príncipe dobra - STN',
  SVC: 'Salvadoran colón - SVC',
  SYP: 'Syrian pound - SYP',
  SZL: 'Swazi lilangeni - SZL',
  THB: 'Thai baht - THB',
  TJS: 'Tajikistani somoni - TJS',
  TMT: 'Turkmenistan manat - TMT',
  TND: 'Tunisian dinar - TND',
  TOP: 'Tongan paʻanga - TOP',
  TRY: 'Turkish lira - TRY',
  TTD: 'Trinidad and Tobago dollar - TTD',
  TWD: 'New Taiwan dollar - TWD',
  TZS: 'Tanzanian shilling - TZS',
  UAH: 'Ukrainian hryvnia - UAH',
  UGX: 'Ugandan shilling - UGX',
  USD: 'United States dollar - USD',
  UYU: 'Uruguayan peso - UYU',
  UYW: 'Unidad Previsional - UYW',
  UZS: 'Uzbekistan som - UZS',
  VES: 'Venezuelan bolívar soberano - VES',
  VND: 'Vietnamese đồng - VND',
  VUV: 'Vanuatu vatu - VUV',
  WST: 'Samoan tālā - WST',
  XAF: 'Central African CFA franc - XAF',
  XCD: 'East Caribbean dollar - XCD',
  XOF: 'West African CFA franc - XOF',
  XPF: 'Pacific franc (CFP franc) - XPF',
  YER: 'Yemeni rial - YER',
  ZAR: 'South African rand - ZAR',
  ZMW: 'Zambian kwacha - ZMW',
  ZWL: 'Zimbabwean dollar - ZWL',
};

export const getCurrencyOptions = () => {
  return Object.values(Currency).map((value) => ({
    label: currencyOptionsLabel[value],
    value: value,
  }));
};
