package entity

const (
	NodeLabel_TimelineEvent      = "TimelineEvent"
	NodeLabel_Contact            = "Contact"
	NodeLabel_JobRole            = "JobRole"
	NodeLabel_Email              = "Email"
	NodeLabel_InteractionEvent   = "InteractionEvent"
	NodeLabel_InteractionSession = "InteractionSession"
	NodeLabel_Note               = "Note"
	NodeLabel_Organization       = "Organization"
	NodeLabel_Action             = "Action"
	NodeLabel_PageView           = "PageView"
	NodeLabel_PhoneNumber        = "PhoneNumber"
	NodeLabel_Tag                = "Tag"
	NodeLabel_Issue              = "Issue"
	NodeLabel_User               = "User"
	NodeLabel_Analysis           = "Analysis"
	NodeLabel_Attachment         = "Attachment"
	NodeLabel_Meeting            = "Meeting"
	NodeLabel_Social             = "Social"
	NodeLabel_Player             = "Player"
	NodeLabel_HealthIndicator    = "HealthIndicator"
	NodeLabel_Country            = "Country"
	NodeLabel_ActionItem         = "ActionItem"
	NodeLabel_LogEntry           = "LogEntry"
)
