import { cva } from 'class-variance-authority';
export const iconVariant = cva('', {
  variants: {
    size: {
      xs: [],
      sm: [],
      md: [],
      lg: [],
      xl: [],
      '2xl': [],
    },
    variant: {
      solid: [],
      outline: [],
      link: [],
      ghost: [],
    },
    colorScheme: {
      primary: [],
      gray: [],
      warm: [],
      error: [],
      rose: [],
      warning: [],
      blueDark: [],
      teal: [],
      success: [],
      moss: [],
      greenLight: [],
      violet: [],
      fuchsia: [],
    },
  },
  compoundVariants: [
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-700'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-700'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-700'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-700'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-600'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'xl',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-700'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-700'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-700'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-700'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-700'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-700'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-700'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-700'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-700'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-700'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-700'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-700'],
    },
    {
      size: 'xl',
      variant: 'link',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-700'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'warm',
      className: ['w-4 h-4', 'text-warm-600'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'xl',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'warm',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-primary-600'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-gray-600'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'warm',
      className: ['w-6 h-6', 'text-warm-600'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-error-600'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-6 h-6', 'text-rose-600'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-6 h-6', 'text-warning-600'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-6 h-6', 'text-blueDark-600'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-6 h-6', 'text-teal-600'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-success-600'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-6 h-6', 'text-moss-600'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-6 h-6', 'text-greenLight-600'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-6 h-6', 'text-violet-600'],
    },
    {
      size: '2xl',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-6 h-6', 'text-fuchsia-600'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-primary-700'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-gray-700'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'warm',
      className: ['w-6 h-6', 'text-warm-700'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-error-700'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'rose',
      className: ['w-6 h-6', 'text-rose-700'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'warning',
      className: ['w-6 h-6', 'text-warning-700'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'blueDark',
      className: ['w-6 h-6', 'text-blueDark-700'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'teal',
      className: ['w-6 h-6', 'text-teal-700'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-success-700'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'moss',
      className: ['w-6 h-6', 'text-moss-700'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'greenLight',
      className: ['w-6 h-6', 'text-greenLight-700'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'violet',
      className: ['w-6 h-6', 'text-violet-700'],
    },
    {
      size: '2xl',
      variant: 'link',
      colorScheme: 'fuchsia',
      className: ['w-6 h-6', 'text-fuchsia-700'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-primary-600'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-gray-600'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'warm',
      className: ['w-6 h-6', 'text-warm-600'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-error-600'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-6 h-6', 'text-rose-600'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-6 h-6', 'text-warning-600'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-6 h-6', 'text-blueDark-600'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-6 h-6', 'text-teal-600'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-success-600'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-6 h-6', 'text-moss-600'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-6 h-6', 'text-greenLight-600'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-6 h-6', 'text-violet-600'],
    },
    {
      size: '2xl',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-6 h-6', 'text-fuchsia-600'],
    },
  ],
});

export const linkButton = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'gap-2',
    'text-base',
    'font-semibold',
    'shadow-xs',
    'outline-none',
    'transition',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
  ],
  {
    variants: {
      colorScheme: {
        primary: [
          'text-primary-700',
          'hover:text-primary-700',
          'focus:text-primary-700',
          'hover:underline',
          'focus:underline',
        ],
        gray: [
          'text-gray-500',
          'hover:text-gray-700',
          'focus:text-gray-700',
          'hover:underline',
          'focus:underline',
        ],
        warm: [
          'text-warm-700',
          'hover:text-warm-700',
          'focus:text-warm-700',
          'hover:underline',
          'focus:underline',
        ],
        error: [
          'text-error-700',
          'hover:text-error-700',
          'focus:text-error-700',
          'hover:underline',
          'focus:underline',
        ],
        rose: [
          'text-rose-700',
          'hover:text-rose-700',
          'focus:text-rose-700',
          'hover:underline',
          'focus:underline',
        ],
        warning: [
          'text-warning-700',
          'hover:text-warning-700',
          'focus:text-warning-700',
          'hover:underline',
          'focus:underline',
        ],
        blueDark: [
          'text-blueDark-700',
          'hover:text-blueDark-700',
          'focus:text-blueDark-700',
          'hover:underline',
          'focus:underline',
        ],
        teal: [
          'text-teal-700',
          'hover:text-teal-700',
          'focus:text-teal-700',
          'hover:underline',
          'focus:underline',
        ],
        success: [
          'text-success-700',
          'hover:text-success-700',
          'focus:text-success-700',
          'hover:underline',
          'focus:underline',
        ],
        moss: [
          'text-moss-700',
          'hover:text-moss-700',
          'focus:text-moss-700',
          'hover:underline',
          'focus:underline',
        ],
        greenLight: [
          'text-greenLight-700',
          'hover:text-greenLight-700',
          'focus:text-greenLight-700',
          'hover:underline',
          'focus:underline',
        ],
        violet: [
          'text-violet-700',
          'hover:text-violet-700',
          'focus:text-violet-700',
          'hover:underline',
          'focus:underline',
        ],
        fuchsia: [
          'text-fuchsia-700',
          'hover:text-fuchsia-700',
          'focus:text-fuchsia-700',
          'hover:underline',
          'focus:underline',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'primary',
    },
  },
);

export const solidButton = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'gap-2',
    'text-base',
    'font-semibold',
    'shadow-xs',
    'outline-none',
    'transition',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
  ],
  {
    variants: {
      colorScheme: {
        primary: [
          'text-white',
          'border',
          'border-solid',
          'bg-primary-600',
          'hover:bg-primary-700',
          'focus:bg-primary-700',
          'border-primary-600',
          'hover:border-primary-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        gray: [
          'text-white',
          'border',
          'border-solid',
          'bg-gray-600',
          'hover:bg-gray-700',
          'focus:bg-gray-700',
          'border-gray-600',
          'hover:border-gray-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        warm: [
          'text-white',
          'border',
          'border-solid',
          'bg-warm-600',
          'hover:bg-warm-700',
          'focus:bg-warm-700',
          'border-warm-600',
          'hover:border-warm-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        error: [
          'text-white',
          'border',
          'border-solid',
          'bg-error-600',
          'hover:bg-error-700',
          'focus:bg-error-700',
          'border-error-600',
          'hover:border-error-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        rose: [
          'text-white',
          'border',
          'border-solid',
          'bg-rose-600',
          'hover:bg-rose-700',
          'focus:bg-rose-700',
          'border-rose-600',
          'hover:border-rose-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        warning: [
          'text-white',
          'border',
          'border-solid',
          'bg-warning-600',
          'hover:bg-warning-700',
          'focus:bg-warning-700',
          'border-warning-600',
          'hover:border-warning-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        blueDark: [
          'text-white',
          'border',
          'border-solid',
          'bg-blueDark-600',
          'hover:bg-blueDark-700',
          'focus:bg-blueDark-700',
          'border-blueDark-600',
          'hover:border-blueDark-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        teal: [
          'text-white',
          'border',
          'border-solid',
          'bg-teal-600',
          'hover:bg-teal-700',
          'focus:bg-teal-700',
          'border-teal-600',
          'hover:border-teal-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        success: [
          'text-white',
          'border',
          'border-solid',
          'bg-success-600',
          'hover:bg-success-700',
          'focus:bg-success-700',
          'border-success-600',
          'hover:border-success-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        moss: [
          'text-white',
          'border',
          'border-solid',
          'bg-moss-600',
          'hover:bg-moss-700',
          'focus:bg-moss-700',
          'border-moss-600',
          'hover:border-moss-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        greenLight: [
          'text-white',
          'border',
          'border-solid',
          'bg-greenLight-600',
          'hover:bg-greenLight-700',
          'focus:bg-greenLight-700',
          'border-greenLight-600',
          'hover:border-greenLight-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        violet: [
          'text-white',
          'border',
          'border-solid',
          'bg-violet-600',
          'hover:bg-violet-700',
          'focus:bg-violet-700',
          'border-violet-600',
          'hover:border-violet-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        fuchsia: [
          'text-white',
          'border',
          'border-solid',
          'bg-fuchsia-600',
          'hover:bg-fuchsia-700',
          'focus:bg-fuchsia-700',
          'border-fuchsia-600',
          'hover:border-fuchsia-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'primary',
    },
  },
);

export const ghostButton = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'gap-2',
    'text-base',
    'font-semibold',
    'shadow-xs',
    'outline-none',
    'transition',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
  ],
  {
    variants: {
      colorScheme: {
        primary: [
          'bg-transparent',
          'text-primary-500',
          'shadow-none',
          'hover:text-primary-700',
          'focus:text-primary-700',
          'hover:bg-primary-50',
          'focus:bg-primary-50',
        ],
        gray: [
          'bg-transparent',
          'shadow-none',
          'text-gray-500',
          'hover:text-gray-700',
          'focus:text-gray-700',
          'hover:bg-gray-50',
          'focus:bg-gray-50',
        ],
        warm: [
          'bg-transparent',
          'text-warm-500',
          'shadow-none',
          'hover:text-warm-700',
          'focus:text-warm-700',
          'hover:bg-warm-50',
          'focus:bg-warm-50',
        ],
        error: [
          'bg-transparent',
          'text-error-500',
          'shadow-none',
          'hover:text-error-700',
          'focus:text-error-700',
          'hover:bg-error-50',
          'focus:bg-error-50',
        ],
        rose: [
          'bg-transparent',
          'text-rose-500',
          'shadow-none',
          'hover:text-rose-700',
          'focus:text-rose-700',
          'hover:bg-rose-50',
          'focus:bg-rose-50',
        ],
        warning: [
          'bg-transparent',
          'text-warning-500',
          'shadow-none',
          'hover:text-warning-700',
          'focus:text-warning-700',
          'hover:bg-warning-50',
          'focus:bg-warning-50',
        ],
        blueDark: [
          'bg-transparent',
          'text-blueDark-500',
          'shadow-none',
          'hover:text-blueDark-700',
          'focus:text-blueDark-700',
          'hover:bg-blueDark-50',
          'focus:bg-blueDark-50',
        ],
        teal: [
          'bg-transparent',
          'text-teal-500',
          'shadow-none',
          'hover:text-teal-700',
          'focus:text-teal-700',
          'hover:bg-teal-50',
          'focus:bg-teal-50',
        ],
        success: [
          'bg-transparent',
          'text-success-500',
          'shadow-none',
          'hover:text-success-700',
          'focus:text-success-700',
          'hover:bg-success-50',
          'focus:bg-success-50',
        ],
        moss: [
          'bg-transparent',
          'text-moss-500',
          'shadow-none',
          'hover:text-moss-700',
          'focus:text-moss-700',
          'hover:bg-moss-50',
          'focus:bg-moss-50',
        ],
        greenLight: [
          'bg-transparent',
          'text-greenLight-500',
          'shadow-none',
          'hover:text-greenLight-700',
          'focus:text-greenLight-700',
          'hover:bg-greenLight-50',
          'focus:bg-greenLight-50',
        ],
        violet: [
          'bg-transparent',
          'text-violet-500',
          'shadow-none',
          'hover:text-violet-700',
          'focus:text-violet-700',
          'hover:bg-violet-50',
          'focus:bg-violet-50',
        ],
        fuchsia: [
          'bg-transparent',
          'text-fuchsia-500',
          'shadow-none',
          'hover:text-fuchsia-700',
          'focus:text-fuchsia-700',
          'hover:bg-fuchsia-50',
          'focus:bg-fuchsia-50',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'primary',
    },
  },
);

export const outlineButton = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'gap-2',
    'text-base',
    'font-semibold',
    'shadow-xs',
    'outline-none',
    'transition',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
  ],
  {
    variants: {
      colorScheme: {
        primary: [
          'bg-primary-50',
          'text-primary-700',
          'border',
          'border-solid',
          'border-primary-300',
          'hover:bg-primary-100',
          'hover:text-primary-700',
          'focus:bg-primary-100',
        ],
        gray: [
          'text-gray-700',
          'border',
          'border-solid',
          'border-gray-300',
          'hover:bg-gray-50',
          'hover:text-gray-700',
          'focus:bg-gray-50',
        ],
        warm: [
          'bg-warm-50',
          'text-warm-700',
          'border',
          'border-solid',
          'border-warm-300',
          'hover:bg-warm-100',
          'hover:text-warm-700',
          'focus:bg-warm-100',
        ],
        error: [
          'bg-error-50',
          'text-error-700',
          'border',
          'border-solid',
          'border-error-300',
          'hover:bg-error-100',
          'hover:text-error-700',
          'focus:bg-error-100',
        ],
        rose: [
          'bg-rose-50',
          'text-rose-700',
          'border',
          'border-solid',
          'border-rose-300',
          'hover:bg-rose-100',
          'hover:text-rose-700',
          'focus:bg-rose-100',
        ],
        warning: [
          'bg-warning-50',
          'text-warning-700',
          'border',
          'border-solid',
          'border-warning-300',
          'hover:bg-warning-100',
          'hover:text-warning-700',
          'focus:bg-warning-100',
        ],
        blueDark: [
          'bg-blueDark-50',
          'text-blueDark-700',
          'border',
          'border-solid',
          'border-blueDark-300',
          'hover:bg-blueDark-100',
          'hover:text-blueDark-700',
          'focus:bg-blueDark-100',
        ],
        teal: [
          'bg-teal-50',
          'text-teal-700',
          'border',
          'border-solid',
          'border-teal-300',
          'hover:bg-teal-100',
          'hover:text-teal-700',
          'focus:bg-teal-100',
        ],
        success: [
          'bg-success-50',
          'text-success-700',
          'border',
          'border-solid',
          'border-success-300',
          'hover:bg-success-100',
          'hover:text-success-700',
          'focus:bg-success-100',
        ],
        moss: [
          'bg-moss-50',
          'text-moss-700',
          'border',
          'border-solid',
          'border-moss-300',
          'hover:bg-moss-100',
          'hover:text-moss-700',
          'focus:bg-moss-100',
        ],
        greenLight: [
          'bg-greenLight-50',
          'text-greenLight-700',
          'border',
          'border-solid',
          'border-greenLight-300',
          'hover:bg-greenLight-100',
          'hover:text-greenLight-700',
          'focus:bg-greenLight-100',
        ],
        violet: [
          'bg-violet-50',
          'text-violet-700',
          'border',
          'border-solid',
          'border-violet-300',
          'hover:bg-violet-100',
          'hover:text-violet-700',
          'focus:bg-violet-100',
        ],
        fuchsia: [
          'bg-fuchsia-50',
          'text-fuchsia-700',
          'border',
          'border-solid',
          'border-fuchsia-300',
          'hover:bg-fuchsia-100',
          'hover:text-fuchsia-700',
          'focus:bg-fuchsia-100',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'primary',
    },
  },
);
