serviceName: event-processing-platform
grpc:
  port: :5001
  development: true
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8001
  checkIntervalSeconds: 10
logger:
  level: debug
  devMode: false
  encoder: console
jaeger:
  enable: true
  serviceName: event-processing-platform
  hostPort: "localhost:6831"
  logSpans: false
eventStoreConfig:
  connectionString: "esdb://localhost:2113?tls=false"
subscriptions:
  poolSize: 60
  allPrefixes: ""
  phoneNumberPrefix: "phone_number-"
  contactPrefix: "contact-"
  organizationPrefix: "organization-"
  emailPrefix: "email-"
  userPrefix: "user-"
  graphProjectionGroupName: "projection-graph-v1"
  emailValidationProjectionGroupName: "projection-emailValidation-v1"
neo4j:
  target: neo4j://127.0.0.1:7687
  user: neo4j
  password: StrongLocalPa$$
  maxConnectionPoolSize: 100
  connectionAcquisitionTimeoutSec: 60
  logLevel: INFO
services:
  validationApi: http://localhost:10003/
  validationApiKey: