serviceName: event-processing-platform
grpc:
  port: :5001
  development: true
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8001
  checkIntervalSeconds: 10
logger:
  level: debug
  devMode: false
  encoder: console
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbName: products
  sslMode: false
jaeger:
  enable: true
  serviceName: event-processing-platform
  hostPort: "localhost:6831"
  logSpans: false
eventStoreConfig:
  connectionString: "esdb://localhost:2113?tls=false"
subscriptions:
  poolSize: 60
  phoneNumberPrefix: "phone_number-"
  graphProjectionGroupName: "graph1"
  dataEnricherProjectionGroupName: "dataEnricher1"
neo4j:
  target: neo4j://127.0.0.1:7687
  user: neo4j
  password: StrongLocalPa$$
  maxConnectionPoolSize: 100
  connectionAcquisitionTimeoutSec: 60
  logLevel: INFO