apiVersion: v1
kind: Service
metadata:
  name: validation-api-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 10003
      targetPort: 10003
  selector:
    app: validation-api
