package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	"github.com/openline-ai/openline-customer-os/packages/server/customer-os-api-sdk/graph/model"
)

// BillingProfileCreate is the resolver for the billingProfile_Create field.
func (r *mutationResolver) BillingProfileCreate(ctx context.Context, input model.BillingProfileInput) (string, error) {
	panic(fmt.Errorf("not implemented: BillingProfileCreate - billingProfile_Create"))
}

// BillingProfileUpdate is the resolver for the billingProfile_Update field.
func (r *mutationResolver) BillingProfileUpdate(ctx context.Context, input model.BillingProfileUpdateInput) (string, error) {
	panic(fmt.Errorf("not implemented: BillingProfileUpdate - billingProfile_Update"))
}

// BillingProfileLinkEmail is the resolver for the billingProfile_LinkEmail field.
func (r *mutationResolver) BillingProfileLinkEmail(ctx context.Context, input model.BillingProfileLinkEmailInput) (string, error) {
	panic(fmt.Errorf("not implemented: BillingProfileLinkEmail - billingProfile_LinkEmail"))
}

// BillingProfileUnlinkEmail is the resolver for the billingProfile_UnlinkEmail field.
func (r *mutationResolver) BillingProfileUnlinkEmail(ctx context.Context, input model.BillingProfileLinkEmailInput) (string, error) {
	panic(fmt.Errorf("not implemented: BillingProfileUnlinkEmail - billingProfile_UnlinkEmail"))
}

// BillingProfileLinkLocation is the resolver for the billingProfile_LinkLocation field.
func (r *mutationResolver) BillingProfileLinkLocation(ctx context.Context, input model.BillingProfileLinkLocationInput) (string, error) {
	panic(fmt.Errorf("not implemented: BillingProfileLinkLocation - billingProfile_LinkLocation"))
}

// BillingProfileUnlinkLocation is the resolver for the billingProfile_UnlinkLocation field.
func (r *mutationResolver) BillingProfileUnlinkLocation(ctx context.Context, input model.BillingProfileLinkLocationInput) (string, error) {
	panic(fmt.Errorf("not implemented: BillingProfileUnlinkLocation - billingProfile_UnlinkLocation"))
}
