package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/openline-ai/openline-customer-os/packages/server/customer-os-api-sdk/graph/model"
)

// CustomFieldTemplateSave is the resolver for the customFieldTemplate_Save field.
func (r *mutationResolver) CustomFieldTemplateSave(ctx context.Context, input model.CustomFieldTemplateInput) (*model.CustomFieldTemplate, error) {
	panic(fmt.Errorf("not implemented: CustomFieldTemplateSave - customFieldTemplate_Save"))
}

// CustomFieldTemplateDelete is the resolver for the customFieldTemplate_Delete field.
func (r *mutationResolver) CustomFieldTemplateDelete(ctx context.Context, id string) (*bool, error) {
	panic(fmt.Errorf("not implemented: CustomFieldTemplateDelete - customFieldTemplate_Delete"))
}

// CustomFieldTemplateList is the resolver for the customFieldTemplate_List field.
func (r *queryResolver) CustomFieldTemplateList(ctx context.Context) ([]*model.CustomFieldTemplate, error) {
	panic(fmt.Errorf("not implemented: CustomFieldTemplateList - customFieldTemplate_List"))
}
