package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	"github.com/openline-ai/openline-customer-os/packages/server/customer-os-api-sdk/graph/model"
)

// InvoicingCycleCreate is the resolver for the invoicingCycle_Create field.
func (r *mutationResolver) InvoicingCycleCreate(ctx context.Context, input model.InvoicingCycleInput) (*model.InvoicingCycle, error) {
	panic(fmt.Errorf("not implemented: InvoicingCycleCreate - invoicingCycle_Create"))
}

// InvoicingCycleUpdate is the resolver for the invoicingCycle_Update field.
func (r *mutationResolver) InvoicingCycleUpdate(ctx context.Context, input model.InvoicingCycleUpdateInput) (*model.InvoicingCycle, error) {
	panic(fmt.Errorf("not implemented: InvoicingCycleUpdate - invoicingCycle_Update"))
}

// InvoicingCycle is the resolver for the invoicingCycle field.
func (r *queryResolver) InvoicingCycle(ctx context.Context) (*model.InvoicingCycle, error) {
	panic(fmt.Errorf("not implemented: InvoicingCycle - invoicingCycle"))
}
