import { cva } from 'class-variance-authority';

export const tagSubtleVariant = cva(
  ['w-fit', 'flex', 'items-center', 'rounded-[4px]', 'leading-none'],
  {
    variants: {
      colorScheme: {
        primary: ['text-primary-700', 'bg-primary-100'],
        gray: ['text-gray-700', 'bg-gray-100'],
        grayBlue: ['text-grayBlue-700', 'bg-grayBlue-100'],
        grayModern: ['text-grayModern-700', 'bg-grayModern-100'],
        grayWarm: ['text-grayWarm-700', 'bg-grayWarm-100'],
        error: ['text-error-700', 'bg-error-100'],
        rose: ['text-rose-700', 'bg-rose-100'],
        warning: ['text-warning-700', 'bg-warning-100'],
        yellow: ['text-yellow-700', 'bg-yellow-100'],
        blueDark: ['text-blueDark-700', 'bg-blueDark-100'],
        indigo: ['text-indigo-700', 'bg-indigo-100'],
        teal: ['text-teal-700', 'bg-teal-100'],
        success: ['text-success-700', 'bg-success-100'],
        blue: ['text-blue-700', 'bg-blue-100'],
        blueLight: ['text-blueLight-700', 'bg-blueLight-100'],
        moss: ['text-moss-700', 'bg-moss-100'],
        greenLight: ['text-greenLight-700', 'bg-greenLight-100'],
        violet: ['text-violet-700', 'bg-violet-100'],
        fuchsia: ['text-fuchsia-700', 'bg-fuchsia-100'],
        orangeDark: ['text-orangeDark-700', 'bg-orangeDark-100'],
        purple: ['text-purple-700', 'bg-purple-100'],
        cyan: ['text-cyan-700', 'bg-cyan-100'],
        pink: ['text-pink-700', 'bg-pink-100'],
      },
    },
    defaultVariants: {
      colorScheme: 'gray',
    },
  },
);

export const tagSolidVariant = cva(
  ['w-fit', 'flex', 'items-center', 'rounded-[4px]', 'leading-none'],
  {
    variants: {
      colorScheme: {
        primary: ['bg-primary-500', 'text-white'],
        gray: ['bg-gray-500', 'text-white'],
        grayBlue: ['bg-grayBlue-500', 'text-white'],
        grayModern: ['bg-grayModern-500', 'text-white'],
        grayWarm: ['bg-grayWarm-500', 'text-white'],
        error: ['bg-error-500', 'text-white'],
        rose: ['bg-rose-500', 'text-white'],
        warning: ['bg-warning-500', 'text-white'],
        yellow: ['bg-yellow-500', 'text-white'],
        blueDark: ['bg-blueDark-500', 'text-white'],
        indigo: ['bg-indigo-500', 'text-white'],
        teal: ['bg-teal-500', 'text-white'],
        success: ['bg-success-500', 'text-white'],
        blue: ['bg-blue-500', 'text-white'],
        blueLight: ['bg-blueLight-500', 'text-white'],
        moss: ['bg-moss-500', 'text-white'],
        greenLight: ['bg-greenLight-500', 'text-white'],
        violet: ['bg-violet-500', 'text-white'],
        fuchsia: ['bg-fuchsia-500', 'text-white'],
        orangeDark: ['bg-orangeDark-500', 'text-white'],
        purple: ['bg-purple-500', 'text-white'],
        cyan: ['bg-cyan-500', 'text-white'],
        pink: ['bg-pink-500', 'text-white'],
      },
    },
    defaultVariants: {
      colorScheme: 'gray',
    },
  },
);

export const tagOutlineVariant = cva(
  ['w-fit', 'flex', 'items-center', 'rounded-[4px]', 'leading-none'],
  {
    variants: {
      colorScheme: {
        primary: [
          'bg-primary-50',
          'text-primary-700',
          'border',
          'border-solid',
          'border-primary-200',
        ],
        gray: [
          'bg-gray-50',
          'text-gray-700',
          'border',
          'border-solid',
          'border-gray-200',
        ],
        grayBlue: [
          'bg-grayBlue-50',
          'text-grayBlue-700',
          'border',
          'border-solid',
          'border-grayBlue-200',
        ],
        grayModern: [
          'bg-grayModern-50',
          'text-grayModern-700',
          'border',
          'border-solid',
          'border-grayModern-200',
        ],
        grayWarm: [
          'bg-grayWarm-50',
          'text-grayWarm-700',
          'border',
          'border-solid',
          'border-grayWarm-200',
        ],
        error: [
          'bg-error-50',
          'text-error-700',
          'border',
          'border-solid',
          'border-error-200',
        ],
        rose: [
          'bg-rose-50',
          'text-rose-700',
          'border',
          'border-solid',
          'border-rose-200',
        ],
        warning: [
          'bg-warning-50',
          'text-warning-700',
          'border',
          'border-solid',
          'border-warning-200',
        ],
        yellow: [
          'bg-yellow-50',
          'text-yellow-700',
          'border',
          'border-solid',
          'border-yellow-200',
        ],
        blueDark: [
          'bg-blueDark-50',
          'text-blueDark-700',
          'border',
          'border-solid',
          'border-blueDark-200',
        ],
        indigo: [
          'bg-indigo-50',
          'text-indigo-700',
          'border',
          'border-solid',
          'border-indigo-200',
        ],
        teal: [
          'bg-teal-50',
          'text-teal-700',
          'border',
          'border-solid',
          'border-teal-200',
        ],
        success: [
          'bg-success-50',
          'text-success-700',
          'border',
          'border-solid',
          'border-success-200',
        ],
        blue: [
          'bg-blue-50',
          'text-blue-700',
          'border',
          'border-solid',
          'border-blue-200',
        ],
        blueLight: [
          'bg-blueLight-50',
          'text-blueLight-700',
          'border',
          'border-solid',
          'border-blueLight-200',
        ],
        moss: [
          'bg-moss-50',
          'text-moss-700',
          'border',
          'border-solid',
          'border-moss-200',
        ],
        greenLight: [
          'bg-greenLight-50',
          'text-greenLight-700',
          'border',
          'border-solid',
          'border-greenLight-200',
        ],
        violet: [
          'bg-violet-50',
          'text-violet-700',
          'border',
          'border-solid',
          'border-violet-200',
        ],
        fuchsia: [
          'bg-fuchsia-50',
          'text-fuchsia-700',
          'border',
          'border-solid',
          'border-fuchsia-200',
        ],
        orangeDark: [
          'bg-orangeDark-50',
          'text-orangeDark-700',
          'border',
          'border-solid',
          'border-orangeDark-200',
        ],
        purple: [
          'bg-purple-50',
          'text-purple-700',
          'border',
          'border-solid',
          'border-purple-200',
        ],
        cyan: [
          'bg-cyan-50',
          'text-cyan-700',
          'border',
          'border-solid',
          'border-cyan-200',
        ],
        pink: [
          'bg-pink-50',
          'text-pink-700',
          'border',
          'border-solid',
          'border-pink-200',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'gray',
    },
  },
);

export const tagCloseButtonVariant = cva([], {
  variants: {
    colorScheme: {
      primary: [
        'text-primary-400',
        'mr-0',
        'bg-primary-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-primary-200',
        'hover:text-primary-500',
      ],
      gray: [
        'text-gray-400',
        'mr-0',
        'bg-gray-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-gray-200',
        'hover:text-gray-500',
      ],
      grayBlue: [
        'text-grayBlue-400',
        'mr-0',
        'bg-grayBlue-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-grayBlue-200',
        'hover:text-grayBlue-500',
      ],
      grayModern: [
        'text-grayModern-400',
        'mr-0',
        'bg-grayModern-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-grayModern-200',
        'hover:text-grayModern-500',
      ],
      grayWarm: [
        'text-grayWarm-400',
        'mr-0',
        'bg-grayWarm-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-grayWarm-200',
        'hover:text-grayWarm-500',
      ],
      error: [
        'text-error-400',
        'mr-0',
        'bg-error-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-error-200',
        'hover:text-error-500',
      ],
      rose: [
        'text-rose-400',
        'mr-0',
        'bg-rose-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-rose-200',
        'hover:text-rose-500',
      ],
      warning: [
        'text-warning-400',
        'mr-0',
        'bg-warning-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-warning-200',
        'hover:text-warning-500',
      ],
      yellow: [
        'text-yellow-400',
        'mr-0',
        'bg-yellow-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-yellow-200',
        'hover:text-yellow-500',
      ],
      blueDark: [
        'text-blueDark-400',
        'mr-0',
        'bg-blueDark-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-blueDark-200',
        'hover:text-blueDark-500',
      ],
      indigo: [
        'text-indigo-400',
        'mr-0',
        'bg-indigo-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-indigo-200',
        'hover:text-indigo-500',
      ],
      teal: [
        'text-teal-400',
        'mr-0',
        'bg-teal-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-teal-200',
        'hover:text-teal-500',
      ],
      success: [
        'text-success-400',
        'mr-0',
        'bg-success-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-success-200',
        'hover:text-success-500',
      ],
      blue: [
        'text-blue-400',
        'mr-0',
        'bg-blue-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-blue-200',
        'hover:text-blue-500',
      ],
      blueLight: [
        'text-blueLight-400',
        'mr-0',
        'bg-blueLight-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-blueLight-200',
        'hover:text-blueLight-500',
      ],
      moss: [
        'text-moss-400',
        'mr-0',
        'bg-moss-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-moss-200',
        'hover:text-moss-500',
      ],
      greenLight: [
        'text-greenLight-400',
        'mr-0',
        'bg-greenLight-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-greenLight-200',
        'hover:text-greenLight-500',
      ],
      violet: [
        'text-violet-400',
        'mr-0',
        'bg-violet-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-violet-200',
        'hover:text-violet-500',
      ],
      fuchsia: [
        'text-fuchsia-400',
        'mr-0',
        'bg-fuchsia-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-fuchsia-200',
        'hover:text-fuchsia-500',
      ],
      orangeDark: [
        'text-orangeDark-400',
        'mr-0',
        'bg-orangeDark-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-orangeDark-200',
        'hover:text-orangeDark-500',
      ],
      purple: [
        'text-purple-400',
        'mr-0',
        'bg-purple-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-purple-200',
        'hover:text-purple-500',
      ],
      cyan: [
        'text-cyan-400',
        'mr-0',
        'bg-cyan-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-cyan-200',
        'hover:text-cyan-500',
      ],
      pink: [
        'text-pink-400',
        'mr-0',
        'bg-pink-100',
        'rounded-e-md',
        'px-0.5',
        'hover:bg-pink-200',
        'hover:text-pink-500',
      ],
    },
  },
  defaultVariants: {
    colorScheme: 'gray',
  },
});

export const tagSizeVariant = cva('', {
  variants: {
    size: {
      sm: 'px-1 text-xs',
      md: 'px-1 text-sm',
      lg: 'px-3 text-base',
    },
  },
  defaultVariants: {
    size: 'md',
  },
});
