package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	"time"

	"github.com/openline-ai/openline-customer-os/packages/server/customer-os-api/graph/model"
)

// AgentSave is the resolver for the agent_Save field.
func (r *mutationResolver) AgentSave(ctx context.Context, input model.AgentSaveInput) (*model.Agent, error) {
	panic(fmt.Errorf("not implemented: AgentSave - agent_Save"))
}

// Agents is the resolver for the agents field.
func (r *queryResolver) Agents(ctx context.Context) ([]*model.Agent, error) {
	return []*model.Agent{}, nil
}

// Agent is the resolver for the agent field.
func (r *queryResolver) Agent(ctx context.Context, id string) (*model.Agent, error) {
	flowId := "123"
	print(ctx)

	return &model.Agent{
		ID:           "1",
		Type:         "aent",
		Tenant:       "tenant",
		Name:         "Agent 1",
		Capabilities: []*model.Capability{},
		Goal:         "Goal 1",
		IsActive:     true,
		FlowID:       &flowId,
		Visible:      true,
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
		Error:        nil,
		Color:        "green",
		Icon:         "Building01",
		Status:       "OFF",
	}, nil
}
