package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.60

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/openline-ai/openline-customer-os/packages/server/customer-os-api/graph/model"
	"github.com/openline-ai/openline-customer-os/packages/server/customer-os-api/tracing"
	"github.com/openline-ai/openline-customer-os/packages/server/customer-os-common-module/common"
	"github.com/openline-ai/openline-customer-os/packages/server/customer-os-common-module/utils"
	postgresentity "github.com/openline-ai/openline-customer-os/packages/server/customer-os-postgres-repository/entity"
)

// GlobalOrganizationsSearch is the resolver for the globalOrganizations_Search field.
func (r *queryResolver) GlobalOrganizationsSearch(ctx context.Context, searchTerm string, limit int) ([]*model.GlobalOrganization, error) {
	ctx, span := tracing.StartGraphQLTracerSpan(ctx, "MutationResolver.OrganizationSaveByGlobalOrganization", graphql.GetOperationContext(ctx))
	defer span.Finish()
	tracing.SetDefaultResolverSpanTags(ctx, span)
	tracing.LogObjectAsJson(span, "request.searchTern", searchTerm)

	var globalOrganizationEntities []*postgresentity.GlobalOrganization
	var err error

	if searchTerm == "" {
		globalOrganizationEntities, err = r.Services.CommonServices.PostgresRepositories.GlobalOrganizationRepository.GetByPrimaryDomains(ctx, r.cfg.AppConfig.DefaultGlobalOrgPrimaryDomainsInSearch)
		if err != nil {
			tracing.TraceErr(span, err)
			graphql.AddErrorf(ctx, "Failed to get default global organizations")
			return nil, err
		}
	} else {
		if limit == 0 {
			limit = 100
		}
		globalOrganizationEntities, err = r.Services.CommonServices.PostgresRepositories.GlobalOrganizationRepository.Search(ctx, searchTerm, limit)
		if err != nil {
			tracing.TraceErr(span, err)
			graphql.AddErrorf(ctx, "Failed to search global organizations")
			return nil, err
		}
	}

	// get tenant org ids for primary domains
	var primaryDomains []string
	for _, globalOrganizationEntity := range globalOrganizationEntities {
		primaryDomains = append(primaryDomains, globalOrganizationEntity.PrimaryDomain)
	}
	orgByDomainMap, err := r.Services.CommonServices.Neo4jRepositories.OrganizationReadRepository.GetActiveOrganizationIdsByDomain(ctx, common.GetTenantFromContext(ctx), primaryDomains)
	if err != nil {
		tracing.TraceErr(span, err)
	}

	globalOrganizations := make([]*model.GlobalOrganization, 0, len(globalOrganizationEntities))
	for _, globalOrganizationEntity := range globalOrganizationEntities {
		globalOrganization := model.GlobalOrganization{
			ID:            int64(globalOrganizationEntity.ID),
			Name:          globalOrganizationEntity.Name,
			PrimaryDomain: globalOrganizationEntity.PrimaryDomain,
			Website:       globalOrganizationEntity.Website,
			IconURL:       globalOrganizationEntity.IconUrl,
			LogoURL:       globalOrganizationEntity.LogoUrl,
			Domains:       utils.StringToSlice(globalOrganizationEntity.OtherDomains),
		}
		if orgId, ok := orgByDomainMap[globalOrganizationEntity.PrimaryDomain]; ok {
			globalOrganization.OrganizationID = utils.StringPtr(orgId)
		}

		globalOrganizations = append(globalOrganizations, &globalOrganization)
	}

	return globalOrganizations, nil
}
