package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"
	"strings"

	"github.com/99designs/gqlgen/graphql"
	"github.com/openline-ai/openline-customer-os/packages/server/customer-os-api/graph/model"
	"github.com/openline-ai/openline-customer-os/packages/server/customer-os-api/tracing"
)

// MailstackBuyDomainWithMailboxes is the resolver for the mailstack_BuyDomainWithMailboxes field.
func (r *mutationResolver) MailstackBuyDomainWithMailboxes(ctx context.Context, domains []string, usernames []string) ([]string, error) {
	panic(fmt.Errorf("not implemented: MailstackBuyDomainWithMailboxes - mailstack_BuyDomainWithMailboxes"))
}

// MailstackSetUser is the resolver for the mailstack_SetUser field.
func (r *mutationResolver) MailstackSetUser(ctx context.Context, mailbox string, userID string) (*model.Mailbox, error) {
	panic(fmt.Errorf("not implemented: MailstackSetUser - mailstack_SetUser"))
}

// MailstackDomainPurchaseSuggestions is the resolver for the mailstack_DomainPurchaseSuggestions field.
func (r *queryResolver) MailstackDomainPurchaseSuggestions(ctx context.Context, domain string) ([]string, error) {
	ctx, span := tracing.StartGraphQLTracerSpan(ctx, "QueryResolver.MailstackDomainPurchaseSuggestions", graphql.GetOperationContext(ctx))
	defer span.Finish()
	tracing.SetDefaultResolverSpanTags(ctx, span)
	span.LogKV("request.domain", domain)

	if strings.Contains(domain, ".") {
		domain = strings.Split(domain, ".")[0]
	}

	return r.Services.CommonServices.MailboxService.RecommendOutboundDomains(ctx, domain, 100), nil
}

// MailstackDomains is the resolver for the mailstack_Domains field.
func (r *queryResolver) MailstackDomains(ctx context.Context) ([]string, error) {
	panic(fmt.Errorf("not implemented: MailstackDomains - mailstack_Domains"))
	//query
}

// MailstackCheckUnavailableDomains is the resolver for the mailstack_CheckUnavailableDomains field.
func (r *queryResolver) MailstackCheckUnavailableDomains(ctx context.Context, domain []string) ([]string, error) {
	panic(fmt.Errorf("not implemented: MailstackCheckUnavailableDomains - mailstack_CheckUnavailableDomains"))
}

// MailstackUniqueUsernames is the resolver for the mailstack_UniqueUsernames field.
func (r *queryResolver) MailstackUniqueUsernames(ctx context.Context) ([]string, error) {
	panic(fmt.Errorf("not implemented: MailstackUniqueUsernames - mailstack_UniqueUsernames"))
}

// MailstackMailboxes is the resolver for the mailstack_Mailboxes field.
func (r *queryResolver) MailstackMailboxes(ctx context.Context) ([]*model.Mailbox, error) {
	panic(fmt.Errorf("not implemented: MailstackMailboxes - mailstack_Mailboxes"))
}
