import { DataSource } from '@spaces/graphql';

export const emptyLocation = {
  id: '',
  createdAt: '',
  updatedAt: '',
  source: DataSource.Openline,
  sourceOfTruth: DataSource.Openline,
  appSource: '',
  name: '',
  rawAddress: '',
  country: '',
  region: '',
  district: '',
  locality: '',
  street: '',
  address: '',
  address2: '',
  zip: '',
  addressType: '',
  houseNumber: '',
  postalCode: '',
  plusFour: '',
  commercial: '',
  predirection: '',
  latitude: '',
  longitude: '',
  timeZone: '',
  utcOffset: '',
};
