export { useAddEmailToContactEmail } from '../useContactEmail/useAddContactEmail';
export { useRemoveEmailFromContactEmail } from '../useContactEmail/useDeleteContactEmail';
export { useUpdateContactEmail } from '../useContactEmail/useUpdateContactEmail';
export { useAddTagToContact } from './useAddContactTag';
export { useRemoveTagFromContact } from './useRemoveTagFromContact';
export { useUpdateContactPersonalDetails } from './useUpdateContactPersonalDetails';
export { useMergeContacts } from './useMergeContacts';
export { useArchiveContact } from './useArchiveContact';
export { useCreateContact } from './useCreateContact';
export type { ContactInput } from './types';
