export {
  useGetContactCommunicationChannelsQuery,
  useGetContactPersonalDetailsQuery,
  useGetContactTagsQuery,
  useCreateContactMutation,
  useUpdateContactEmailMutation,
  useAddEmailToContactMutation,
  useRemoveEmailFromContactMutation,
  useUpdateContactPhoneNumberMutation,
  useRemovePhoneNumberFromContactMutation,
  useAddPhoneToContactMutation,
  useAddTagToContactMutation,
  useMergeContactsMutation,
} from '../../graphQL/__generated__/generated';
export type {
  Contact,
  GetContactCommunicationChannelsQuery,
  GetContactPersonalDetailsQuery,
  ContactInput,
  CreateContactMutation,
  Email,
  UpdateContactEmailMutation,
  GetContactTagsQuery,
  AddTagToContactMutation,
  ContactTagInput,
  MergeContactsMutation,
} from '../../graphQL/__generated__/generated';
