// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: webtracker_session_created.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebtrackerSessionCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TrackerId     string                 `protobuf:"bytes,2,opt,name=tracker_id,json=trackerId,proto3" json:"tracker_id,omitempty"`
	VisitorId     string                 `protobuf:"bytes,3,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	EventType     WebTrackerEventType    `protobuf:"varint,5,opt,name=event_type,json=eventType,proto3,enum=pb.WebTrackerEventType" json:"event_type,omitempty"`
	EventData     string                 `protobuf:"bytes,6,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Href          string                 `protobuf:"bytes,8,opt,name=href,proto3" json:"href,omitempty"`
	Referrer      string                 `protobuf:"bytes,9,opt,name=referrer,proto3" json:"referrer,omitempty"`
	UserAgent     string                 `protobuf:"bytes,10,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Language      string                 `protobuf:"bytes,11,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebtrackerSessionCreated) Reset() {
	*x = WebtrackerSessionCreated{}
	mi := &file_webtracker_session_created_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebtrackerSessionCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebtrackerSessionCreated) ProtoMessage() {}

func (x *WebtrackerSessionCreated) ProtoReflect() protoreflect.Message {
	mi := &file_webtracker_session_created_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebtrackerSessionCreated.ProtoReflect.Descriptor instead.
func (*WebtrackerSessionCreated) Descriptor() ([]byte, []int) {
	return file_webtracker_session_created_proto_rawDescGZIP(), []int{0}
}

func (x *WebtrackerSessionCreated) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WebtrackerSessionCreated) GetTrackerId() string {
	if x != nil {
		return x.TrackerId
	}
	return ""
}

func (x *WebtrackerSessionCreated) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

func (x *WebtrackerSessionCreated) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *WebtrackerSessionCreated) GetEventType() WebTrackerEventType {
	if x != nil {
		return x.EventType
	}
	return WebTrackerEventType_WEB_TRACKER_EVENT_UNSPECIFIED
}

func (x *WebtrackerSessionCreated) GetEventData() string {
	if x != nil {
		return x.EventData
	}
	return ""
}

func (x *WebtrackerSessionCreated) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WebtrackerSessionCreated) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *WebtrackerSessionCreated) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

func (x *WebtrackerSessionCreated) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *WebtrackerSessionCreated) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_webtracker_session_created_proto protoreflect.FileDescriptor

const file_webtracker_session_created_proto_rawDesc = "" +
	"\n" +
	" webtracker_session_created.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a enum_webtracker_event_type.proto\"\x83\x03\n" +
	"\x18WebtrackerSessionCreated\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"tracker_id\x18\x02 \x01(\tR\ttrackerId\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x03 \x01(\tR\tvisitorId\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x126\n" +
	"\n" +
	"event_type\x18\x05 \x01(\x0e2\x17.pb.WebTrackerEventTypeR\teventType\x12\x1d\n" +
	"\n" +
	"event_data\x18\x06 \x01(\tR\teventData\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04href\x18\b \x01(\tR\x04href\x12\x1a\n" +
	"\breferrer\x18\t \x01(\tR\breferrer\x12\x1d\n" +
	"\n" +
	"user_agent\x18\n" +
	" \x01(\tR\tuserAgent\x12\x1a\n" +
	"\blanguage\x18\v \x01(\tR\blanguageB\x06Z\x04./pbb\x06proto3"

var (
	file_webtracker_session_created_proto_rawDescOnce sync.Once
	file_webtracker_session_created_proto_rawDescData []byte
)

func file_webtracker_session_created_proto_rawDescGZIP() []byte {
	file_webtracker_session_created_proto_rawDescOnce.Do(func() {
		file_webtracker_session_created_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webtracker_session_created_proto_rawDesc), len(file_webtracker_session_created_proto_rawDesc)))
	})
	return file_webtracker_session_created_proto_rawDescData
}

var file_webtracker_session_created_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_webtracker_session_created_proto_goTypes = []any{
	(*WebtrackerSessionCreated)(nil), // 0: pb.WebtrackerSessionCreated
	(WebTrackerEventType)(0),         // 1: pb.WebTrackerEventType
	(*timestamppb.Timestamp)(nil),    // 2: google.protobuf.Timestamp
}
var file_webtracker_session_created_proto_depIdxs = []int32{
	1, // 0: pb.WebtrackerSessionCreated.event_type:type_name -> pb.WebTrackerEventType
	2, // 1: pb.WebtrackerSessionCreated.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_webtracker_session_created_proto_init() }
func file_webtracker_session_created_proto_init() {
	if File_webtracker_session_created_proto != nil {
		return
	}
	file_enum_webtracker_event_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webtracker_session_created_proto_rawDesc), len(file_webtracker_session_created_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webtracker_session_created_proto_goTypes,
		DependencyIndexes: file_webtracker_session_created_proto_depIdxs,
		MessageInfos:      file_webtracker_session_created_proto_msgTypes,
	}.Build()
	File_webtracker_session_created_proto = out.File
	file_webtracker_session_created_proto_goTypes = nil
	file_webtracker_session_created_proto_depIdxs = nil
}
