// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type PagedResult interface {
	IsPagedResult()
	GetTotalPages() int
	GetTotalElements() int64
}

type BooleanResult struct {
	Result bool `json:"result"`
}

type CompanyPosition struct {
	CompanyName string  `json:"companyName"`
	JobTitle    *string `json:"jobTitle"`
}

type CompanyPositionInput struct {
	CompanyName string  `json:"companyName"`
	JobTitle    *string `json:"jobTitle"`
}

// A contact represents an individual in customerOS.
type Contact struct {
	// The unique ID associated with the contact in customerOS.
	ID string `json:"id"`
	// The title associate with the contact in customerOS.
	Title *PersonTitle `json:"title"`
	// The first name of the contact in customerOS.
	FirstName string `json:"firstName"`
	// The last name of the contact in customerOS.
	LastName string `json:"lastName"`
	// An ISO8601 timestamp recording when the contact was created in customerOS.
	CreatedAt time.Time `json:"createdAt"`
	// A user-defined label applied against a contact in customerOS.
	Label *string `json:"label"`
	// User-defined notes associated with a contact in customerOS.
	Notes *string `json:"notes"`
	// User-defined [should this be a defined type?]
	ContactType *string `json:"contactType"`
	// `companyName` and `jobTitle` of the contact if it has been associated with a company.
	CompanyPositions []*CompanyPosition `json:"companyPositions"`
	// Identifies any contact groups the contact is associated with.
	Groups []*ContactGroup `json:"groups"`
	// User defined metadata appended to the contact record in customerOS.
	TextCustomFields []*TextCustomField `json:"textCustomFields"`
	// All phone numbers associated with a contact in customerOS.
	PhoneNumbers []*PhoneNumberInfo `json:"phoneNumbers"`
	// All email addresses assocaited with a contact in customerOS.
	Emails     []*EmailInfo `json:"emails"`
	FieldsSets []*FieldsSet `json:"fieldsSets"`
}

type ContactGroup struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ContactGroupInput struct {
	Name string `json:"name"`
}

type ContactGroupUpdateInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ContactGroupsPage struct {
	Content       []*ContactGroup `json:"content"`
	TotalPages    int             `json:"totalPages"`
	TotalElements int64           `json:"totalElements"`
}

func (ContactGroupsPage) IsPagedResult()               {}
func (this ContactGroupsPage) GetTotalPages() int      { return this.TotalPages }
func (this ContactGroupsPage) GetTotalElements() int64 { return this.TotalElements }

// An individual that you would like to add to customerOS.
type ContactInput struct {
	// The title of the contact.
	Title *PersonTitle `json:"title"`
	// The first name of the contact.
	FirstName string `json:"firstName"`
	// The last name of the contact.
	LastName string `json:"lastName"`
	// A user-defined label attached to contact.
	Label *string `json:"label"`
	// User-defined notes associated with contact.
	Notes *string `json:"notes"`
	// User-defined [should this be a defined type?]
	ContactType *string `json:"contactType"`
	// User defined metadata appended to contact.
	TextCustomFields []*TextCustomFieldInput `json:"textCustomFields"`
	// The job title of the contact.
	CompanyPosition *CompanyPositionInput `json:"companyPosition"`
	// An email addresses assocaited with the contact.
	Email *EmailInput `json:"email"`
	// A phone number associated with the contact.
	PhoneNumber *PhoneNumberInput `json:"phoneNumber"`
}

// Updates data fields associated with an existing customer record in customerOS.
type ContactUpdateInput struct {
	// The unique ID associated with the contact in customerOS.
	ID string `json:"id"`
	// The title associate with the contact in customerOS.
	Title *PersonTitle `json:"title"`
	// The first name of the contact in customerOS.
	FirstName string `json:"firstName"`
	// The last name of the contact in customerOS.
	LastName string `json:"lastName"`
	// A user-defined label applied against a contact in customerOS.
	Label *string `json:"label"`
	// User-defined notes associated with contact.
	Notes *string `json:"notes"`
	// User-defined [should this be a defined type?]
	ContactType *string `json:"contactType"`
}

// Specifies how many pages of contact information has been returned in the query response.
type ContactsPage struct {
	// A contact entity in customerOS.
	Content []*Contact `json:"content"`
	// Total number of pages in the query response.
	TotalPages int `json:"totalPages"`
	// Total number of elements in the query response.
	TotalElements int64 `json:"totalElements"`
}

func (ContactsPage) IsPagedResult()               {}
func (this ContactsPage) GetTotalPages() int      { return this.TotalPages }
func (this ContactsPage) GetTotalElements() int64 { return this.TotalElements }

type EmailInfo struct {
	ID      string     `json:"id"`
	Email   string     `json:"email"`
	Label   EmailLabel `json:"label"`
	Primary bool       `json:"primary"`
}

type EmailInput struct {
	Email   string     `json:"email"`
	Label   EmailLabel `json:"label"`
	Primary *bool      `json:"primary"`
}

type EmailUpdateInput struct {
	ID      string     `json:"id"`
	Email   string     `json:"email"`
	Label   EmailLabel `json:"label"`
	Primary *bool      `json:"primary"`
}

type FieldsSet struct {
	ID               string             `json:"id"`
	Type             string             `json:"type"`
	Name             string             `json:"name"`
	Added            time.Time          `json:"added"`
	TextCustomFields []*TextCustomField `json:"textCustomFields"`
}

type FieldsSetInput struct {
	Type string `json:"type"`
	Name string `json:"name"`
}

type FieldsSetUpdateInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type PaginationFilter struct {
	Page  int `json:"page"`
	Limit int `json:"limit"`
}

type PhoneNumberInfo struct {
	ID      string     `json:"id"`
	Number  string     `json:"number"`
	Label   PhoneLabel `json:"label"`
	Primary bool       `json:"primary"`
}

type PhoneNumberInput struct {
	Number  string     `json:"number"`
	Label   PhoneLabel `json:"label"`
	Primary *bool      `json:"primary"`
}

type PhoneNumberUpdateInput struct {
	ID      string     `json:"id"`
	Number  string     `json:"number"`
	Label   PhoneLabel `json:"label"`
	Primary *bool      `json:"primary"`
}

type TenantUser struct {
	ID        string    `json:"id"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
}

type TenantUserInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}

type TenantUsersPage struct {
	Content       []*TenantUser `json:"content"`
	TotalPages    int           `json:"totalPages"`
	TotalElements int64         `json:"totalElements"`
}

func (TenantUsersPage) IsPagedResult()               {}
func (this TenantUsersPage) GetTotalPages() int      { return this.TotalPages }
func (this TenantUsersPage) GetTotalElements() int64 { return this.TotalElements }

type TextCustomField struct {
	ID    string  `json:"id"`
	Group *string `json:"group"`
	Name  string  `json:"name"`
	Value string  `json:"value"`
}

type TextCustomFieldInput struct {
	Group *string `json:"group"`
	Name  string  `json:"name"`
	Value string  `json:"value"`
}

type TextCustomFieldUpdateInput struct {
	ID    string  `json:"id"`
	Group *string `json:"group"`
	Name  string  `json:"name"`
	Value string  `json:"value"`
}

type EmailLabel string

const (
	EmailLabelMain  EmailLabel = "MAIN"
	EmailLabelWork  EmailLabel = "WORK"
	EmailLabelHome  EmailLabel = "HOME"
	EmailLabelOther EmailLabel = "OTHER"
)

var AllEmailLabel = []EmailLabel{
	EmailLabelMain,
	EmailLabelWork,
	EmailLabelHome,
	EmailLabelOther,
}

func (e EmailLabel) IsValid() bool {
	switch e {
	case EmailLabelMain, EmailLabelWork, EmailLabelHome, EmailLabelOther:
		return true
	}
	return false
}

func (e EmailLabel) String() string {
	return string(e)
}

func (e *EmailLabel) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EmailLabel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EmailLabel", str)
	}
	return nil
}

func (e EmailLabel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// The honorific title of an individual.
type PersonTitle string

const (
	// For men, regardless of marital status.
	PersonTitleMr PersonTitle = "MR"
	// For married women.
	PersonTitleMrs PersonTitle = "MRS"
	// For girls, unmarried women, and married women who continue to use their maiden name.
	PersonTitleMiss PersonTitle = "MISS"
	// For women, regardless of marital status, or when marital status is unknown.
	PersonTitleMs PersonTitle = "MS"
	// For the holder of a doctoral degree.
	PersonTitleDr PersonTitle = "DR"
)

var AllPersonTitle = []PersonTitle{
	PersonTitleMr,
	PersonTitleMrs,
	PersonTitleMiss,
	PersonTitleMs,
	PersonTitleDr,
}

func (e PersonTitle) IsValid() bool {
	switch e {
	case PersonTitleMr, PersonTitleMrs, PersonTitleMiss, PersonTitleMs, PersonTitleDr:
		return true
	}
	return false
}

func (e PersonTitle) String() string {
	return string(e)
}

func (e *PersonTitle) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PersonTitle(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PersonTitle", str)
	}
	return nil
}

func (e PersonTitle) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PhoneLabel string

const (
	PhoneLabelMain   PhoneLabel = "MAIN"
	PhoneLabelWork   PhoneLabel = "WORK"
	PhoneLabelHome   PhoneLabel = "HOME"
	PhoneLabelMobile PhoneLabel = "MOBILE"
	PhoneLabelOther  PhoneLabel = "OTHER"
)

var AllPhoneLabel = []PhoneLabel{
	PhoneLabelMain,
	PhoneLabelWork,
	PhoneLabelHome,
	PhoneLabelMobile,
	PhoneLabelOther,
}

func (e PhoneLabel) IsValid() bool {
	switch e {
	case PhoneLabelMain, PhoneLabelWork, PhoneLabelHome, PhoneLabelMobile, PhoneLabelOther:
		return true
	}
	return false
}

func (e PhoneLabel) String() string {
	return string(e)
}

func (e *PhoneLabel) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PhoneLabel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PhoneLabel", str)
	}
	return nil
}

func (e PhoneLabel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
