// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Contact - represents one person that can be contacted for a Customer. In B2C
type Contact struct {
	ID          string  `json:"id"`
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	Label       *string `json:"label"`
	ContactType *string `json:"contactType"`
}

type ContactInput struct {
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	Label       *string `json:"label"`
	ContactType *string `json:"contactType"`
}
