import { Currency } from '@graphql/types';
import { SelectOption } from '@shared/types/SelectOptions';

export const countryOptions: SelectOption[] = [
  { label: 'Afghanistan', value: 'AF' },
  { label: 'Åland Islands', value: 'AX' },
  { label: 'Albania', value: 'AL' },
  { label: 'Algeria', value: 'DZ' },
  { label: 'American Samoa', value: 'AS' },
  { label: 'Andorra', value: 'AD' },
  { label: 'Angola', value: 'AO' },
  { label: 'Anguilla', value: 'AI' },
  { label: 'Antarctica', value: 'AQ' },
  { label: 'Antigua and Barbuda', value: 'AG' },
  { label: 'Argentina', value: 'AR' },
  { label: 'Armenia', value: 'AM' },
  { label: 'Aruba', value: 'AW' },
  { label: 'Australia', value: 'AU' },
  { label: 'Austria', value: 'AT' },
  { label: 'Azerbaijan', value: 'AZ' },
  { label: 'Bahamas', value: 'BS' },
  { label: 'Bahrain', value: 'BH' },
  { label: 'Bangladesh', value: 'BD' },
  { label: 'Barbados', value: 'BB' },
  { label: 'Belarus', value: 'BY' },
  { label: 'Belgium', value: 'BE' },
  { label: 'Belize', value: 'BZ' },
  { label: 'Benin', value: 'BJ' },
  { label: 'Bermuda', value: 'BM' },
  { label: 'Bhutan', value: 'BT' },
  { label: 'Bolivia (Plurinational State of)', value: 'BO' },
  { label: 'Bonaire, Sint Eustatius and Saba', value: 'BQ' },
  { label: 'Bosnia and Herzegovina', value: 'BA' },
  { label: 'Botswana', value: 'BW' },
  { label: 'Bouvet Island', value: 'BV' },
  { label: 'Brazil', value: 'BR' },
  { label: 'British Indian Ocean Territory', value: 'IO' },
  { label: 'Brunei Darussalam', value: 'BN' },
  { label: 'Bulgaria', value: 'BG' },
  { label: 'Burkina Faso', value: 'BF' },
  { label: 'Burundi', value: 'BI' },
  { label: 'Cabo Verde', value: 'CV' },
  { label: 'Cambodia', value: 'KH' },
  { label: 'Cameroon', value: 'CM' },
  { label: 'Canada', value: 'CA' },
  { label: 'Cayman Islands', value: 'KY' },
  { label: 'Central African Republic', value: 'CF' },
  { label: 'Chad', value: 'TD' },
  { label: 'Chile', value: 'CL' },
  { label: 'China', value: 'CN' },
  { label: 'Christmas Island', value: 'CX' },
  { label: 'Cocos (Keeling) Islands', value: 'CC' },
  { label: 'Colombia', value: 'CO' },
  { label: 'Comoros', value: 'KM' },
  { label: 'Congo', value: 'CG' },
  { label: 'Congo, Democratic Republic of the', value: 'CD' },
  { label: 'Cook Islands', value: 'CK' },
  { label: 'Costa Rica', value: 'CR' },
  { label: "Côte d'Ivoire", value: 'CI' },
  { label: 'Croatia', value: 'HR' },
  { label: 'Cuba', value: 'CU' },
  { label: 'Curaçao', value: 'CW' },
  { label: 'Cyprus', value: 'CY' },
  { label: 'Czechia', value: 'CZ' },
  { label: 'Denmark', value: 'DK' },
  { label: 'Djibouti', value: 'DJ' },
  { label: 'Dominica', value: 'DM' },
  { label: 'Dominican Republic', value: 'DO' },
  { label: 'Ecuador', value: 'EC' },
  { label: 'Egypt', value: 'EG' },
  { label: 'El Salvador', value: 'SV' },
  { label: 'Equatorial Guinea', value: 'GQ' },
  { label: 'Eritrea', value: 'ER' },
  { label: 'Estonia', value: 'EE' },
  { label: 'Eswatini', value: 'SZ' },
  { label: 'Ethiopia', value: 'ET' },
  { label: 'Falkland Islands (Malvinas)', value: 'FK' },
  { label: 'Faroe Islands', value: 'FO' },
  { label: 'Fiji', value: 'FJ' },
  { label: 'Finland', value: 'FI' },
  { label: 'France', value: 'FR' },
  { label: 'French Guiana', value: 'GF' },
  { label: 'French Polynesia', value: 'PF' },
  { label: 'French Southern Territories', value: 'TF' },
  { label: 'Gabon', value: 'GA' },
  { label: 'Gambia', value: 'GM' },
  { label: 'Georgia', value: 'GE' },
  { label: 'Germany', value: 'DE' },
  { label: 'Ghana', value: 'GH' },
  { label: 'Gibraltar', value: 'GI' },
  { label: 'Greece', value: 'GR' },
  { label: 'Greenland', value: 'GL' },
  { label: 'Grenada', value: 'GD' },
  { label: 'Guadeloupe', value: 'GP' },
  { label: 'Guam', value: 'GU' },
  { label: 'Guatemala', value: 'GT' },
  { label: 'Guernsey', value: 'GG' },
  { label: 'Guinea', value: 'GN' },
  { label: 'Guinea-Bissau', value: 'GW' },
  { label: 'Guyana', value: 'GY' },
  { label: 'Haiti', value: 'HT' },
  { label: 'Heard Island and McDonald Islands', value: 'HM' },
  { label: 'Holy See', value: 'VA' },
  { label: 'Honduras', value: 'HN' },
  { label: 'Hong Kong', value: 'HK' },
  { label: 'Hungary', value: 'HU' },
  { label: 'Iceland', value: 'IS' },
  { label: 'India', value: 'IN' },
  { label: 'Indonesia', value: 'ID' },
  { label: 'Iran (Islamic Republic of)', value: 'IR' },
  { label: 'Iraq', value: 'IQ' },
  { label: 'Ireland', value: 'IE' },
  { label: 'Isle of Man', value: 'IM' },
  { label: 'Israel', value: 'IL' },
  { label: 'Italy', value: 'IT' },
  { label: 'Jamaica', value: 'JM' },
  { label: 'Japan', value: 'JP' },
  { label: 'Jersey', value: 'JE' },
  { label: 'Jordan', value: 'JO' },
  { label: 'Kazakhstan', value: 'KZ' },
  { label: 'Kenya', value: 'KE' },
  { label: 'Kiribati', value: 'KI' },
  { label: "Korea (Democratic People's Republic of)", value: 'KP' },
  { label: 'Korea, Republic of', value: 'KR' },
  { label: 'Kuwait', value: 'KW' },
  { label: 'Kyrgyzstan', value: 'KG' },
  { label: "Lao People's Democratic Republic", value: 'LA' },
  { label: 'Latvia', value: 'LV' },
  { label: 'Lebanon', value: 'LB' },
  { label: 'Lesotho', value: 'LS' },
  { label: 'Liberia', value: 'LR' },
  { label: 'Libya', value: 'LY' },
  { label: 'Liechtenstein', value: 'LI' },
  { label: 'Lithuania', value: 'LT' },
  { label: 'Luxembourg', value: 'LU' },
  { label: 'Macao', value: 'MO' },
  { label: 'Madagascar', value: 'MG' },
  { label: 'Malawi', value: 'MW' },
  { label: 'Malaysia', value: 'MY' },
  { label: 'Maldives', value: 'MV' },
  { label: 'Mali', value: 'ML' },
  { label: 'Malta', value: 'MT' },
  { label: 'Marshall Islands', value: 'MH' },
  { label: 'Martinique', value: 'MQ' },
  { label: 'Mauritania', value: 'MR' },
  { label: 'Mauritius', value: 'MU' },
  { label: 'Mayotte', value: 'YT' },
  { label: 'Mexico', value: 'MX' },
  { label: 'Micronesia (Federated States of)', value: 'FM' },
  { label: 'Moldova, Republic of', value: 'MD' },
  { label: 'Monaco', value: 'MC' },
  { label: 'Mongolia', value: 'MN' },
  { label: 'Montenegro', value: 'ME' },
  { label: 'Montserrat', value: 'MS' },
  { label: 'Morocco', value: 'MA' },
  { label: 'Mozambique', value: 'MZ' },
  { label: 'Myanmar', value: 'MM' },
  { label: 'Namibia', value: 'NA' },
  { label: 'Nauru', value: 'NR' },
  { label: 'Nepal', value: 'NP' },
  { label: 'Netherlands', value: 'NL' },
  { label: 'New Caledonia', value: 'NC' },
  { label: 'New Zealand', value: 'NZ' },
  { label: 'Nicaragua', value: 'NI' },
  { label: 'Niger', value: 'NE' },
  { label: 'Nigeria', value: 'NG' },
  { label: 'Niue', value: 'NU' },
  { label: 'Norfolk Island', value: 'NF' },
  { label: 'North Macedonia', value: 'MK' },
  { label: 'Northern Mariana Islands', value: 'MP' },
  { label: 'Norway', value: 'NO' },
  { label: 'Oman', value: 'OM' },
  { label: 'Pakistan', value: 'PK' },
  { label: 'Palau', value: 'PW' },
  { label: 'Palestine, State of', value: 'PS' },
  { label: 'Panama', value: 'PA' },
  { label: 'Papua New Guinea', value: 'PG' },
  { label: 'Paraguay', value: 'PY' },
  { label: 'Peru', value: 'PE' },
  { label: 'Philippines', value: 'PH' },
  { label: 'Pitcairn', value: 'PN' },
  { label: 'Poland', value: 'PL' },
  { label: 'Portugal', value: 'PT' },
  { label: 'Puerto Rico', value: 'PR' },
  { label: 'Qatar', value: 'QA' },
  { label: 'Réunion', value: 'RE' },
  { label: 'Romania', value: 'RO' },
  { label: 'Russian Federation', value: 'RU' },
  { label: 'Rwanda', value: 'RW' },
  { label: 'Saint Barthélemy', value: 'BL' },
  { label: 'Saint Helena, Ascension and Tristan da Cunha', value: 'SH' },
  { label: 'Saint Kitts and Nevis', value: 'KN' },
  { label: 'Saint Lucia', value: 'LC' },
  { label: 'Saint Martin (French part)', value: 'MF' },
  { label: 'Saint Pierre and Miquelon', value: 'PM' },
  { label: 'Saint Vincent and the Grenadines', value: 'VC' },
  { label: 'Samoa', value: 'WS' },
  { label: 'San Marino', value: 'SM' },
  { label: 'Sao Tome and Principe', value: 'ST' },
  { label: 'Saudi Arabia', value: 'SA' },
  { label: 'Senegal', value: 'SN' },
  { label: 'Serbia', value: 'RS' },
  { label: 'Seychelles', value: 'SC' },
  { label: 'Sierra Leone', value: 'SL' },
  { label: 'Singapore', value: 'SG' },
  { label: 'Sint Maarten (Dutch part)', value: 'SX' },
  { label: 'Slovakia', value: 'SK' },
  { label: 'Slovenia', value: 'SI' },
  { label: 'Solomon Islands', value: 'SB' },
  { label: 'Somalia', value: 'SO' },
  { label: 'South Africa', value: 'ZA' },
  { label: 'South Georgia and the South Sandwich Islands', value: 'GS' },
  { label: 'South Sudan', value: 'SS' },
  { label: 'Spain', value: 'ES' },
  { label: 'Sri Lanka', value: 'LK' },
  { label: 'Sudan', value: 'SD' },
  { label: 'Suriname', value: 'SR' },
  { label: 'Svalbard and Jan Mayen', value: 'SJ' },
  { label: 'Sweden', value: 'SE' },
  { label: 'Switzerland', value: 'CH' },
  { label: 'Syrian Arab Republic', value: 'SY' },
  { label: 'Taiwan, Province of China', value: 'TW' },
  { label: 'Tajikistan', value: 'TJ' },
  { label: 'Tanzania, United Republic of', value: 'TZ' },
  { label: 'Thailand', value: 'TH' },
  { label: 'Timor-Leste', value: 'TL' },
  { label: 'Togo', value: 'TG' },
  { label: 'Tokelau', value: 'TK' },
  { label: 'Tonga', value: 'TO' },
  { label: 'Trinidad and Tobago', value: 'TT' },
  { label: 'Tunisia', value: 'TN' },
  { label: 'Turkey', value: 'TR' },
  { label: 'Turkmenistan', value: 'TM' },
  { label: 'Turks and Caicos Islands', value: 'TC' },
  { label: 'Tuvalu', value: 'TV' },
  { label: 'Uganda', value: 'UG' },
  { label: 'Ukraine', value: 'UA' },
  { label: 'United Arab Emirates', value: 'AE' },
  {
    label: 'United Kingdom of Great Britain and Northern Ireland',
    value: 'GB',
  },
  { label: 'United States of America', value: 'US' },
  { label: 'United States Minor Outlying Islands', value: 'UM' },
  { label: 'Uruguay', value: 'UY' },
  { label: 'Uzbekistan', value: 'UZ' },
  { label: 'Vanuatu', value: 'VU' },
  { label: 'Venezuela (Bolivarian Republic of)', value: 'VE' },
  { label: 'Viet Nam', value: 'VN' },
  { label: 'Virgin Islands (British)', value: 'VG' },
  { label: 'Virgin Islands (U.S.)', value: 'VI' },
  { label: 'Wallis and Futuna', value: 'WF' },
  { label: 'Western Sahara', value: 'EH' },
  { label: 'Yemen', value: 'YE' },
  { label: 'Zambia', value: 'ZM' },
  { label: 'Zimbabwe', value: 'ZW' },
];

export const currencyOptions = [
  { label: 'Afghan afghani', value: 'AFN' },
  { label: 'Albanian lek', value: 'ALL' },
  { label: 'Armenian dram', value: 'AMD' },
  { label: 'Netherlands Antillean guilder', value: 'ANG' },
  { label: 'Angolan kwanza', value: 'AOA' },
  { label: 'Argentine peso', value: 'ARS' },
  { label: 'Australian dollar', value: 'AUD' },
  { label: 'Aruban florin', value: 'AWG' },
  { label: 'Azerbaijani manat', value: 'AZN' },
  { label: 'Bosnia and Herzegovina convertible mark', value: 'BAM' },
  { label: 'Barbados dollar', value: 'BBD' },
  { label: 'Bangladeshi taka', value: 'BDT' },
  { label: 'Bulgarian lev', value: 'BGN' },
  { label: 'Bahraini dinar', value: 'BHD' },
  { label: 'Burundian franc', value: 'BIF' },
  {
    label: 'Bermudian dollar (customarily known as Bermuda dollar)',
    value: 'BMD',
  },
  { label: 'Brunei dollar', value: 'BND' },
  { label: 'Boliviano', value: 'BOB' },
  { label: 'Bolivian Mvdol (funds code)', value: 'BOV' },
  { label: 'Brazilian real', value: 'BRL' },
  { label: 'Bahamian dollar', value: 'BSD' },
  { label: 'Bhutanese ngultrum', value: 'BTN' },
  { label: 'Botswana pula', value: 'BWP' },
  { label: 'Belarusian ruble', value: 'BYR' },
  { label: 'Belize dollar', value: 'BZD' },
  { label: 'Canadian dollar', value: 'CAD' },
  { label: 'Congolese franc', value: 'CDF' },
  { label: 'WIR Euro (complementary currency)', value: 'CHE' },
  { label: 'Swiss franc', value: 'CHF' },
  { label: 'WIR Franc (complementary currency)', value: 'CHW' },
  { label: 'Unidad de Fomento (funds code)', value: 'CLF' },
  { label: 'Chilean peso', value: 'CLP' },
  { label: 'Chinese yuan', value: 'CNY' },
  { label: 'Colombian peso', value: 'COP' },
  { label: 'Unidad de Valor Real', value: 'COU' },
  { label: 'Costa Rican colon', value: 'CRC' },
  { label: 'Cuban convertible peso', value: 'CUC' },
  { label: 'Cuban peso', value: 'CUP' },
  { label: 'Cape Verde escudo', value: 'CVE' },
  { label: 'Czech koruna', value: 'CZK' },
  { label: 'Djiboutian franc', value: 'DJF' },
  { label: 'Danish krone', value: 'DKK' },
  { label: 'Dominican peso', value: 'DOP' },
  { label: 'Algerian dinar', value: 'DZD' },
  { label: 'Egyptian pound', value: 'EGP' },
  { label: 'Eritrean nakfa', value: 'ERN' },
  { label: 'Ethiopian birr', value: 'ETB' },
  { label: 'Euro', value: 'EUR' },
  { label: 'Fiji dollar', value: 'FJD' },
  { label: 'Falkland Islands pound', value: 'FKP' },
  { label: 'Pound sterling', value: 'GBP' },
  { label: 'Georgian lari', value: 'GEL' },
  { label: 'Ghanaian cedi', value: 'GHS' },
  { label: 'Gibraltar pound', value: 'GIP' },
  { label: 'Gambian dalasi', value: 'GMD' },
  { label: 'Guinean franc', value: 'GNF' },
  { label: 'Guatemalan quetzal', value: 'GTQ' },
  { label: 'Guyanese dollar', value: 'GYD' },
  { label: 'Hong Kong dollar', value: 'HKD' },
  { label: 'Honduran lempira', value: 'HNL' },
  { label: 'Croatian kuna', value: 'HRK' },
  { label: 'Haitian gourde', value: 'HTG' },
  { label: 'Hungarian forint', value: 'HUF' },
  { label: 'Indonesian rupiah', value: 'IDR' },
  { label: 'Israeli new shekel', value: 'ILS' },
  { label: 'Indian rupee', value: 'INR' },
  { label: 'Iraqi dinar', value: 'IQD' },
  { label: 'Iranian rial', value: 'IRR' },
  { label: 'Icelandic króna', value: 'ISK' },
  { label: 'Jamaican dollar', value: 'JMD' },
  { label: 'Jordanian dinar', value: 'JOD' },
  { label: 'Japanese yen', value: 'JPY' },
  { label: 'Kenyan shilling', value: 'KES' },
  { label: 'Kyrgyzstani som', value: 'KGS' },
  { label: 'Cambodian riel', value: 'KHR' },
  { label: 'Comoro franc', value: 'KMF' },
  { label: 'North Korean won', value: 'KPW' },
  { label: 'South Korean won', value: 'KRW' },
  { label: 'Kuwaiti dinar', value: 'KWD' },
  { label: 'Cayman Islands dollar', value: 'KYD' },
  { label: 'Kazakhstani tenge', value: 'KZT' },
  { label: 'Lao kip', value: 'LAK' },
  { label: 'Lebanese pound', value: 'LBP' },
  { label: 'Sri Lankan rupee', value: 'LKR' },
  { label: 'Liberian dollar', value: 'LRD' },
  { label: 'Lesotho loti', value: 'LSL' },
  { label: 'Lithuanian litas', value: 'LTL' },
  { label: 'Latvian lats', value: 'LVL' },
  { label: 'Libyan dinar', value: 'LYD' },
  { label: 'Moroccan dirham', value: 'MAD' },
  { label: 'Moldovan leu', value: 'MDL' },
  { label: 'Malagasy ariary', value: 'MGA' },
  { label: 'Macedonian denar', value: 'MKD' },
  { label: 'Myanmar kyat', value: 'MMK' },
  { label: 'Mongolian tugrik', value: 'MNT' },
  { label: 'Macanese pataca', value: 'MOP' },
  { label: 'Mauritanian ouguiya', value: 'MRU' },
  { label: 'Mauritian rupee', value: 'MUR' },
  { label: 'Maldivian rufiyaa', value: 'MVR' },
  { label: 'Malawian kwacha', value: 'MWK' },
  { label: 'Mexican peso', value: 'MXN' },
  { label: 'Mexican Unidad de Inversion (UDI) (funds code)', value: 'MXV' },
  { label: 'Malaysian ringgit', value: 'MYR' },
  { label: 'Mozambican metical', value: 'MZN' },
  { label: 'Namibian dollar', value: 'NAD' },
  { label: 'Nigerian naira', value: 'NGN' },
  { label: 'Nicaraguan córdoba', value: 'NIO' },
  { label: 'Norwegian krone', value: 'NOK' },
  { label: 'Nepalese rupee', value: 'NPR' },
  { label: 'New Zealand dollar', value: 'NZD' },
  { label: 'Omani rial', value: 'OMR' },
  { label: 'Panamanian balboa', value: 'PAB' },
  { label: 'Peruvian nuevo sol', value: 'PEN' },
  { label: 'Papua New Guinean kina', value: 'PGK' },
  { label: 'Philippine peso', value: 'PHP' },
  { label: 'Pakistani rupee', value: 'PKR' },
  { label: 'Polish złoty', value: 'PLN' },
  { label: 'Paraguayan guaraní', value: 'PYG' },
  { label: 'Qatari riyal', value: 'QAR' },
  { label: 'Romanian leu', value: 'RON' },
  { label: 'Serbian dinar', value: 'RSD' },
  { label: 'Russian ruble', value: 'RUB' },
  { label: 'Rwandan franc', value: 'RWF' },
  { label: 'Saudi riyal', value: 'SAR' },
  { label: 'Solomon Islands dollar', value: 'SBD' },
  { label: 'Seychelles rupee', value: 'SCR' },
  { label: 'Sudanese pound', value: 'SDG' },
  { label: 'Swedish krona/kronor', value: 'SEK' },
  { label: 'Singapore dollar', value: 'SGD' },
  { label: 'Saint Helena pound', value: 'SHP' },
  { label: 'Sierra Leonean leone', value: 'SLL' },
  { label: 'Somali shilling', value: 'SOS' },
  { label: 'Surinamese dollar', value: 'SRD' },
  { label: 'South Sudanese pound', value: 'SSP' },
  { label: 'São Tomé and Príncipe dobra', value: 'STN' },
  { label: 'Salvadoran colón', value: 'SVC' },
  { label: 'Syrian pound', value: 'SYP' },
  { label: 'Swazi lilangeni', value: 'SZL' },
  { label: 'Thai baht', value: 'THB' },
  { label: 'Tajikistani somoni', value: 'TJS' },
  { label: 'Turkmenistan manat', value: 'TMT' },
  { label: 'Tunisian dinar', value: 'TND' },
  { label: 'Tongan paʻanga', value: 'TOP' },
  { label: 'Turkish lira', value: 'TRY' },
  { label: 'Trinidad and Tobago dollar', value: 'TTD' },
  { label: 'New Taiwan dollar', value: 'TWD' },
  { label: 'Tanzanian shilling', value: 'TZS' },
  { label: 'Ukrainian hryvnia', value: 'UAH' },
  { label: 'Ugandan shilling', value: 'UGX' },
  { label: 'United States dollar', value: 'USD' },
  { label: 'Uruguayan peso', value: 'UYU' },
  { label: 'Unidad Previsional', value: 'UYW' },
  { label: 'Uzbekistan som', value: 'UZS' },
  { label: 'Venezuelan bolívar soberano', value: 'VES' },
  { label: 'Vietnamese đồng', value: 'VND' },
  { label: 'Vanuatu vatu', value: 'VUV' },
  { label: 'Samoan tālā', value: 'WST' },
  { label: 'Central African CFA franc', value: 'XAF' },
  { label: 'East Caribbean dollar', value: 'XCD' },
  { label: 'West African CFA franc', value: 'XOF' },
  { label: 'Pacific franc (CFP franc)', value: 'XPF' },
  { label: 'Yemeni rial', value: 'YER' },
  { label: 'South African rand', value: 'ZAR' },
  { label: 'Zambian kwacha', value: 'ZMW' },
  { label: 'Zimbabwean dollar', value: 'ZWL' },
];

const currencyOptionsLabel = {
  AFN: 'Afghan afghani - AFN',
  ALL: 'Albanian lek - ALL',
  AMD: 'Armenian dram - AMD',
  ANG: 'Netherlands Antillean guilder - ANG',
  AOA: 'Angolan kwanza - AOA',
  ARS: 'Argentine peso - ARS',
  AUD: 'Australian dollar - AUD',
  AWG: 'Aruban florin - AWG',
  AZN: 'Azerbaijani manat - AZN',
  BAM: 'Bosnia and Herzegovina convertible mark - BAM',
  BBD: 'Barbados dollar - BBD',
  BDT: 'Bangladeshi taka - BDT',
  BGN: 'Bulgarian lev - BGN',
  BHD: 'Bahraini dinar - BHD',
  BIF: 'Burundian franc - BIF',
  BMD: 'Bermudian dollar (customarily known as Bermuda dollar) - BMD',
  BND: 'Brunei dollar - BND',
  BOB: 'Boliviano - BOB',
  BOV: 'Bolivian Mvdol (funds code) - BOV',
  BRL: 'Brazilian real - BRL',
  BSD: 'Bahamian dollar - BSD',
  BTN: 'Bhutanese ngultrum - BTN',
  BWP: 'Botswana pula - BWP',
  BYR: 'Belarusian ruble - BYR',
  BZD: 'Belize dollar - BZD',
  CAD: 'Canadian dollar - CAD',
  CDF: 'Congolese franc - CDF',
  CHE: 'WIR Euro (complementary currency) - CHE',
  CHF: 'Swiss franc - CHF',
  CHW: 'WIR Franc (complementary currency) - CHW',
  CLF: 'Unidad de Fomento (funds code) - CLF',
  CLP: 'Chilean peso - CLP',
  CNY: 'Chinese yuan - CNY',
  COP: 'Colombian peso - COP',
  COU: 'Unidad de Valor Real - COU',
  CRC: 'Costa Rican colon - CRC',
  CUC: 'Cuban convertible peso - CUC',
  CUP: 'Cuban peso - CUP',
  CVE: 'Cape Verde escudo - CVE',
  CZK: 'Czech koruna - CZK',
  DJF: 'Djiboutian franc - DJF',
  DKK: 'Danish krone - DKK',
  DOP: 'Dominican peso - DOP',
  DZD: 'Algerian dinar - DZD',
  EGP: 'Egyptian pound - EGP',
  ERN: 'Eritrean nakfa - ERN',
  ETB: 'Ethiopian birr - ETB',
  EUR: 'Euro - EUR',
  FJD: 'Fiji dollar - FJD',
  FKP: 'Falkland Islands pound - FKP',
  GBP: 'Pound sterling - GBP',
  GEL: 'Georgian lari - GEL',
  GHS: 'Ghanaian cedi - GHS',
  GIP: 'Gibraltar pound - GIP',
  GMD: 'Gambian dalasi - GMD',
  GNF: 'Guinean franc - GNF',
  GTQ: 'Guatemalan quetzal - GTQ',
  GYD: 'Guyanese dollar - GYD',
  HKD: 'Hong Kong dollar - HKD',
  HNL: 'Honduran lempira - HNL',
  HRK: 'Croatian kuna - HRK',
  HTG: 'Haitian gourde - HTG',
  HUF: 'Hungarian forint - HUF',
  IDR: 'Indonesian rupiah - IDR',
  ILS: 'Israeli new shekel - ILS',
  INR: 'Indian rupee - INR',
  IQD: 'Iraqi dinar - IQD',
  IRR: 'Iranian rial - IRR',
  ISK: 'Icelandic króna - ISK',
  JMD: 'Jamaican dollar - JMD',
  JOD: 'Jordanian dinar - JOD',
  JPY: 'Japanese yen - JPY',
  KES: 'Kenyan shilling - KES',
  KGS: 'Kyrgyzstani som - KGS',
  KHR: 'Cambodian riel - KHR',
  KMF: 'Comoro franc - KMF',
  KPW: 'North Korean won - KPW',
  KRW: 'South Korean won - KRW',
  KWD: 'Kuwaiti dinar - KWD',
  KYD: 'Cayman Islands dollar - KYD',
  KZT: 'Kazakhstani tenge - KZT',
  LAK: 'Lao kip - LAK',
  LBP: 'Lebanese pound - LBP',
  LKR: 'Sri Lankan rupee - LKR',
  LRD: 'Liberian dollar - LRD',
  LSL: 'Lesotho loti - LSL',
  LTL: 'Lithuanian litas - LTL',
  LVL: 'Latvian lats - LVL',
  LYD: 'Libyan dinar - LYD',
  MAD: 'Moroccan dirham - MAD',
  MDL: 'Moldovan leu - MDL',
  MGA: 'Malagasy ariary - MGA',
  MKD: 'Macedonian denar - MKD',
  MMK: 'Myanmar kyat - MMK',
  MNT: 'Mongolian tugrik - MNT',
  MOP: 'Macanese pataca - MOP',
  MRU: 'Mauritanian ouguiya - MRU',
  MUR: 'Mauritian rupee - MUR',
  MVR: 'Maldivian rufiyaa - MVR',
  MWK: 'Malawian kwacha - MWK',
  MXN: 'Mexican peso - MXN',
  MXV: 'Mexican Unidad de Inversion (UDI) (funds code) - MXV',
  MYR: 'Malaysian ringgit - MYR',
  MZN: 'Mozambican metical - MZN',
  NAD: 'Namibian dollar - NAD',
  NGN: 'Nigerian naira - NGN',
  NIO: 'Nicaraguan córdoba - NIO',
  NOK: 'Norwegian krone - NOK',
  NPR: 'Nepalese rupee - NPR',
  NZD: 'New Zealand dollar - NZD',
  OMR: 'Omani rial - OMR',
  PAB: 'Panamanian balboa - PAB',
  PEN: 'Peruvian nuevo sol - PEN',
  PGK: 'Papua New Guinean kina - PGK',
  PHP: 'Philippine peso - PHP',
  PKR: 'Pakistani rupee - PKR',
  PLN: 'Polish złoty - PLN',
  PYG: 'Paraguayan guaraní - PYG',
  QAR: 'Qatari riyal - QAR',
  RON: 'Romanian leu - RON',
  RSD: 'Serbian dinar - RSD',
  RUB: 'Russian ruble - RUB',
  RWF: 'Rwandan franc - RWF',
  SAR: 'Saudi riyal - SAR',
  SBD: 'Solomon Islands dollar - SBD',
  SCR: 'Seychelles rupee - SCR',
  SDG: 'Sudanese pound - SDG',
  SEK: 'Swedish krona/kronor - SEK',
  SGD: 'Singapore dollar - SGD',
  SHP: 'Saint Helena pound - SHP',
  SLL: 'Sierra Leonean leone - SLL',
  SOS: 'Somali shilling - SOS',
  SRD: 'Surinamese dollar - SRD',
  SSP: 'South Sudanese pound - SSP',
  STN: 'São Tomé and Príncipe dobra - STN',
  SVC: 'Salvadoran colón - SVC',
  SYP: 'Syrian pound - SYP',
  SZL: 'Swazi lilangeni - SZL',
  THB: 'Thai baht - THB',
  TJS: 'Tajikistani somoni - TJS',
  TMT: 'Turkmenistan manat - TMT',
  TND: 'Tunisian dinar - TND',
  TOP: 'Tongan paʻanga - TOP',
  TRY: 'Turkish lira - TRY',
  TTD: 'Trinidad and Tobago dollar - TTD',
  TWD: 'New Taiwan dollar - TWD',
  TZS: 'Tanzanian shilling - TZS',
  UAH: 'Ukrainian hryvnia - UAH',
  UGX: 'Ugandan shilling - UGX',
  USD: 'United States dollar - USD',
  UYU: 'Uruguayan peso - UYU',
  UYW: 'Unidad Previsional - UYW',
  UZS: 'Uzbekistan som - UZS',
  VES: 'Venezuelan bolívar soberano - VES',
  VND: 'Vietnamese đồng - VND',
  VUV: 'Vanuatu vatu - VUV',
  WST: 'Samoan tālā - WST',
  XAF: 'Central African CFA franc - XAF',
  XCD: 'East Caribbean dollar - XCD',
  XOF: 'West African CFA franc - XOF',
  XPF: 'Pacific franc (CFP franc) - XPF',
  YER: 'Yemeni rial - YER',
  ZAR: 'South African rand - ZAR',
  ZMW: 'Zambian kwacha - ZMW',
  ZWL: 'Zimbabwean dollar - ZWL',
};

export const getCurrencyOptions = () => {
  return Object.values(Currency).map((value) => ({
    label: currencyOptionsLabel[value],
    value: value,
  }));
};
