import { cva } from 'class-variance-authority';
export const iconVariant = cva('', {
  variants: {
    size: {
      xxs: [],
      xs: [],
      sm: [],
      md: [],
      lg: [],
    },
    variant: {
      solid: [],
      outline: [],
      link: [],
      ghost: [],
    },
    colorScheme: {
      primary: [],
      gray: [],
      grayBlue: [],
      grayModern: [],
      grayWarm: [],
      error: [],
      rose: [],
      warning: [],
      yellow: [],
      blueDark: [],
      teal: [],
      success: [],
      blue: [],
      moss: [],
      greenLight: [],
      violet: [],
      fuchsia: [],
      orangeDark: [],
      purple: [],
      cyan: [],
    },
  },
  compoundVariants: [
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'grayBlue',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'grayModern',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'grayWarm',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'yellow',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'blue',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'orangeDark',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'purple',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'cyan',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-3 h-3', 'text-primary-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-3 h-3', 'text-gray-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'grayBlue',
      className: ['w-3 h-3', 'text-grayBlue-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'grayModern',
      className: ['w-3 h-3', 'text-grayModern-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'grayWarm',
      className: ['w-3 h-3', 'text-grayWarm-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-3 h-3', 'text-error-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-3 h-3', 'text-rose-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-3 h-3', 'text-warning-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'yellow',
      className: ['w-3 h-3', 'text-yellow-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-3 h-3', 'text-blueDark-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-3 h-3', 'text-teal-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-3 h-3', 'text-success-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'blue',
      className: ['w-3 h-3', 'text-blue-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-3 h-3', 'text-moss-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-3 h-3', 'text-greenLight-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-3 h-3', 'text-violet-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-3 h-3', 'text-fuchsia-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'orangeDark',
      className: ['w-3 h-3', 'text-orangeDark-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'purple',
      className: ['w-3 h-3', 'text-purple-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'cyan',
      className: ['w-3 h-3', 'text-cyan-600'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'primary',
      className: ['w-3 h-3', 'text-primary-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'gray',
      className: ['w-3 h-3', 'text-gray-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'grayBlue',
      className: ['w-3 h-3', 'text-grayBlue-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'grayModern',
      className: ['w-3 h-3', 'text-grayModern-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'grayWarm',
      className: ['w-3 h-3', 'text-grayWarm-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'error',
      className: ['w-3 h-3', 'text-error-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'rose',
      className: ['w-3 h-3', 'text-rose-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'warning',
      className: ['w-3 h-3', 'text-warning-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'yellow',
      className: ['w-3 h-3', 'text-yellow-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'blueDark',
      className: ['w-3 h-3', 'text-blueDark-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'teal',
      className: ['w-3 h-3', 'text-teal-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'success',
      className: ['w-3 h-3', 'text-success-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'blue',
      className: ['w-3 h-3', 'text-blue-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'moss',
      className: ['w-3 h-3', 'text-moss-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'greenLight',
      className: ['w-3 h-3', 'text-greenLight-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'violet',
      className: ['w-3 h-3', 'text-violet-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'fuchsia',
      className: ['w-3 h-3', 'text-fuchsia-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'orangeDark',
      className: ['w-3 h-3', 'text-orangeDark-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'purple',
      className: ['w-3 h-3', 'text-purple-700'],
    },
    {
      size: 'xxs',
      variant: 'link',
      colorScheme: 'cyan',
      className: ['w-3 h-3', 'text-cyan-700'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-3 h-3', 'text-primary-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-3 h-3', 'text-gray-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'grayBlue',
      className: ['w-3 h-3', 'text-grayBlue-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'grayModern',
      className: ['w-3 h-3', 'text-grayModern-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'grayWarm',
      className: ['w-3 h-3', 'text-grayWarm-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-3 h-3', 'text-error-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-3 h-3', 'text-rose-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-3 h-3', 'text-warning-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'yellow',
      className: ['w-3 h-3', 'text-yellow-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-3 h-3', 'text-blueDark-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-3 h-3', 'text-teal-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-3 h-3', 'text-success-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'blue',
      className: ['w-3 h-3', 'text-blue-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-3 h-3', 'text-moss-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-3 h-3', 'text-greenLight-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-3 h-3', 'text-violet-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-3 h-3', 'text-fuchsia-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'orangeDark',
      className: ['w-3 h-3', 'text-orangeDark-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'purple',
      className: ['w-3 h-3', 'text-purple-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'cyan',
      className: ['w-3 h-3', 'text-cyan-600'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'grayBlue',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'grayModern',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'grayWarm',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'yellow',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'blue',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'orangeDark',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'purple',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'cyan',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'grayBlue',
      className: ['w-4 h-4', 'text-grayBlue-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'grayModern',
      className: ['w-4 h-4', 'text-grayModern-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'grayWarm',
      className: ['w-4 h-4', 'text-grayWarm-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'yellow',
      className: ['w-4 h-4', 'text-yellow-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'blue',
      className: ['w-4 h-4', 'text-blue-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'orangeDark',
      className: ['w-4 h-4', 'text-orangeDark-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'purple',
      className: ['w-4 h-4', 'text-purple-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'cyan',
      className: ['w-4 h-4', 'text-cyan-600'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'grayBlue',
      className: ['w-4 h-4', 'text-grayBlue-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'grayModern',
      className: ['w-4 h-4', 'text-grayModern-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'grayWarm',
      className: ['w-4 h-4', 'text-grayWarm-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'yellow',
      className: ['w-4 h-4', 'text-yellow-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'blue',
      className: ['w-4 h-4', 'text-blue-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'orangeDark',
      className: ['w-4 h-4', 'text-orangeDark-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'purple',
      className: ['w-4 h-4', 'text-purple-700'],
    },
    {
      size: 'xs',
      variant: 'link',
      colorScheme: 'cyan',
      className: ['w-4 h-4', 'text-cyan-700'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'grayBlue',
      className: ['w-4 h-4', 'text-grayBlue-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'grayModern',
      className: ['w-4 h-4', 'text-grayModern-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'grayWarm',
      className: ['w-4 h-4', 'text-grayWarm-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-4 h-4', 'text-rose-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-4 h-4', 'text-warning-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'yellow',
      className: ['w-4 h-4', 'text-yellow-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-4 h-4', 'text-blueDark-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-4 h-4', 'text-teal-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'blue',
      className: ['w-4 h-4', 'text-blue-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-4 h-4', 'text-moss-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-4 h-4', 'text-greenLight-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-4 h-4', 'text-violet-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-4 h-4', 'text-fuchsia-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'orangeDark',
      className: ['w-4 h-4', 'text-orangeDark-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'purple',
      className: ['w-4 h-4', 'text-purple-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'cyan',
      className: ['w-4 h-4', 'text-cyan-600'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-grayBlue-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-grayModern-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-grayWarm-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-rose-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-warning-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-yellow-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-blueDark-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-teal-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-blue-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-moss-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-greenLight-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-violet-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-fuchsia-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-orangeDark-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-purple-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-cyan-600'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-grayBlue-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-grayModern-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-grayWarm-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-rose-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-warning-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-yellow-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-blueDark-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-teal-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-blue-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-moss-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-greenLight-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-violet-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-fuchsia-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-orangeDark-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-purple-700'],
    },
    {
      size: 'sm',
      variant: 'link',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-cyan-700'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-grayBlue-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-grayModern-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-grayWarm-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-rose-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-warning-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-yellow-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-blueDark-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-teal-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-blue-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-moss-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-greenLight-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-violet-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-fuchsia-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-orangeDark-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-purple-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-cyan-600'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-grayBlue-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-grayModern-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-grayWarm-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-rose-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-warning-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-yellow-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-blueDark-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-teal-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-blue-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-moss-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-greenLight-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-violet-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-fuchsia-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-orangeDark-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-purple-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-cyan-600'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-grayBlue-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-grayModern-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-grayWarm-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-rose-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-warning-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-yellow-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-blueDark-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-teal-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-blue-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-moss-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-greenLight-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-violet-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-fuchsia-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-orangeDark-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-purple-700'],
    },
    {
      size: 'md',
      variant: 'link',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-cyan-700'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'grayBlue',
      className: ['w-5 h-5', 'text-grayBlue-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'grayModern',
      className: ['w-5 h-5', 'text-grayModern-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'grayWarm',
      className: ['w-5 h-5', 'text-grayWarm-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-5 h-5', 'text-rose-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-5 h-5', 'text-warning-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'yellow',
      className: ['w-5 h-5', 'text-yellow-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-5 h-5', 'text-blueDark-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-5 h-5', 'text-teal-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'blue',
      className: ['w-5 h-5', 'text-blue-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-5 h-5', 'text-moss-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-5 h-5', 'text-greenLight-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-5 h-5', 'text-violet-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-5 h-5', 'text-fuchsia-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'orangeDark',
      className: ['w-5 h-5', 'text-orangeDark-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'purple',
      className: ['w-5 h-5', 'text-purple-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'cyan',
      className: ['w-5 h-5', 'text-cyan-600'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'grayBlue',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'grayModern',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'grayWarm',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'rose',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'yellow',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'blueDark',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'teal',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'blue',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'moss',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'greenLight',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'violet',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'fuchsia',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'orangeDark',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'purple',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'cyan',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-primary-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-gray-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'grayBlue',
      className: ['w-6 h-6', 'text-grayBlue-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'grayModern',
      className: ['w-6 h-6', 'text-grayModern-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'grayWarm',
      className: ['w-6 h-6', 'text-grayWarm-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-error-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'rose',
      className: ['w-6 h-6', 'text-rose-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'warning',
      className: ['w-6 h-6', 'text-warning-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'yellow',
      className: ['w-6 h-6', 'text-yellow-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'blueDark',
      className: ['w-6 h-6', 'text-blueDark-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'teal',
      className: ['w-6 h-6', 'text-teal-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-success-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'blue',
      className: ['w-6 h-6', 'text-blue-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'moss',
      className: ['w-6 h-6', 'text-moss-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'greenLight',
      className: ['w-6 h-6', 'text-greenLight-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'violet',
      className: ['w-6 h-6', 'text-violet-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'fuchsia',
      className: ['w-6 h-6', 'text-fuchsia-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'orangeDark',
      className: ['w-6 h-6', 'text-orangeDark-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'purple',
      className: ['w-6 h-6', 'text-purple-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'cyan',
      className: ['w-6 h-6', 'text-cyan-600'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-primary-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-gray-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'grayBlue',
      className: ['w-6 h-6', 'text-grayBlue-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'grayModern',
      className: ['w-6 h-6', 'text-grayModern-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'grayWarm',
      className: ['w-6 h-6', 'text-grayWarm-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-error-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'rose',
      className: ['w-6 h-6', 'text-rose-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'warning',
      className: ['w-6 h-6', 'text-warning-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'yellow',
      className: ['w-6 h-6', 'text-yellow-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'blueDark',
      className: ['w-6 h-6', 'text-blueDark-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'teal',
      className: ['w-6 h-6', 'text-teal-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-success-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'blue',
      className: ['w-6 h-6', 'text-blue-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'moss',
      className: ['w-6 h-6', 'text-moss-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'greenLight',
      className: ['w-6 h-6', 'text-greenLight-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'violet',
      className: ['w-6 h-6', 'text-violet-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'fuchsia',
      className: ['w-6 h-6', 'text-fuchsia-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'orangeDark',
      className: ['w-6 h-6', 'text-orangeDark-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'purple',
      className: ['w-6 h-6', 'text-purple-700'],
    },
    {
      size: 'lg',
      variant: 'link',
      colorScheme: 'cyan',
      className: ['w-6 h-6', 'text-cyan-700'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-primary-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-gray-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'grayBlue',
      className: ['w-6 h-6', 'text-grayBlue-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'grayModern',
      className: ['w-6 h-6', 'text-grayModern-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'grayWarm',
      className: ['w-6 h-6', 'text-grayWarm-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-error-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'rose',
      className: ['w-6 h-6', 'text-rose-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'warning',
      className: ['w-6 h-6', 'text-warning-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'yellow',
      className: ['w-6 h-6', 'text-yellow-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'blueDark',
      className: ['w-6 h-6', 'text-blueDark-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'teal',
      className: ['w-6 h-6', 'text-teal-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-success-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'blue',
      className: ['w-6 h-6', 'text-blue-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'moss',
      className: ['w-6 h-6', 'text-moss-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'greenLight',
      className: ['w-6 h-6', 'text-greenLight-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'violet',
      className: ['w-6 h-6', 'text-violet-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'fuchsia',
      className: ['w-6 h-6', 'text-fuchsia-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'orangeDark',
      className: ['w-6 h-6', 'text-orangeDark-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'purple',
      className: ['w-6 h-6', 'text-purple-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'cyan',
      className: ['w-6 h-6', 'text-cyan-600'],
    },
  ],
});

export const linkButton = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'gap-2',
    'text-base',
    'font-medium',
    'shadow-xs',
    'outline-none',
    'transition',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
  ],
  {
    variants: {
      colorScheme: {
        primary: [
          'text-primary-700',
          'hover:text-primary-700',
          'focus:text-primary-700',
          'hover:underline',
          'focus:underline',
        ],
        gray: [
          'text-gray-500',
          'hover:text-gray-700',
          'focus:text-gray-700',
          'hover:underline',
          'focus:underline',
        ],
        grayBlue: [
          'text-grayBlue-700',
          'hover:text-grayBlue-700',
          'focus:text-grayBlue-700',
          'hover:underline',
          'focus:underline',
        ],
        grayModern: [
          'text-grayModern-700',
          'hover:text-grayModern-700',
          'focus:text-grayModern-700',
          'hover:underline',
          'focus:underline',
        ],
        grayWarm: [
          'text-grayWarm-700',
          'hover:text-grayWarm-700',
          'focus:text-grayWarm-700',
          'hover:underline',
          'focus:underline',
        ],
        error: [
          'text-error-700',
          'hover:text-error-700',
          'focus:text-error-700',
          'hover:underline',
          'focus:underline',
        ],
        rose: [
          'text-rose-700',
          'hover:text-rose-700',
          'focus:text-rose-700',
          'hover:underline',
          'focus:underline',
        ],
        warning: [
          'text-warning-700',
          'hover:text-warning-700',
          'focus:text-warning-700',
          'hover:underline',
          'focus:underline',
        ],
        yellow: [
          'text-yellow-700',
          'hover:text-yellow-700',
          'focus:text-yellow-700',
          'hover:underline',
          'focus:underline',
        ],
        blueDark: [
          'text-blueDark-700',
          'hover:text-blueDark-700',
          'focus:text-blueDark-700',
          'hover:underline',
          'focus:underline',
        ],
        teal: [
          'text-teal-700',
          'hover:text-teal-700',
          'focus:text-teal-700',
          'hover:underline',
          'focus:underline',
        ],
        success: [
          'text-success-700',
          'hover:text-success-700',
          'focus:text-success-700',
          'hover:underline',
          'focus:underline',
        ],
        blue: [
          'text-blue-700',
          'hover:text-blue-700',
          'focus:text-blue-700',
          'hover:underline',
          'focus:underline',
        ],
        moss: [
          'text-moss-700',
          'hover:text-moss-700',
          'focus:text-moss-700',
          'hover:underline',
          'focus:underline',
        ],
        greenLight: [
          'text-greenLight-700',
          'hover:text-greenLight-700',
          'focus:text-greenLight-700',
          'hover:underline',
          'focus:underline',
        ],
        violet: [
          'text-violet-700',
          'hover:text-violet-700',
          'focus:text-violet-700',
          'hover:underline',
          'focus:underline',
        ],
        fuchsia: [
          'text-fuchsia-700',
          'hover:text-fuchsia-700',
          'focus:text-fuchsia-700',
          'hover:underline',
          'focus:underline',
        ],
        orangeDark: [
          'text-orangeDark-700',
          'hover:text-orangeDark-700',
          'focus:text-orangeDark-700',
          'hover:underline',
          'focus:underline',
        ],
        purple: [
          'text-purple-700',
          'hover:text-purple-700',
          'focus:text-purple-700',
          'hover:underline',
          'focus:underline',
        ],
        cyan: [
          'text-cyan-700',
          'hover:text-cyan-700',
          'focus:text-cyan-700',
          'hover:underline',
          'focus:underline',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'gray',
    },
  },
);

export const solidButton = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'gap-2',
    'text-base',
    'font-medium',
    'shadow-xs',
    'outline-none',
    'transition',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
  ],
  {
    variants: {
      colorScheme: {
        primary: [
          'text-white',
          'border',
          'border-solid',
          'bg-primary-600',
          'hover:bg-primary-700',
          'focus:bg-primary-700',
          'border-primary-600',
          'hover:border-primary-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        gray: [
          'text-white',
          'border',
          'border-solid',
          'bg-gray-600',
          'hover:bg-gray-700',
          'focus:bg-gray-700',
          'border-gray-600',
          'hover:border-gray-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        grayBlue: [
          'text-white',
          'border',
          'border-solid',
          'bg-grayBlue-600',
          'hover:bg-grayBlue-700',
          'focus:bg-grayBlue-700',
          'border-grayBlue-600',
          'hover:border-grayBlue-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        grayModern: [
          'text-white',
          'border',
          'border-solid',
          'bg-grayModern-600',
          'hover:bg-grayModern-700',
          'focus:bg-grayModern-700',
          'border-grayModern-600',
          'hover:border-grayModern-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        grayWarm: [
          'text-white',
          'border',
          'border-solid',
          'bg-grayWarm-600',
          'hover:bg-grayWarm-700',
          'focus:bg-grayWarm-700',
          'border-grayWarm-600',
          'hover:border-grayWarm-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        error: [
          'text-white',
          'border',
          'border-solid',
          'bg-error-600',
          'hover:bg-error-700',
          'focus:bg-error-700',
          'border-error-600',
          'hover:border-error-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        rose: [
          'text-white',
          'border',
          'border-solid',
          'bg-rose-600',
          'hover:bg-rose-700',
          'focus:bg-rose-700',
          'border-rose-600',
          'hover:border-rose-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        warning: [
          'text-white',
          'border',
          'border-solid',
          'bg-warning-600',
          'hover:bg-warning-700',
          'focus:bg-warning-700',
          'border-warning-600',
          'hover:border-warning-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        yellow: [
          'text-white',
          'border',
          'border-solid',
          'bg-yellow-600',
          'hover:bg-yellow-700',
          'focus:bg-yellow-700',
          'border-yellow-600',
          'hover:border-yellow-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        blueDark: [
          'text-white',
          'border',
          'border-solid',
          'bg-blueDark-600',
          'hover:bg-blueDark-700',
          'focus:bg-blueDark-700',
          'border-blueDark-600',
          'hover:border-blueDark-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        teal: [
          'text-white',
          'border',
          'border-solid',
          'bg-teal-600',
          'hover:bg-teal-700',
          'focus:bg-teal-700',
          'border-teal-600',
          'hover:border-teal-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        success: [
          'text-white',
          'border',
          'border-solid',
          'bg-success-600',
          'hover:bg-success-700',
          'focus:bg-success-700',
          'border-success-600',
          'hover:border-success-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        blue: [
          'text-white',
          'border',
          'border-solid',
          'bg-blue-600',
          'hover:bg-blue-700',
          'focus:bg-blue-700',
          'border-blue-600',
          'hover:border-blue-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        moss: [
          'text-white',
          'border',
          'border-solid',
          'bg-moss-600',
          'hover:bg-moss-700',
          'focus:bg-moss-700',
          'border-moss-600',
          'hover:border-moss-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        greenLight: [
          'text-white',
          'border',
          'border-solid',
          'bg-greenLight-600',
          'hover:bg-greenLight-700',
          'focus:bg-greenLight-700',
          'border-greenLight-600',
          'hover:border-greenLight-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        violet: [
          'text-white',
          'border',
          'border-solid',
          'bg-violet-600',
          'hover:bg-violet-700',
          'focus:bg-violet-700',
          'border-violet-600',
          'hover:border-violet-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        fuchsia: [
          'text-white',
          'border',
          'border-solid',
          'bg-fuchsia-600',
          'hover:bg-fuchsia-700',
          'focus:bg-fuchsia-700',
          'border-fuchsia-600',
          'hover:border-fuchsia-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        orangeDark: [
          'text-white',
          'border',
          'border-solid',
          'bg-orangeDark-600',
          'hover:bg-orangeDark-700',
          'focus:bg-orangeDark-700',
          'border-orangeDark-600',
          'hover:border-orangeDark-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        purple: [
          'text-white',
          'border',
          'border-solid',
          'bg-purple-600',
          'hover:bg-purple-700',
          'focus:bg-purple-700',
          'border-purple-600',
          'hover:border-purple-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
        cyan: [
          'text-white',
          'border',
          'border-solid',
          'bg-cyan-600',
          'hover:bg-cyan-700',
          'focus:bg-cyan-700',
          'border-cyan-600',
          'hover:border-cyan-700',
          'focus:shadow-ringPrimary',
          'focus-visible:shadow-ringPrimary',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'gray',
    },
  },
);

export const ghostButton = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'gap-2',
    'text-base',
    'font-medium',
    'shadow-xs',
    'outline-none',
    'transition',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
  ],
  {
    variants: {
      colorScheme: {
        primary: [
          'bg-transparent',
          'text-primary-500',
          'shadow-none',
          'hover:text-primary-700',
          'focus:text-primary-700',
          'hover:bg-primary-50',
          'focus:bg-primary-50',
        ],
        gray: [
          'bg-transparent',
          'shadow-none',
          'text-gray-500',
          'hover:text-gray-700',
          'focus:text-gray-700',
          'hover:bg-gray-50',
          'focus:bg-gray-50',
        ],
        grayBlue: [
          'bg-transparent',
          'text-grayBlue-500',
          'shadow-none',
          'hover:text-grayBlue-700',
          'focus:text-grayBlue-700',
          'hover:bg-grayBlue-50',
          'focus:bg-grayBlue-50',
        ],
        grayModern: [
          'bg-transparent',
          'text-grayModern-500',
          'shadow-none',
          'hover:text-grayModern-700',
          'focus:text-grayModern-700',
          'hover:bg-grayModern-50',
          'focus:bg-grayModern-50',
        ],
        grayWarm: [
          'bg-transparent',
          'text-grayWarm-500',
          'shadow-none',
          'hover:text-grayWarm-700',
          'focus:text-grayWarm-700',
          'hover:bg-grayWarm-50',
          'focus:bg-grayWarm-50',
        ],
        error: [
          'bg-transparent',
          'text-error-500',
          'shadow-none',
          'hover:text-error-700',
          'focus:text-error-700',
          'hover:bg-error-50',
          'focus:bg-error-50',
        ],
        rose: [
          'bg-transparent',
          'text-rose-500',
          'shadow-none',
          'hover:text-rose-700',
          'focus:text-rose-700',
          'hover:bg-rose-50',
          'focus:bg-rose-50',
        ],
        warning: [
          'bg-transparent',
          'text-warning-500',
          'shadow-none',
          'hover:text-warning-700',
          'focus:text-warning-700',
          'hover:bg-warning-50',
          'focus:bg-warning-50',
        ],
        yellow: [
          'bg-transparent',
          'text-yellow-500',
          'shadow-none',
          'hover:text-yellow-700',
          'focus:text-yellow-700',
          'hover:bg-yellow-50',
          'focus:bg-yellow-50',
        ],
        blueDark: [
          'bg-transparent',
          'text-blueDark-500',
          'shadow-none',
          'hover:text-blueDark-700',
          'focus:text-blueDark-700',
          'hover:bg-blueDark-50',
          'focus:bg-blueDark-50',
        ],
        teal: [
          'bg-transparent',
          'text-teal-500',
          'shadow-none',
          'hover:text-teal-700',
          'focus:text-teal-700',
          'hover:bg-teal-50',
          'focus:bg-teal-50',
        ],
        success: [
          'bg-transparent',
          'text-success-500',
          'shadow-none',
          'hover:text-success-700',
          'focus:text-success-700',
          'hover:bg-success-50',
          'focus:bg-success-50',
        ],
        blue: [
          'bg-transparent',
          'text-blue-500',
          'shadow-none',
          'hover:text-blue-700',
          'focus:text-blue-700',
          'hover:bg-blue-50',
          'focus:bg-blue-50',
        ],
        moss: [
          'bg-transparent',
          'text-moss-500',
          'shadow-none',
          'hover:text-moss-700',
          'focus:text-moss-700',
          'hover:bg-moss-50',
          'focus:bg-moss-50',
        ],
        greenLight: [
          'bg-transparent',
          'text-greenLight-500',
          'shadow-none',
          'hover:text-greenLight-700',
          'focus:text-greenLight-700',
          'hover:bg-greenLight-50',
          'focus:bg-greenLight-50',
        ],
        violet: [
          'bg-transparent',
          'text-violet-500',
          'shadow-none',
          'hover:text-violet-700',
          'focus:text-violet-700',
          'hover:bg-violet-50',
          'focus:bg-violet-50',
        ],
        fuchsia: [
          'bg-transparent',
          'text-fuchsia-500',
          'shadow-none',
          'hover:text-fuchsia-700',
          'focus:text-fuchsia-700',
          'hover:bg-fuchsia-50',
          'focus:bg-fuchsia-50',
        ],
        orangeDark: [
          'bg-transparent',
          'text-orangeDark-500',
          'shadow-none',
          'hover:text-orangeDark-700',
          'focus:text-orangeDark-700',
          'hover:bg-orangeDark-50',
          'focus:bg-orangeDark-50',
        ],
        purple: [
          'bg-transparent',
          'text-purple-500',
          'shadow-none',
          'hover:text-purple-700',
          'focus:text-purple-700',
          'hover:bg-purple-50',
          'focus:bg-purple-50',
        ],
        cyan: [
          'bg-transparent',
          'text-cyan-500',
          'shadow-none',
          'hover:text-cyan-700',
          'focus:text-cyan-700',
          'hover:bg-cyan-50',
          'focus:bg-cyan-50',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'gray',
    },
  },
);

export const outlineButton = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'gap-2',
    'text-base',
    'font-medium',
    'shadow-xs',
    'outline-none',
    'transition',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
  ],
  {
    variants: {
      colorScheme: {
        primary: [
          'bg-primary-50',
          'text-primary-700',
          'border',
          'border-solid',
          'border-primary-300',
          'hover:bg-primary-100',
          'hover:text-primary-700',
          'focus:bg-primary-100',
        ],
        gray: [
          'text-gray-700',
          'border',
          'border-solid',
          'border-gray-300',
          'hover:bg-gray-50',
          'hover:text-gray-700',
          'focus:bg-gray-50',
        ],
        grayBlue: [
          'bg-grayBlue-50',
          'text-grayBlue-700',
          'border',
          'border-solid',
          'border-grayBlue-300',
          'hover:bg-grayBlue-100',
          'hover:text-grayBlue-700',
          'focus:bg-grayBlue-100',
        ],
        grayModern: [
          'bg-grayModern-50',
          'text-grayModern-700',
          'border',
          'border-solid',
          'border-grayModern-300',
          'hover:bg-grayModern-100',
          'hover:text-grayModern-700',
          'focus:bg-grayModern-100',
        ],
        grayWarm: [
          'bg-grayWarm-50',
          'text-grayWarm-700',
          'border',
          'border-solid',
          'border-grayWarm-300',
          'hover:bg-grayWarm-100',
          'hover:text-grayWarm-700',
          'focus:bg-grayWarm-100',
        ],
        error: [
          'bg-error-50',
          'text-error-700',
          'border',
          'border-solid',
          'border-error-300',
          'hover:bg-error-100',
          'hover:text-error-700',
          'focus:bg-error-100',
        ],
        rose: [
          'bg-rose-50',
          'text-rose-700',
          'border',
          'border-solid',
          'border-rose-300',
          'hover:bg-rose-100',
          'hover:text-rose-700',
          'focus:bg-rose-100',
        ],
        warning: [
          'bg-warning-50',
          'text-warning-700',
          'border',
          'border-solid',
          'border-warning-300',
          'hover:bg-warning-100',
          'hover:text-warning-700',
          'focus:bg-warning-100',
        ],
        yellow: [
          'bg-yellow-50',
          'text-yellow-700',
          'border',
          'border-solid',
          'border-yellow-300',
          'hover:bg-yellow-100',
          'hover:text-yellow-700',
          'focus:bg-yellow-100',
        ],
        blueDark: [
          'bg-blueDark-50',
          'text-blueDark-700',
          'border',
          'border-solid',
          'border-blueDark-300',
          'hover:bg-blueDark-100',
          'hover:text-blueDark-700',
          'focus:bg-blueDark-100',
        ],
        teal: [
          'bg-teal-50',
          'text-teal-700',
          'border',
          'border-solid',
          'border-teal-300',
          'hover:bg-teal-100',
          'hover:text-teal-700',
          'focus:bg-teal-100',
        ],
        success: [
          'bg-success-50',
          'text-success-700',
          'border',
          'border-solid',
          'border-success-300',
          'hover:bg-success-100',
          'hover:text-success-700',
          'focus:bg-success-100',
        ],
        blue: [
          'bg-blue-50',
          'text-blue-700',
          'border',
          'border-solid',
          'border-blue-300',
          'hover:bg-blue-100',
          'hover:text-blue-700',
          'focus:bg-blue-100',
        ],
        moss: [
          'bg-moss-50',
          'text-moss-700',
          'border',
          'border-solid',
          'border-moss-300',
          'hover:bg-moss-100',
          'hover:text-moss-700',
          'focus:bg-moss-100',
        ],
        greenLight: [
          'bg-greenLight-50',
          'text-greenLight-700',
          'border',
          'border-solid',
          'border-greenLight-300',
          'hover:bg-greenLight-100',
          'hover:text-greenLight-700',
          'focus:bg-greenLight-100',
        ],
        violet: [
          'bg-violet-50',
          'text-violet-700',
          'border',
          'border-solid',
          'border-violet-300',
          'hover:bg-violet-100',
          'hover:text-violet-700',
          'focus:bg-violet-100',
        ],
        fuchsia: [
          'bg-fuchsia-50',
          'text-fuchsia-700',
          'border',
          'border-solid',
          'border-fuchsia-300',
          'hover:bg-fuchsia-100',
          'hover:text-fuchsia-700',
          'focus:bg-fuchsia-100',
        ],
        orangeDark: [
          'bg-orangeDark-50',
          'text-orangeDark-700',
          'border',
          'border-solid',
          'border-orangeDark-300',
          'hover:bg-orangeDark-100',
          'hover:text-orangeDark-700',
          'focus:bg-orangeDark-100',
        ],
        purple: [
          'bg-purple-50',
          'text-purple-700',
          'border',
          'border-solid',
          'border-purple-300',
          'hover:bg-purple-100',
          'hover:text-purple-700',
          'focus:bg-purple-100',
        ],
        cyan: [
          'bg-cyan-50',
          'text-cyan-700',
          'border',
          'border-solid',
          'border-cyan-300',
          'hover:bg-cyan-100',
          'hover:text-cyan-700',
          'focus:bg-cyan-100',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'gray',
    },
  },
);
