export {
  useGetContactCommunicationChannelsQuery,
  useGetContactPersonalDetailsQuery,
  useCreateContactMutation,
  useUpdateContactEmailMutation,
  useAddEmailToContactMutation,
  useRemoveEmailFromContactMutation,
  useUpdateContactPhoneNumberMutation,
  useRemovePhoneNumberFromContactMutation,
  useAddPhoneToContactMutation,
  useUpdateOrganizationMutation,
  useAddEmailToOrganizationMutation,
  useRemoveEmailFromOrganizationMutation,
  useUpdateOrganizationEmailMutation,
} from '../../graphQL/__generated__/generated';
export type {
  Contact,
  GetContactCommunicationChannelsQuery,
  GetContactPersonalDetailsQuery,
  ContactInput,
  CreateContactMutation,
  Email,
  UpdateContactEmailMutation,
  UpdateOrganizationMutation,
  AddEmailToOrganizationMutation,
  RemoveEmailFromOrganizationMutation,
  UpdateOrganizationEmailMutation,
  EmailUpdateInput,
} from '../../graphQL/__generated__/generated';
