name: user-admin-api

on:
  push:
    branches: [ "otter", "3920-test-coverage-announcer" ]
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/user-admin-api/**
      - .github/workflows/build-user-admin-api.yml
  pull_request:
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/user-admin-api/**
      - .github/workflows/build-user-admin-api.yml
  release:
    types: [created, edited]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/user-admin-api

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    working-directory: ./packages/server/user-admin-api

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Build
        working-directory: ./packages/server/user-admin-api
        run: make all

      - name: Configure Test Folders
        id: test-folders
        run: |
          test_folders=$(go list ./... | grep -v /gen | grep -v /test | paste -sd "," -)
          echo "::set-output name=test_folders::$test_folders"

      - name: Test
        run: |
          go install gotest.tools/gotestsum@latest
          gotestsum --junitfile unit-tests.xml -- -coverprofile=cover.out -coverpkg=${{ steps.test-folders.outputs.test_folders }} ./...

      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()    # run this step even if previous step failed
        with:
          report_paths: packages/server/user-admin-api/unit-tests.xml    # Path to test results
          include_passed: true
          annotate_only: true
          detailed_summary: true

      - name: Compute Code Coverage
        id: compute_code_coverage
        working-directory: ./packages/server/user-admin-api
        run: |
          echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "|Filename|Function|Coverage|" >> $GITHUB_STEP_SUMMARY
          echo "|--------|--------|--------|" >> $GITHUB_STEP_SUMMARY
          go tool cover -func=cover.out |sed -r  's/[[:space:]]+/|/g'|sed -r 's/$/|/g'|sed -r 's/^/|/g' >> $GITHUB_STEP_SUMMARY
          go tool cover -func=cover.out | sed -r 's/[[:space:]]+/|/g' | sed -r 's/$/|/g' | sed -r 's/^/|/g' | tail -n 1 > test-coverage.txt
          coverage=$(cat test-coverage.txt | awk -F'|' '{gsub(/%/, "", $(NF-1)); print $(NF-1)}')
          echo "::set-output name=computed_coverage::$coverage"

      - name: Send Output to Slack
        run: |
          computed_coverage="${{ steps.compute_code_coverage.outputs.computed_coverage }}"
          warning_threshold=80.0
          critical_threshold=50.0
          if (( $(echo "$computed_coverage > $warning_threshold" | bc -l) )); then
            curl -X POST -H 'Content-type: application/json' --data '{
              "text": "${{ github.workflow }} coverage ${{ steps.compute_code_coverage.outputs.computed_coverage }}:\n```\n'$(cat test-coverage.txt)'```\n"
            }' ${{ secrets.TEST_COVERAGE_SLACK_WEBHOOK_URL }}
          elif (( $(echo "$computed_coverage < $warning_threshold && $computed_coverage > $critical_threshold" | bc -l) )); then
            curl -X POST -H 'Content-type: application/json' --data '{
              "text": ":warning: ${{ github.workflow }} coverage is lower than the warning threshold of 80%:\n```\n'$(cat test-coverage.txt)'```\n"
            }' ${{ secrets.TEST_COVERAGE_SLACK_WEBHOOK_URL }}
          elif (( $(echo "$computed_coverage < $critical_threshold" | bc -l) )); then
            curl -X POST -H 'Content-type: application/json' --data '{
              "text": ":no_entry: ${{ github.workflow }} coverage is lower than the critical threshold of 50%:\n```\n'$(cat test-coverage.txt)'```\n"
            }' ${{ secrets.TEST_COVERAGE_SLACK_WEBHOOK_URL }}
          fi


  build-publish:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REPOSITORY_READ_WRITE_USERNAME }}
          password: ${{ secrets.REPOSITORY_READ_WRITE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./packages/server/
          file: ./packages/server/user-admin-api/Dockerfile
          push: ${{ github.ref_name == 'otter' || github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
