name: Build and Publish Transcription API

on:
  push:
    branches: [ "otter" ]
    paths:
      - packages/server/transcription-api/**
      - .github/workflows/build-publish-transcription-api.yml
  pull_request:
    paths:
      - packages/server/transcription-api/**
      - .github/workflows/build-publish-transcription-api.yml
  release:
    types: [created, edited]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/transcription-api

permissions:
  contents: read
  pull-requests: read

jobs:
  publish:
    if: github.ref_name == 'otter' || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REPOSITORY_READ_WRITE_USERNAME }}
          password: ${{ secrets.REPOSITORY_READ_WRITE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./packages/server/transcription-api
          file: ./packages/server/transcription-api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
