name: Build & Publish OpenAi API

on:
  push:
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/openai-api/**
      - .github/workflows/*-openai-api.yml
  release:
    types: [created, edited]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/openai-api

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Build
        working-directory: ./packages/server/openai-api
        run: make all

      - name: Test
        working-directory: ./packages/server/openai-api
        run: |
              go install gotest.tools/gotestsum@latest
              gotestsum --junitfile unit-tests.xml -- -coverprofile=cover.out ./...
      - name: Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()    # run this step even if previous step failed
        with:
          report_paths: packages/server/openai-api/unit-tests.xml    # Path to test results
          include_passed: true
          annotate_only: true
          detailed_summary: true

      - name: Compute Code Coverage
        working-directory: ./packages/server/openai-api
        run: | 
             echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
             echo "|Filename|Function|Coverage|" >> $GITHUB_STEP_SUMMARY
             echo "|--------|--------|--------|" >> $GITHUB_STEP_SUMMARY
             go tool cover -func=cover.out |sed -r  's/[[:space:]]+/|/g'|sed -r 's/$/|/g'|sed -r 's/^/|/g' >> $GITHUB_STEP_SUMMARY
  publish:
    needs:
      - build

    if: github.ref_name == 'otter' || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REPOSITORY_READ_WRITE_USERNAME }}
          password: ${{ secrets.REPOSITORY_READ_WRITE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./packages/server/
          file: ./packages/server/openai-api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
