name: spaces

on:
  push:
    branches: [ "otter", "4001-fe-test-coverage-announcer" ]
    paths:
      - 'packages/apps/spaces/**'
      - '.github/workflows/build-spaces.yml'
  pull_request:
    paths:
      - 'packages/apps/spaces/**'
      - '.github/workflows/build-spaces.yml'
  release:
    types: [ created, edited ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - run: npm install -g yarn

#      - name: Deploy test Environment
#        run: |
#          curl http://openline.sh/install.sh | sh
#          echo "[INFO] Starting Openline CLI..."
#          openline dev start
#          echo "[INFO] Checking Openline CLI services..."
#          openline dev ping
#          echo "[INFO] Checking PODs..."
#          kubectl -n openline get pods
#
#      - name: Run tests
#        run: |
#          cd packages/apps/spaces
#          yarn add -D jest --silent
#          yarn test

      - name: Check test coverage
        run: |
          git clone https://github.com/openline-ai/openline-test-harness.git
          cd openline-test-harness/spaces-coverage
          go mod tidy
          go build
          coverage=$(./spaces-coverage)
          echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "|Filename|Function|Coverage|" >> $GITHUB_STEP_SUMMARY
          echo "|--------|--------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "::set-output name=computed_coverage::$coverage"

      - name: Send Output to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
              "text": "TEST"
            }' ${{ secrets.TEST_COVERAGE_SLACK_WEBHOOK_URL_FE }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REPOSITORY_READ_WRITE_USERNAME }}
          password: ${{ secrets.REPOSITORY_READ_WRITE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: packages/apps/spaces/
          push: ${{ github.ref_name == 'otter' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ENV=cluster
