name: sync-gmail-raw

on:
  push:
    branches: [ "otter" ]
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/customer-os-common-auth/**
      - packages/runner/sync-gmail-raw/**
      - .github/workflows/build-sync-gmail-raw.yml
  pull_request:
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/customer-os-common-auth/**
      - packages/runner/sync-gmail-raw/**
      - .github/workflows/build-sync-gmail-raw.yml
  release:
    types: [created, edited]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/sync-gmail-raw

permissions:
  contents: read
  pull-requests: read
  packages: write

defaults:
  run:
    working-directory: ./packages/runner/sync-gmail-raw

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Build
        working-directory: ./packages/runner/sync-gmail-raw
        run: make all

      - name: Test
        working-directory: ./packages/runner/sync-gmail-raw
        run: |
              go install gotest.tools/gotestsum@latest
              gotestsum --junitfile unit-tests.xml -- -coverprofile=cover.out ./...
      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()    # run this step even if previous step failed
        with:
          report_paths: packages/runner/sync-gmail-raw/unit-tests.xml    # Path to test results
          include_passed: true
          annotate_only: true
          detailed_summary: true

      - name: Compute Code Coverage
        working-directory: ./packages/runner/sync-gmail-raw
        run: | 
             echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
             echo "|Filename|Function|Coverage|" >> $GITHUB_STEP_SUMMARY
             echo "|--------|--------|--------|" >> $GITHUB_STEP_SUMMARY
             go tool cover -func=cover.out |sed -r  's/[[:space:]]+/|/g'|sed -r 's/$/|/g'|sed -r 's/^/|/g' >> $GITHUB_STEP_SUMMARY

  build-publish:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare sources for docker build
        run: |
          mkdir tmp-sources
          mkdir tmp-sources/customer-os-common-module
          mkdir tmp-sources/customer-os-common-auth
          mkdir tmp-sources/sync-gmail-raw
          
          rsync -av --progress --exclude="tmp-sources" * tmp-sources/sync-gmail-raw
          cp .env tmp-sources/sync-gmail-raw/.env
          cp -r ../../server/customer-os-common-module/* tmp-sources/customer-os-common-module
          cp -r ../../server/customer-os-common-auth/* tmp-sources/customer-os-common-auth
          
          cp Dockerfile tmp-sources/Dockerfile

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REPOSITORY_READ_WRITE_USERNAME }}
          password: ${{ secrets.REPOSITORY_READ_WRITE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: packages/runner/sync-gmail-raw/.
          push: ${{ github.ref_name == 'otter' || github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
