name: Build and publish sync-tracked-data runner

on:
  push:
    branches: [ "otter" ]
    paths:
      - packages/runner/sync-tracked-data/**
      - .github/workflows/build-sync-tracked-data.yml
  pull_request:
    paths:
      - packages/runner/sync-tracked-data/**
      - .github/workflows/build-sync-tracked-data.yml
  release:
    types: [ created, edited ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/sync-tracked-data

permissions:
  contents: read
  pull-requests: read
  packages: write

defaults:
  run:
    working-directory: ./packages/runner/sync-tracked-data

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: stable

      - name: Build
        run: make all

      - name: Test
        run: gotestsum --junitfile unit-tests.xml -- -coverprofile=cover.out ./...

      - name: Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()    # run this step even if previous step failed
        with:
          report_paths: ./packages/runner/sync-tracked-data/unit-tests.xml    # Path to test results
          include_passed: true
          annotate_only: true
          detailed_summary: true

      - name: Compute Code Coverage
        run: |
          echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "|Filename|Function|Coverage|" >> $GITHUB_STEP_SUMMARY
          echo "|--------|--------|--------|" >> $GITHUB_STEP_SUMMARY
          go tool cover -func=cover.out |sed -r  's/[[:space:]]+/|/g'|sed -r 's/$/|/g'|sed -r 's/^/|/g' >> $GITHUB_STEP_SUMMARY

  publish:
    name: publish image
    needs:
      - build

    if: github.ref_name == 'otter' || github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REPOSITORY_READ_WRITE_USERNAME }}
          password: ${{ secrets.REPOSITORY_READ_WRITE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: packages/runner/sync-tracked-data/.
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
