name: Build comms-api

on:
  push:
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/comms-api/**
      - packages/server/customer-os-api/graph/schemas/**
      - .github/workflows/*-comms-api.yml
  pull_request:
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/comms-api/**
      - packages/server/customer-os-api/graph/schemas/**
      - .github/workflows/*-comms-api.yml
  release:
    types: [created, edited]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/comms-api

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Build
        working-directory: ./packages/server/comms-api
        run: make all

      - name: Test
        working-directory: ./packages/server/comms-api
        run: |
              go install gotest.tools/gotestsum@latest
              gotestsum --junitfile unit-tests.xml -- -coverprofile=cover.out ./...
      - name: Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()    # run this step even if previous step failed
        with:
          report_paths: packages/server/comms-api/unit-tests.xml    # Path to test results
          include_passed: true
          annotate_only: true
          detailed_summary: true

      - name: Compute Code Coverage
        working-directory: ./packages/server/comms-api
        run: | 
             echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
             echo "|Filename|Function|Coverage|" >> $GITHUB_STEP_SUMMARY
             echo "|--------|--------|--------|" >> $GITHUB_STEP_SUMMARY
             go tool cover -func=cover.out |sed -r  's/[[:space:]]+/|/g'|sed -r 's/$/|/g'|sed -r 's/^/|/g' >> $GITHUB_STEP_SUMMARY