name: spaces

on:
  push:
    branches: [ "otter",  "3945-fe-tests"]
    paths:
      - 'packages/apps/spaces/**'
      - '.github/workflows/build-spaces.yml'
  pull_request:
    paths:
      - 'packages/apps/spaces/**'
      - '.github/workflows/build-spaces.yml'
  release:
    types: [ created, edited ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g yarn

      - name: Deploy test Environment
        run: |
          curl http://openline.sh/install.sh | sh
          openline --help
          openline dev start -v
          openline dev ping
          kubectl -n openline get pods
          kubectl -n openline logs -f event-store-0

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REPOSITORY_READ_WRITE_USERNAME }}
          password: ${{ secrets.REPOSITORY_READ_WRITE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: packages/apps/spaces/
          push: ${{ github.ref_name == 'otter' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ENV=cluster