name: customer-os-api-custom

on:
  push:
    branches: [ "silviu/cos-6148-test-workflow" ]  # Replace with your desired branch name
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/customer-os-postgres-repository/**
      - packages/server/customer-os-neo4j-repository/**
      - packages/server/events-processing-proto/**
      - packages/server/events/**
      - packages/server/validation-api/**
      - packages/server/enrichment-api/**
      - packages/server/customer-os-api/**
      - .github/workflows/build-customer-os-api.yml
      - .github/workflows/build-customer-os-api-custom.yml
  pull_request:
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/customer-os-postgres-repository/**
      - packages/server/customer-os-neo4j-repository/**
      - packages/server/events-processing-proto/**
      - packages/server/events/**
      - packages/server/validation-api/**
      - packages/server/enrichment-api/**
      - packages/server/customer-os-api/**
      - .github/workflows/build-customer-os-api-custom.yml
  release:
    types: [ created, edited ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/customer-os-api
  GOMODCACHE: ${{ github.workspace }}/go/pkg/mod
  GOBIN: ${{ github.workspace }}/go/bin

permissions:
  contents: write
  pull-requests: read
  packages: write

defaults:
  run:
    working-directory: ./packages/server/customer-os-api

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          "repository",
          "rest",
          "other"
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
        env:
          GOPROXY: "direct"
          GOSUMDB: "off"
          GOMODCACHE: ${{ github.workspace }}/go/pkg/mod

      - name: Checkout deploy scripts
        uses: actions/checkout@v4
        with:
          repository: customeros/cloud
          path: './cloud'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: main

      - name: Run deploy script
        working-directory: ./cloud/deployment/sandbox/_deployment
        env:
          IMAGE_VERSION: ${{ steps.version.outputs.version }}
        run: |
          cat customer-os-api.sh