name: CustomerOS API Deploy

on:
  push:
    branches:
      - otter
    paths:
      - ".github/workflows/customer-os-api-deploy.yml"
      - "packages/server/customer-os-api/**"
      - "packages/server/customer-os-common-module/**"
      - "packages/server/customer-os-neo4j-repository/**"
      - "packages/server/customer-os-postgres-repository/**"
  workflow_dispatch:

env:
  APP_NAME: customer-os-api
  APP_PATH: packages/server/customer-os-api
  IMAGE_NAME: customer-os-api
  REGISTRY: ghcr.io
  GQL_PATH: gqlgen.yml
  CGO_ENABLED: 0
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  CLOUD_REPO: customeros/cloud

permissions:
  contents: write
  pull-requests: read
  packages: write

jobs:
  deploy:
    runs-on: ubicloud-standard-2

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if release is required
        run: |
          RELEASE_NEEDED=$(./deployment/runners/check-release-needed.sh)
          echo "RELEASE_NEEDED=$RELEASE_NEEDED" >> $GITHUB_ENV

      - name: Set up Go
        if: github.env.RELEASE_NEEDED == 'true'
        uses: ubicloud/setup-go@v5
        with:
          go-version: 1.24.2
          cache: true
        env:
          GOPROXY: "direct"
          GOSUMDB: "off"

      - name: Install dependencies
        if: github.env.RELEASE_NEEDED == 'true'
        run: |
          ./deployment/runners/install-dependencies.sh

      - name: Build Go binary
        if: github.env.RELEASE_NEEDED == 'true'
        run: |
          ./deployment/runners/build.sh -p ${{ env.APP_PATH }} ${{ env.GQL_PATH }}

      - name: Generate version number
        if: github.env.RELEASE_NEEDED == 'true'
        id: version
        run: |
          VERSION=$(./deployment/runners/generate-version.sh)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        if: github.env.RELEASE_NEEDED == 'true'
        run: |
          ./deployment/runners/create-release-tag.sh

      - name: Create release
        if: github.env.RELEASE_NEEDED == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.env.VERSION }}
          name: Release ${{ github.env.VERSION }}
          generate_release_notes: true

      - name: Login to GitHub Container Registry
        if: github.env.RELEASE_NEEDED == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_TRIGGER_GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: github.env.RELEASE_NEEDED == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and push container image
        if: github.env.RELEASE_NEEDED == 'true'
        run: |
          ./deployment/runners/build-and-push-image.sh \
            ${{ env.REGISTRY }} \
            ${{ env.IMAGE_NAME }} \
            ${{ github.env.VERSION }} \
            "linux/arm64" \
            "arm64" \
            "customeros" \
            ${{ env.APP_PATH }}

#      - name: Checkout cloud repo
#        if: github.env.RELEASE_NEEDED == 'true'
#        uses: actions/checkout@v4
#        with:
#          repository: ${{ env.CLOUD_REPO }}
#          token: ${{ secrets.CLOUD_REPO_KEY }}
#          path: cloud-repo
#          fetch-depth: 1
#
#      - name: Update cloud version
#        if: github.env.RELEASE_NEEDED == 'true'
#        run: |
#          ./deployment/runners/update-cloud.sh ${{ env.APP_NAME }} ${{ github.env.VERSION }} 