name: Leads Build and Release

on:
  pull_request:
    paths:
      - packages/server/leads/**
      - .github/workflows/leads-workflow.yml
  push:
    branches:
      - otter
    paths:
      - packages/server/leads/**
      - .github/workflows/leads-workflow.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/customer-os-leads

permissions:
  contents: write
  pull-requests: read
  packages: write

jobs:
  leads-pipeline:
    runs-on: ubicloud-standard-2
    steps:
      - uses: elves/setup-elvish@v1
        with:
          elvish-version: HEAD
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run build script (PR)
        if: github.event_name == 'pull_request'
        run: elvish ./packages/server/leads/deployments/build/build.elv

      - name: Run full pipeline (otter branch)
        if: github.event_name == 'push' && github.ref == 'refs/heads/otter'
        run: elvish ./packages/server/leads/deployments/build/leads-pipeline.elv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
