name: JMeter Pipeline

on:
  workflow_dispatch:
    inputs:
      #      environment:
      #        description: 'Environment ( eg: production | dev | preview-edi | preview-cali | preview-kasia )'
      #        required: true
      environment:
        type: choice
        description: 'Environment ( eg: dev, prod )'
        required: true
        options:
          - dev
          - prod

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run COS api performance testing suite
        run: |
          if ! command -v jmeter >/dev/null; then
            wget -q https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.tgz
            tar -xf apache-jmeter-5.6.tgz
            export PATH=$PATH:$PWD/apache-jmeter-5.6/bin
          fi
          
          # Run JMeter script and generate JTL file
          ls -l performance_testing/cos_api.jmx
          jmeter -n -t performance_testing/cos_api.jmx -Jsummariser.out=false -JX-Openline-API-KEY=${{ secrets.DEV_CUSTOMER_OS_ADMIN_API_KEY }} -l test_results.jtl

      - name: Check average response time
        run: |
          averageResponseTime=$(awk -F',' '{sum+=$2; count++} END {print sum/count}' test_results.jtl)
          responseTimeThreshold=100
          echo "responseTimeThreshold=$responseTimeThreshold" >> $GITHUB_ENV
          echo "averageResponseTime=$averageResponseTime" >> $GITHUB_ENV

          if [[ $(bc <<< "$averageResponseTime > $responseTimeThreshold") -eq 1 ]]; then
            echo "Average response time ($averageResponseTime ms) exceeds threshold of $responseTimeThreshold ms."
            echo "::set-output name=threshold_exceeded::true"
          fi
        id: check_response_time

      - name: Tests failure
        if: steps.check_response_time.outputs.threshold_exceeded == 'true'
        run: |
          echo "::error title=Average response time ($averageResponseTime ms) exceeds the threshold of $responseTimeThreshold ms."
          exit 1

      - name: Tests passed
        if: steps.check_response_time.outputs.threshold_exceeded != 'true'
        run: |
          echo "::notice title=Average response time ($averageResponseTime ms) doesn't exceed the threshold of $responseTimeThreshold ms."
