name: Publish Check If Email Exists

on:
  push:
    branches: [ "2088-support-check-if-email-exists-api" ]
    paths:
      - .github/workflows/*-check-if-email-exists-api.yml
  release:
    types: [created, edited]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/check-if-email-exists-api

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  publish:

    if: github.ref_name == 'otter' || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REPOSITORY_READ_WRITE_USERNAME }}
          password: ${{ secrets.REPOSITORY_READ_WRITE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Extract Zip File
        working-directory: ./packages/server/check-if-email-exists-api
        run: |
          unzip v0.9.0.zip

      - name: Push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./packages/server/check-if-email-exists-api/check-if-email-exists-0.9.0
          file: ./packages/server/check-if-email-exists-api/check-if-email-exists-0.9.0/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
